GitGuardian/ggshield

.gitguardian.example.yml
Pipfile.lock
README.md
ggshield/cmd.py
ggshield/config.py
tests/test_config.py

- Adds support for API URL config in the config.
- Documents existing support for env variable of `GITGUARDIAN_API_URL`
- Makes adding options+defaults more simple and avoiding typos (only one source for key name)

Jguer/ /add url config

---

.gitguardian.example.yml
README.md
ggshield/cmd.py
ggshield/config.py
tests/cassettes/test_scan_file_secret.yaml
tests/test_cli.py

- Add `exit zero` behavior to force scan exit code to be always 0
- Adds `--exit-zero` flag
- Adds `GITGUARDIAN_EXIT_ZERO` environment variable

feat(gg-shield): add exit-zero

---

README.md
doc/pre-receive-python.sample

- Adds git pre-receive hook using only python without docker

Add python pre-receive

---

ggshield/filter.py
ggshield/scannable.py
ggshield/utils.py

- Fix matches not getting updated with correct patch position due to bool evaluation of `0`

fix(display): Fix single line of index 0 breaking display

---

README.md
ggshield/dev_scan.py
ggshield/git_shell.py
ggshield/utils.py

- Add support for scanning repositories already cloned

Support path scanning repos

---

Dockerfile

- Allow ssh git clone inside image
- More permissive workdir folder

fix(dockerfile): allow running ssh in docker container

---

ggshield/config.py
ggshield/dev_scan.py
ggshield/filter.py
ggshield/git_shell.py
ggshield/message.py
ggshield/scannable.py
ggshield/text_utils.py
ggshield/utils.py
setup.cfg
setup.py
tests/test_scannable.py
tests/test_text_utils.py

- Add author display as in `git` on scan

Add author display

---

ggshield/dev_scan.py
ggshield/filter.py
ggshield/git_shell.py
ggshield/install.py
ggshield/scannable.py
tests/test_git_shell.py

fix(git): do not use cwd git

---

.gitguardian.example.yml
.github/workflows/main.yml
.pre-commit-config.yaml
README.md
ggshield/ci.py
ggshield/cmd.py
ggshield/config.py
ggshield/dev_scan.py
ggshield/output/__init__.py
ggshield/output/json/__init__.py
ggshield/output/json/json_output.py
ggshield/output/json/schemas.py
ggshield/output/output_handler.py
ggshield/output/text/__init__.py
ggshield/output/text/message.py
ggshield/output/text/text_output.py
ggshield/path.py
ggshield/scan/__init__.py
ggshield/scan/scannable.py
ggshield/text_utils.py
pyproject.toml
tests/output/snapshots/snap_test_json_output.py
tests/output/snapshots/snap_test_message.py
tests/output/snapshots/snap_test_text_output.py
tests/output/test_json_output.py
tests/output/test_message.py
tests/output/test_text_output.py
tests/scan/test_scannable.py
tests/test_cli.py
tests/test_text_utils.py

**Added**
- `-o` `--output` Allows outputting result to a file
- `--json` output scan result as a JSON 
- Allow output of normal text to `-o` as well
**TODO**
- Missing documentation, must be added before merge
**Example output**
```json
{
"id": "https://github.com/GitGuardian/py-gitguardian.git",
"type": "commit-range",
"scans": [
{
"id": "164490d66e382c1cb49337ca02511224c931d403",
"type": "commit",
"entities_with_issues": [
{
"mode": "MODIFY",
"filename": "README.md",
"issues": [
{
"policy": "Secrets detection",
"occurrences": [
{
"index_end": 28,
"type": "username",
"line_start": 12,
"line_end": 12,
"match": "je******er",
"index_start": 18
},
{
"index_end": 54,
"type": "password",
"line_start": 12,
"line_end": 12,
"match": "corre***************taple",
"index_start": 29
},
{ …
```

Add JSON output and file output

---

README.md

Fix documentation hyper links to ease usability

Fix readme pre receive link

---

README.md

- Explain different ignore mechanisms on `gg-shield`

docs(readme): document ggignore

---

.github/workflows/main.yml

ci(python): test against python39

---

ggshield/dev_scan.py
tests/test_cli.py

- Attempt to propose a correct url if possible

feat(qol): add warning when it's possible to correct the url

---

.github/workflows/tag.yml
ggshield/dev_scan.py
ggshield/scan/scannable.py

- Add automatic changelogs
- Limit threads for scanning ( avoid heavy request rate)

Jguer/ /prepare release

---

ggshield/config.py
tests/test_ignore.py

Ignore adds policy break ignore SHA instead of all matches

Ignore adds policy break sha instead of all matches

---

.gitguardian.yaml
ggshield/config.py

- Fix invalid yaml generated from command

fix(ggshield): fix yaml writing

---

README.md

docs(ggshield): fix match ignore key

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
README.md
ggshield/ci.py
ggshield/cmd.py
ggshield/config.py
ggshield/dev_scan.py
ggshield/hook_cmd.py
ggshield/install.py
ggshield/utils.py
tests/conftest.py
tests/test_cli.py
tests/test_hook_cmd.py
tests/test_ignore.py
tests/test_install.py
tests/test_scan.py

- Add pre-push hooks
- Add pre-push install command

Add pre push hooks

---

ggshield/cmd.py

This is in reference to https://github.com/GitGuardian/gg-shield/issues/51

Add --version option

---

.pre-commit-config.yaml
CONTRIBUTING.md
Makefile
README.md
SECURITY.md

- Add CONTRIBUTING.md
- Add base SECURITY.md

Add contributing guidelines

---

ggshield/output/json/json_output.py
ggshield/output/json/schemas.py
ggshield/utils.py
tests/test_utils.py

fix(json): fix line display on JSON output

---

ggshield/utils.py

fix(urlib): do not warn if the user knows he's disabling SSL verification

Do not warn if the user knows he's disabling SSL verification

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.pre-commit-config.yaml
Pipfile
Pipfile.lock
ggshield/status.py
ggshield/text_utils.py
pyproject.toml
tests/cassettes/quota.yaml
tests/cassettes/quota_half_remaining.yaml
tests/cassettes/quota_low_remaining.yaml
tests/cassettes/test_health_check.yaml
tests/cassettes/test_health_check_error.yaml
tests/snapshots/snap_test_cli.py

Fix typo app version

---

.gitguardian.example.yml
.github/workflows/main.yml
.pre-commit-config.yaml
Pipfile
Pipfile.lock
README.md
ggshield/config.py
setup.py

Closes #105 
- Update dev dependencies
- Add new options to examples

Sync documentation and update dev dependencies

---

ggshield/git_shell.py

Skip over utf-8 conversion errors. Closes #108

Ignore utf-8 conversion errors

---

ggshield/output/json/json_output.py
ggshield/output/json/schemas.py
ggshield/output/text/message.py
ggshield/status.py
tests/output/snapshots/snap_test_json_output.py
tests/output/test_json_output.py
tests/snapshots/snap_test_status_cli.py
tests/test_path_scan_cli.py

If API delivers validity info:
If not:
---
Also add api url to api-status to verify if there's wrong overrides

Add validity display

---

.gitguardian.example.yml
README.md
ggshield/cmd.py
tests/test_prereceive_cmd.py

- Add max-hook configurable by env variable

Add max-hook configurable by env variable

---

ggshield/pre_receive_cmd.py
tests/test_prereceive_cmd.py

On remote bare repositories, HEAD is the main branch (result of git ls-remote origin HEAD).
We can use this to try and get a rev-list between the two

feat(pre-receive): try to diff against HEAD

---

.github/workflows/tag.yml

- Fix small issue where release-notary is running before the release is actually published
- Implement https://github.com/linkedin/shiv to produce easy to distribute zipapps

Implement shiv -- upload .pyz on release

---

README.md

Top of README Azure Pipelines links was wrong

docs(README): fix azure pipelines link

---

.pre-commit-hooks.yaml

Description will appear in pre-commit hook page https://pre-commit.com/hooks.html

doc(pre-commit): add description to hooks

---

README.md

This PR just fixed the presentation of pre-receive documentation

Polish pre-receive doc

---

ggshield/iac/filter.py
ggshield/scan/scannable.py
tests/iac/test_filter.py
tests/scan/test_scannable.py

- Adding a filter for IAC files based on the extension of the file, on excluded patterns and on the git status of the file (based on the ignore_git flag)
- Added unit tests

feat: Adding a filter for IAC files

---

ggshield/core/client.py
tests/cassettes/test_iac_scan_empty_directory.yaml
tests/cassettes/test_iac_scan_error_response.yaml
tests/cassettes/test_iac_scan_multiple_files.yaml
tests/cassettes/test_iac_scan_multiple_vulnerabilities.yaml
tests/cassettes/test_iac_scan_no_vulnerabilities.yaml
tests/cassettes/test_iac_scan_single_vulnerability.yaml

This MR updates the endpoint for IaC scan since we changed the naming

Fix iac scanning endpoint

---

.github/workflows/main.yml

Run tests on Python 3.10

---

tests/cmd/auth/test_login.py
tests/cmd/scan/test_docker.py
tests/cmd/scan/test_path.py
tests/cmd/scan/test_prepush.py
tests/cmd/scan/test_prereceive.py
tests/cmd/scan/test_repo.py
tests/cmd/test_install.py
tests/cmd/test_status.py
tests/conftest.py

Add test method in conftest to factorize cli_fs_runner calls

---

.github/workflows/main.yml
tests/cmd/auth/test_login.py
tests/cmd/scan/test_docker.py
tests/cmd/scan/test_path.py
tests/cmd/scan/test_prepush.py
tests/cmd/scan/test_prereceive.py
tests/cmd/scan/test_repo.py
tests/cmd/test_install.py
tests/cmd/test_status.py
tests/conftest.py

This PR merges main in the iac branch, bringing in the latest fixes, including the new `assert_invoke_ok()` and `assert_invoke_exited_with()` test helpers.

Upmerge main

---

README.md

Add a readme for the IaC section.

docs(iac): add readme for iac section

---

Pipfile.lock
setup.py

Update minimum version of pygitguardian to 1.3.5

---

ggshield/cmd/main.py
ggshield/output/output_handler.py
ggshield/scan/scannable.py
tests/output/test_iac_text_output.py

fix(iac): fix iac exit code to return a non zero code in case of an error
Updated unit tests

fix(iac): fix iac exit code to return a non zero code in case of an error

---

tests/conftest.py
tests/core/test_utils.py

Made those while investigating merge commit parser issues.
- Fix formatting of `_SINGLE_DELETE_PATCH`
- Modernize `test_utils.test_make_indices_patch`

Minor test improvements

---

ggshield/scan/repo.py

refactor: fix typo in repo.py

---

ggshield/cmd/secret/scan/path.py
ggshield/core/constants.py
ggshield/scan/repo.py
ggshield/scan/scannable.py

Same as https://github.com/GitGuardian/ggshield/pull/348 with slight improvements.

Modified value of multi-threads for ggshield

---

ggshield/cmd/install.py
ggshield/cmd/secret/scan/prepush.py
ggshield/cmd/secret/scan/prereceive.py
ggshield/core/git_shell.py
tests/cmd/scan/test_prepush.py
tests/cmd/scan/test_prereceive.py
tests/cmd/test_install.py
tests/repository.py

This PR adds functional tests in addition to unit tests.
For now the tests are run for each PR. We may change this if this cause problems.
The functional tests are in the `functests` directory.

Add functional tests

---

ggshield/cmd/main.py
ggshield/core/check_updates.py
ggshield/core/utils.py
tests/unit/core/test_check_updates.py

When the command is called, look for updates by requesting the latest release on GitHub. Save the latest version in a local file to only query GitHub once per day.
closes #299

feat: Check for updates and display a warning when an update is available 

---

ggshield/core/check_updates.py
tests/unit/core/test_check_updates.py

- Wait only 5s. This prevents blocking if api.github.com is not reachable.
- Catch all exceptions.
- Always store check time even in case of failure. This prevents retrying at each command in case api.github.com can never be reached from the customer machine.

Make check_updates() more robust

---

.pre-commit-hooks.yaml
ggshield/cmd/secret/scan/precommit.py
ggshield/cmd/secret/scan/prepush.py
ggshield/cmd/secret/scan/prereceive.py
ggshield/core/text_utils.py
ggshield/core/utils.py
ggshield/output/text/message.py
ggshield/output/text/text_output_handler.py
tests/functional/secret/test_scan_docset.py
tests/unit/cmd/scan/test_docker.py
tests/unit/cmd/scan/test_path.py
tests/unit/cmd/scan/test_prepush.py
tests/unit/cmd/scan/test_prereceive.py
tests/unit/output/snapshots/snap_test_text_output.py
tests/unit/output/test_iac_text_output.py

pre-commit
pre-push
pre-receive

rework outputs of pre-commit, pre-push and pre-receive

---

Pipfile.lock
scripts/update-pipfile-lock/Dockerfile

This PR does two things:
- Fix a failure in the update-pipfile-lock script
- Actually update the Pipfile.lock

Update Pipfile.lock and its generation script

---

ggshield/core/text_utils.py
ggshield/output/text/iac_text_output_handler.py
ggshield/output/text/message.py

Modifying output of iac scanner to print the severity of a vulnerability.

style(iac): #PLC-304 output iac vulnerability severity

---

Pipfile.lock

chore: update Pipfile.lock to update certifi

---

.pre-commit-config.yaml

Follow up to the release of ggshield 1.14.4

chore: use ggshield 1.14.4

---

Pipfile.lock

Update the `Pipfile.lock`.  
No significant changes in dependencies.

chore: update Pipfile.lock

---

ggshield/scan/docker.py
tests/unit/scan/test_scan_docker.py

Checks if image name is tagged, and adds :latest if it is not
Fixes #468

fix: add :latest tag to image name before save

---

.github/workflows/main.yml
.github/workflows/tag.yml
ggshield/cmd/secret/scan/ci.py
ggshield/core/cache.py
ggshield/core/client.py
ggshield/core/config/utils.py
ggshield/core/constants.py
ggshield/core/errors.py
ggshield/core/filter.py
ggshield/core/git_shell.py
ggshield/core/types.py
ggshield/output/text/message.py
ggshield/scan/docker.py
ggshield/scan/scanner.py
setup.py
tests/unit/cmd/scan/test_pypi.py
tests/unit/core/test_cache.py
tests/unit/output/snapshots/snap_test_text_output.py
tests/unit/output/test_text_output.py
tests/unit/scan/snapshots/snap_test_scannable.py
tests/unit/scan/test_scan_docker.py
tests/unit/scan/test_scan_docset.py

It's not exactly spring, but while working on #473, I found an unused function in ggshield/core/client.py (`load_detail()`), and decided to do a bit of clean up.
- Use [vulture][] to detect and remove unused code.
- Use [pyupgrade --py37-plus][pyup] to modernize the code.
- Look at GitHub CI summary to update deprecated commands in CI setup.
[vulture]: https://pypi.org/project/vulture
[pyup]: https://pypi.org/project/pyupgrade

Spring cleanup

---

.github/workflows/tag.yml
Pipfile.lock

This PR does two things:
- Fix the tagging part of the CI, which I broke while modernizing it 🤦🏻‍♂️ 
- Update our Pipfile.lock

Post release fixes

---

.github/workflows/ci.yml
Pipfile

This PR prepares fixes the CI for the 1.15.x branch.

Prepare the 1.15.x branch

---

Pipfile.lock
changelog.d/20230427_182700_antonin.lacombe_create_honeytoken.md
ggshield/cmd/honeytoken/__init__.py
ggshield/cmd/honeytoken/create.py
ggshield/cmd/main.py
ggshield/core/config/config.py
setup.py
tests/unit/cassettes/test_honeytoken_create_ok.yaml
tests/unit/cassettes/test_honeytoken_create_ok_no_name.yaml
tests/unit/cmd/honeytoken/test_honeytoken.py

Add a new `ggshield honeytoken create` commande to create honeytokens for workspace manager

Add honeytoken create command

---

ggshield/cmd/main.py
ggshield/cmd/sca/__init__.py
ggshield/cmd/sca/scan.py

Not adding test for commands for now, I don't think there really is a point.

feat(sca): add empty scan commands

---

ggshield/sca/client.py
tests/unit/cassettes/test_compute_sca_files.yaml
tests/unit/sca/test_client.py

feat(sca): add client with compute_sca_files method

---

ggshield/cmd/iac/scan/diff.py

Note to myself: after merging, check if unit tests on output still work (#569)

feat(iac): #IAC-48 add a beta warning for iac scan diff

---

ggshield/cmd/sca/scan.py

Adds a decorator to print a warning message for SCA features being in beta.

feat(sca): #PLC-768 add warning beta message for sca commands

---

ggshield/sca/sca_scan_models.py

Defined the same output schema as the one defined in backend.
I don't think we need any schema for the input, we should do the same as what is done for IaC. Do you agree @amascia-gg ?

feat(sca): #PLC-761 add sca full scan output schema

---

ggshield/cmd/sca/scan.py
ggshield/sca/client.py
ggshield/sca/file_selection.py
ggshield/sca/sca_scan_models.py
ggshield/scan/scan_mode.py
tests/unit/cassettes/test_sca_get_scan_all_filepaths.yaml
tests/unit/cassettes/test_sca_scan_all_no_file.yaml
tests/unit/cassettes/test_sca_scan_all_valid.yaml
tests/unit/cassettes/test_sca_scan_directory_invalid_tar.yaml
tests/unit/cassettes/test_sca_scan_directory_valid.yaml
tests/unit/cmd/sca/test_scan.py
tests/unit/data/Pipfile.lock
tests/unit/sca/test_client.py
tests/unit/sca/test_file_selection.py

This PR implements SCA scan all command logic.
- input: a directory
- filters sca related files with a call to SCA compute files API
- (NOT IMPLEMENTED) launches the SCA scan with a call to SCA public api (not merged in backend for now)
- returns the raw_results (output handling will be done later)

feat(sca): #PLC-763 sca scan all command

---

ggshield/core/errors.py

This small PR slightly improve the internal documentation for our exit codes, now that we are adding exit codes to the user documentation.

Document exit codes

---

README.md
doc/dev/architecture.md
ggshield/cmd/iac/__init__.py

chore(iac): rename Infrastructure as Code to Infra as Code Security

---

ggshield/cmd/sca/scan.py
ggshield/sca/client.py
ggshield/sca/file_selection.py
tests/unit/cassettes/test_sca_scan_diff.yaml
tests/unit/cmd/sca/test_scan.py

Like in SCA scan all, the output_handler is not implemented yet.

chore(sca): #PLC-764 Implement scan_diff command

---

.gitguardian.example.yml

Update `.gitguardian.example.yaml` with IaC command

feat(iac): #IAC-112 update example with iac command

---

ggshield/cmd/hmsl/decrypt.py
tests/unit/cmd/hmsl/test_check.py

This PR proposes improvements in messages displayed to users when no leak has been found by HMSL:
- more cheerful text message if no leak is found
- warning color in other cases
- count of leaks found to avoid empty json array as sole output if no leak has been found

imp(hmsl): #EXPL-150 more cheerfull message when no leak has been found

---

ggshield/cmd/sca/scan.py
ggshield/cmd/sca/scan_utils.py
ggshield/core/text_utils.py
ggshield/sca/collection/__init__.py
ggshield/sca/collection/collection.py
ggshield/sca/output/__init__.py
ggshield/sca/output/handler.py
ggshield/sca/output/text_handler.py
tests/conftest.py
tests/unit/cassettes/test_sca_scan_all_cmd.yaml
tests/unit/cmd/sca/test_scan.py

xblanchot/plc 824/sca all text output

---

ggshield/cmd/sca/scan.py
ggshield/core/constants.py
ggshield/core/text_utils.py
ggshield/sca/output/handler.py
ggshield/sca/output/text_handler.py
tests/unit/cassettes/test_sca_scan_pre_commit_no_arg.yaml
tests/unit/cassettes/test_sca_scan_pre_commit_with_added_vulns.yaml
tests/unit/cmd/sca/test_scan.py

feat(sca): add text output for sca scan pre-commit

---

.pre-commit-hooks.yaml

Add pre-commit and pre-push hooks for IaC commands.

feat(iac): #IAC-113 add pre-commit hooks

---

.gitguardian.example.yml
ggshield/cmd/sca/scan/sca_scan_utils.py
ggshield/core/config/user_config.py
ggshield/sca/sca_scan_models.py
tests/unit/core/config/test_user_config.py

- added sca in configuration file .gitguardian.example.yaml
- added `ignored_vulnerabilities` pararms for sca scans.

feat(sca): add ignored_vulnerabilities parameters to sca commands

---

changelog.d/20230801_183736_henri.hubert_allow_scan_all_pre_commit.md
ggshield/cmd/sca/scan/precommit.py
tests/unit/cassettes/test_sca_scan_pre_commit_all.yaml
tests/unit/cmd/sca/test_precommit.py
tests/unit/cmd/sca/test_scan.py

- Add flag
- Refactor tests for pre-commit

feat(sca): add all flag for pre-commit command

---

changelog.d/20230802_153039_henri.hubert_add_sca_scan_diff.md
ggshield/cmd/common_options.py
ggshield/cmd/iac/scan/diff.py
ggshield/cmd/sca/scan/__init__.py
ggshield/cmd/sca/scan/diff.py
tests/conftest.py
tests/functional/sca/test_sca_scan_diff.py
tests/unit/cassettes/test_sca_scan_diff_no_vuln.yaml
tests/unit/cassettes/test_sca_scan_diff_vuln.yaml
tests/unit/cmd/sca/test_diff.py

Add scan diff command. This will allow users to perform a differential scan with custom reference.

feat(sca): add scan diff command

---

ggshield/cmd/common_options.py
ggshield/cmd/iac/scan/prereceive.py
ggshield/cmd/sca/scan/__init__.py
ggshield/cmd/sca/scan/ci.py
ggshield/cmd/sca/scan/diff.py
ggshield/cmd/sca/scan/precommit.py
ggshield/cmd/sca/scan/prepush.py
ggshield/cmd/sca/scan/prereceive.py
ggshield/cmd/sca/scan/sca_scan_utils.py
tests/functional/conftest.py
tests/functional/iac/test_iac_scan_prereceive.py
tests/functional/sca/test_sca_scan_prereceive.py
tests/repository.py
tests/unit/cassettes/test_sca_scan_prereceive_no_sca_changes.yaml
tests/unit/cassettes/test_sca_scan_prereceive_no_sca_changes_all.yaml
tests/unit/cassettes/test_sca_scan_prereceive_no_sca_files.yaml
tests/unit/cassettes/test_sca_scan_prereceive_no_sca_files_all.yaml
tests/unit/cassettes/test_sca_scan_prereceive_with_vuln.yaml
tests/unit/cassettes/test_sca_scan_prereceive_with_vuln_all.yaml
tests/unit/cmd/sca/test_scan.py
tests/unit/cmd/sca/test_scan_prereceive.py
tests/unit/cmd/scan/test_prereceive.py

Added sca pre-receive command and functional tests

feat(sca): add sca pre-receive command

---

Pipfile.lock
changelog.d/20230808_105814_aurelien.gateau_update_cryptography.md
setup.py

This fixes https://github.com/advisories/GHSA-jm77-qphf-c4w8, and hopefully #672.

Update cryptography to fix security issue

---

Pipfile.lock
setup.py

This brings us one step closer to the next ggshield release!

Update py-gitguardian to 1.9.0

---

ggshield/cmd/hmsl/check.py
ggshield/cmd/hmsl/decrypt.py
ggshield/cmd/hmsl/fingerprint.py
ggshield/cmd/hmsl/hmsl_common_options.py
ggshield/cmd/hmsl/query.py
ggshield/hmsl/collection.py
ggshield/hmsl/output.py

Reorganize files to match the current organization for other commands and make it easier to read.
This PR only moves code and change imports.

HMSL: reorg of some code

---

ggshield/cmd/iac/scan/all.py
ggshield/cmd/iac/scan/ci.py
ggshield/cmd/iac/scan/diff.py
ggshield/cmd/iac/scan/precommit.py
ggshield/cmd/iac/scan/prepush.py
ggshield/cmd/iac/scan/prereceive.py
ggshield/cmd/sca/scan/all.py
ggshield/cmd/sca/scan/ci.py
ggshield/cmd/sca/scan/diff.py
ggshield/cmd/sca/scan/precommit.py
ggshield/cmd/sca/scan/prepush.py
ggshield/cmd/sca/scan/prereceive.py
ggshield/cmd/sca/scan/sca_scan_utils.py
ggshield/cmd/secret/scan/ci.py
ggshield/cmd/secret/scan/docker.py
ggshield/cmd/secret/scan/dockerarchive.py
ggshield/cmd/secret/scan/docset.py
ggshield/cmd/secret/scan/path.py
ggshield/cmd/secret/scan/precommit.py
ggshield/cmd/secret/scan/prepush.py
ggshield/cmd/secret/scan/range.py
ggshield/cmd/utils/common_decorators.py

Remove try/except blocks in commands from Secrets / IaC / SCA in favour of a decorator

Create decorator for exception handling for secrets/iac/sca commands

---

ggshield/__main__.py
ggshield/cmd/config/config_migrate.py
ggshield/cmd/iac/scan/diff.py
ggshield/cmd/iac/scan/iac_scan_utils.py
ggshield/cmd/secret/scan/repo.py
ggshield/core/check_updates.py
ggshield/core/config/auth_config.py
ggshield/core/config/config.py
ggshield/core/config/user_config.py
ggshield/core/config/utils.py
ggshield/core/dirs.py
ggshield/core/env_utils.py
ggshield/core/scan/file.py
ggshield/utils/files.py
ggshield/utils/git_shell.py
ggshield/utils/os.py
ggshield/verticals/hmsl/utils.py
ggshield/verticals/iac/output/iac_text_output_handler.py
ggshield/verticals/sca/file_selection.py
ggshield/verticals/secret/docker.py
ggshield/verticals/secret/repo.py
tests/functional/secret/test_scan_docker.py
tests/unit/cmd/auth/test_login.py
tests/unit/cmd/auth/test_logout.py
tests/unit/conftest.py
tests/unit/core/config/test_auth_config.py
tests/unit/core/scan/test_file.py
tests/unit/core/test_env_utils.py
tests/unit/utils/test_files.py

This PR brings another batch of porting from os.path to Pathlib.
Now that the verticals are using Pathlib, this PR focuses on core and utils.

More pathlib porting

---

tests/conftest.py

Our unknown test secret is now a known test secret :(. Switch to another secret.

Unbreak functional tests

---

ggshield/verticals/secret/secret_scanner.py

- `GG_MAX_DOCS`: override the maximum number of documents per chunk
- `GG_MAX_DOC_SIZE`: override the maximum size of each document
This provides a workaround if a user hits payload size limits, until a proper fix is ready.
`skip-changelog` because we do not want to provide any guarantee over `GG_*` environment variables.

Make scan chunks configurable via environment variables

---

scripts/build-packages/build-packages

We need them for the brew tap.

chore: make build-package build sdist again

---

.pre-commit-config.yaml
Pipfile.lock

Note about the lock: we get rid of the darwin related dep introduced by mistake before the release.

Post-release: update lock and update to latest ggshield

---

changelog.d/20231005_152137_antonin.lacombe_Adapt_message_in_case_we_find_tons_of_matches.md
ggshield/verticals/hmsl/output.py

Add a new message when a secret has more than 100 locations

chore(hmsl): Adapt message in case we find tons of matches

---

ggshield/cmd/hmsl/hmsl_common_options.py

This will be autosynced in the doc. Replicating the changes manually before the next release.

fix(hmsl): # Fix option description for full-hashes

---

tests/conftest.py
tests/functional/conftest.py

Some minor test fixes. This was prompted by `pytest --help` taking a long time now that I have setup ggshield as a global git hook.

Test cleanups

---

.github/workflows/ci.yml

Tested in my sandbox repository: https://github.com/agateau-gg/ci-sandbox/pull/4

Fix fixup commit message checker failing on PR from forks

---

scripts/README.md
scripts/create-ghe-environment

Add a script to generate a chroot suitable for use as a GitHub Enterprise pre-receive hook environment.

Add a script to generate a GitHub Enterprise pre-receive hook env

---

changelog.d/20240110_161612_paul.beslin.ext_fix_ci_new_branch.md
ggshield/core/git_hooks/ci/previous_commit.py
tests/conftest.py
tests/functional/iac/test_iac_scan_all.py
tests/functional/iac/test_iac_scan_ci.py
tests/functional/iac/test_iac_scan_diff.py
tests/functional/iac/test_iac_scan_precommit.py
tests/functional/iac/test_iac_scan_prepush.py
tests/functional/iac/test_iac_scan_prereceive.py
tests/unit/cmd/iac/test_iac_scan_utils.py
tests/unit/cmd/iac/test_scan_all.py
tests/unit/cmd/iac/test_scan_common.py
tests/unit/cmd/iac/test_scan_diff.py
tests/unit/cmd/iac/test_scan_prepush.py
tests/unit/core/git_hooks/ci/test_previous_commit.py
tests/unit/verticals/iac/output/test_iac_json_output.py
tests/unit/verticals/iac/output/test_iac_text_output.py

First commit refactors some IAC tests to use fixtures instead of global variables, and could be reviewed separately.
Other commits fix 2 bugs for IAC and SCA:
- CI scans failed when pushing a new branch, due to CI predefined variables being incorrect -> now the parent commit is calculated using git commands
- They failed on the first push to a repository for the same reason (and because there were no commits to compare HEAD to) -> a scan all is triggered instead
Previously, for these two cases, Gitlab CI failed, while Github CI fallback was to scan the last commit only.
CI is still misbehaving on force pushes, this will be fixed in another PR.

Fix IAC scan CI for new branches on Github

---

Pipfile.lock
ggshield/core/dirs.py
setup.cfg

chore(deps): use replace appdirs by platformdirs

---

.pre-commit-config.yaml

chore(pre-commit): update to latest ggshield

---

ggshield/verticals/auth/oauth.py

This PR simplifies OAuthClient code.
RequestHandler is no longer an inner class. This was required for it to get access to the RequestHandlerWrapper instance creating it, but this made the code hard to read.
This commit changes this by:
1. Removing RequestHandlerWrapper: its `complete` and `error_message` attributes have been moved to OAuthClient as `_request_finished` and `_request_error_message`.
2. Making `RequestHandler.__init__()` take an OAuthClient instance in addition to the arguments it already accepts.
3. Making RequestHandler update the new OAuthClient attributes added in 1)
4. Passing to HTTPServer a partial of RequestHandler class, initialized with the OAuthClient instance.

Refactor oauth code: simplify request handling

---

changelog.d/20240205_111044_paul.beslin.ext_hide_sca_ignored_incidents_all.md
ggshield/verticals/sca/collection/collection.py
ggshield/verticals/sca/collection/filter_ignored.py
ggshield/verticals/sca/output/handler.py
ggshield/verticals/sca/output/json_handler.py
ggshield/verticals/sca/output/text_handler.py
tests/functional/sca/test_sca_scan_output.py
tests/unit/verticals/sca/collection/test_filter_ignored.py

All vulnerabilities retrieved from the API are now filtered based on their statuses. Ignored vulnerabilities are no longer shown in the text/JSON outputs, for SCA scan all/diff commands.
The implementation is mostly similar to the one for IAC in #800.

Hide vulnerabilities ignored in app

---

Pipfile.lock
changelog.d/20240201_145431_cedric.bosselut_add_honeytoken_create_with_context_command.md
ggshield/cmd/honeytoken/__init__.py
ggshield/cmd/honeytoken/create.py
ggshield/cmd/honeytoken/create_with_context.py
ggshield/cmd/honeytoken/utils.py
setup.cfg
tests/unit/cassettes/test_honeytoken_create_with_context_bad_language.yaml
tests/unit/cassettes/test_honeytoken_create_with_context_ok_no_name.yaml
tests/unit/cmd/honeytoken/test_honeytoken.py
tests/unit/cmd/honeytoken/test_honeytoken_with_context.py

This PR adds the command `create-with-context` in honeytoken group to create a honeytoken and insert it in a file.

feat(honeytokens): add honeytoken create-with_context command

---

Pipfile.lock

Update Pipfile.lock to fix security issue in idna < 3.7

---

changelog.d/20240424_144034_sylvain.baud_remove_sca_beta_badge.md
ggshield/cmd/sca/scan/all.py
ggshield/cmd/sca/scan/ci.py
ggshield/cmd/sca/scan/diff.py
ggshield/cmd/sca/scan/precommit.py
ggshield/cmd/sca/scan/prepush.py
ggshield/cmd/sca/scan/prereceive.py

chore(sca): remove sca beta warning

---

Pipfile.lock

Post release update Pipfile.lock

chore(deps): post release 1.27.0 update lock file

---

Pipfile.lock

Pipfile update following 1.28.0 release

chore(deps): post release 1.28.0 update lock file

---

ggshield/verticals/secret/output/secret_json_output_handler.py
ggshield/verticals/secret/repo.py
ggshield/verticals/secret/secret_scan_collection.py

fix(result): change naming to suit scannable

---

.pre-commit-config.yaml
CHANGELOG.md
ggshield/cmd/honeytoken/create.py
ggshield/cmd/honeytoken/create_with_context.py

- Update ggshield version in pre-commit to 1.29.0.
- Add a missing changelog entry.
- Update honeytoken doc.

Post release updates

---

Pipfile
Pipfile.lock
setup.cfg

Update to pygitguardian 1.16.0 now that it has been released.

chore(deps): update to pygitguardian 1.16.0

---

tests/functional/conftest.py

Fix broken functional tests blocking the release

Fix functional tests

---

README.md

Now that we have a standalone Windows binary, let's talk about it!
Add a section about the Windows binary to the README.

Document ggshield standalone Windows binary

---

.pre-commit-config.yaml

Update ggshield pre-commit version.

Update to latest ggshield

---

.github/workflows/ci.yml

Cleanup
Remove unused env var in the scan sca and scan iac jobs
- checks in CI: https://github.com/GitGuardian/ggshield/actions/runs/9581923357/job/26419785059#step:3:294 and https://github.com/GitGuardian/ggshield/actions/runs/9581923357/job/26419789565#step:3:298

chore(ci): remove unused env variables for IaC / SCA scans

---

.pre-commit-config.yaml

Update pre-commit to ggshield 1.31.0

chore(pre-commit): update to ggshield 1.31.0

---

ggshield/core/client.py

Add possibility to change user agent in requests.

feat(monitoring): Use env variable as user agent

---

.pre-commit-config.yaml

Update to ggshield 1.32.0

---

.pre-commit-config.yaml

Update to ggshield 1.33.0

---

.pre-commit-config.yaml

Update to ggshield 1.34.0

---

pdm.lock
pyproject.toml

IPython is needed when running the debugger

add IPython in dev dependencies

---

scripts/push-to-chocolatey/VERIFICATION.txt
scripts/push-to-chocolatey/ggshield.nuspec
scripts/push-to-chocolatey/push-to-chocolatey

The chocolatey package failed verification in the package repository
A VERIFICATION.txt has been added with instructions on how to verify the binaries's authenticity.
a packageSourceUrl field has been added.

chore: fix chocolatey package to follow guidelines

---

README.md

Update Readme for Chocolatey release
Update Readme

Add Chocolatey installation instructions for Windows

---

changelog.d/20250717_280780_guillaune.valadon.md
ggshield/verticals/secret/docker.py

This PR adds filepath that likely contain application code and should be scanned.

feat: remove filepaths from docker banlist

---

pdm.lock
pyproject.toml

Bump py-gitguardian, update lock file.

Bump py-gitguardian version
