GitGuardian/ggshield

ggshield/git_shell.py, ggshield/install.py, setup.cfg, tests/test_git_shell.py
- removes `capture_output` which was only added in python 3.7.
- removes `git_shell` from coverage exclusions
=> fix(shell): fix compatibility issue with python 3.6

.pre-commit-config.yaml, .pre-commit-hooks.yaml, README.md
- Adds `docker_image` pre-commit hook as `docker-ggshield`
- Change default recommended pre-commit hook to `ggshield`, `commit-ggshield` will be deprecated in the future
=> feat(pre-commit): add docker-image pre-commit

Dockerfile, Pipfile.lock, ggshield/cmd.py, ggshield/config.py, setup.py, tests/test_config.py
- Remove deprecated commands
- Add `GITGUARDIAN_CRASH_LOG` to print exceptions that bubble to the top
- Squash unneeded layers in docker file
=> Click cleanup

ggshield/filter.py, ggshield/git_shell.py
Increase timeout of `git ls-files` for ignored file listing to handle repositories with a lot of ignored file in the working directory.
This is a temporary fix and refactoring the ignore file to avoid having to run this git command will need to be done.
=> Increase timeout to list git ignored files to 10min

.pre-commit-config.yaml, Pipfile.lock, ggshield/config.py, ggshield/dev_scan.py, ggshield/scannable.py
- Reduces scan time in approximately half for directory scanning
ThreadPool scan for chunks
- Reduces scan time in 1/3 for commit range scanning
ProcessPool scan for commits
- Could be improved to not create the ThreadPoolExecutor if the `scannable_list` is inferior to `MULTI_DOCUMENT_LIMIT`. (To be discussed in review)
=> Add thread pool executor for chunk scanning

.pre-commit-config.yaml, ggshield/filter.py, ggshield/git_shell.py, ggshield/path.py, setup.cfg
- Remove need for building git filter set for commits (much faster pre-commit and commit-range scan).
- Use `.gitignore` of target if it's not the working directory.
- Use `git ls-files` for path if target is a repo (faster)
Average 2x improvement
Example on mid-sized project:
old - 0:04.26 elapsed
new - 0:02.54 elapsed
=> Improve filter performance

.gitignore, README.md, ggshield/ci.py, ggshield/cmd.py, ggshield/config.py, ggshield/dev_scan.py, ggshield/ignore.py, ggshield/scan/scannable.py, tests/conftest.py, tests/output/test_json_output.py, tests/scan/test_scannable.py, tests/test_config.py, tests/test_ignore.py
__Narrative__
As a ggshield user,
I want to add my last found secrets on ggshield to the .gitguardian.yaml (or .gitguardian.yml) when I run ggshield ignore --last-found
so that I don't have to copy-paste them into .gitguardian.yaml and they are ignored on my next run of ggshield
__Technical description:__
- add Cache object that load and save into a local json .cache_ggshield file
- add ignore cmd with its option --last-found
- add corresponding doc in README.md
- adding comment to the config yaml turned out to be too complicated compared to the value of the feature
=> feat(ignore_cmd): add ignore --last-found command

ggshield/install.py
Hi,
Thanks for creating this cool tool. I wanted to propose a fix for the global hook installation.
If certain repos have local pre commit hooks installed (manually or through some other tools), the global pre-commit hook completely ignores them, leading to bad user experience since these pre-commit hooks are installed for a reason.
With this proposed change, local hooks are executed if they exist:
```
perei@DESKTOP-9PBJQMM MINGW64 ~/Documents/gg-shield (local-hook-support-for-global)
$ docker build -t ggshield .
[+] Building 16.0s (19/19) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                  0.0s
=> => transferring dockerfile: 32B …
```
=> fix(ggshield): allow execution of local hooks when the global hook runs

ggshield/git_shell.py
This is in reference to https://github.com/GitGuardian/gg-shield/issues/52
Don't throw exception when CWD is /
Do throw an exception when git is not found
Update exception message to indicate situation (not found vs rejected)
Enhance PATH/CWD comparisons to avoid symlinks from causing issues
=> Proposed fix for Issue 52

README.md, ggshield/ci.py, ggshield/utils.py
This heavily relies on the BUILD_BUILDID environment variable to detect the use of Azure Pipelines. Also use BUILD_SOURCEVERSION to know the head commit. This will work nicely to detect ranges in PRs, not so much for pushes in main branches (there only the latest commit will be scanned).
=> Azure Pipelines Integration

ggshield/scan/docker.py, tests/scan/test_scan_docker.py
- Make dockerfile/buildargs specific in the detection
- Easiest way without changing output logic
Example:
=> Make dockerfile/buildargs specific

ggshield/config.py, ggshield/hook_cmd.py, tests/test_config.py, tests/test_hook_cmd.py
Scan last x commits in pre-push if there are too many and make it configurable
https://github.com/GitGuardian/ggshield/issues/78
=> Scan last x commits in pre-push if there are too many

ggshield/ci.py, ggshield/config.py
This PR makes sure the `scan ci` command does not create a cache file. This fixes #68 
- Do not create the cache file as soon as the Cache instance is created
- In `ci_cmd()`, call `scan_commit_range()` with the cache set to a "dummy" cache class which does not save to disk
=> No cache for scan ci

README.md, ggshield/cmd.py
`export GITGUARDIAN_TIMEOUT=2`
`echo 86c47dda8f279cea8cba8384040e14672f9aa7ab\nHEAD\nmain\n | ggshield scan pre-receive`
=> Never run standalone mode. fixes exit 1 on interrupt

ggshield/utils.py, tests/cassettes/no_newline_before_secret.yaml, tests/conftest.py, tests/test_utils.py
Handles bug encountered due to the presence of `\ No newline at end of file` in patches, that were not handled
=> fix(patch_parsing): lines starting with backslash

README.md, ggshield/ci.py, ggshield/cmd.py, ggshield/dev_scan.py, ggshield/filter.py, ggshield/hook_cmd.py, ggshield/path.py, ggshield/pre_receive_cmd.py, ggshield/scan/scannable.py, tests/scan/test_scannable.py, tests/test_prepush_cmd.py
ggshield supports to exclude some files from scan using exclude
patterns.  Those patterns can be set using cli arguments, configuration
file and there are default excluded patterns as well.
We used to list all the files matching those patterns using glob in
order to filter out files to scan. We recently added some default
patterns to ignore and it leds us to realize the performance issue with
this approach: FS listing is very slow and it does not scale.
We now use regex to check if a file path is included in the exclude
patterns.
=> fix(filter): stop to list FS to exclude files to scan

.github/workflows/tag.yml
In this MR, we want to lay the ground for migrating to a central tap for all GitGuardian's tool.  
This MR simply modifies the `tag` workflow to push ggshield formula to two taps. 
**Warning :** We should wait for `GitGuardian/homebrew-tap` to be public before merging.
=> Update jobs to push ggshield formula on both GitGuardian's taps

tests/test_ignore.py, tests/test_scan.py
Tests are failing on Mac OS because the tmp directory is not /tmp. Also /tmp is a symlink for /private/tmp
This PR proposes:
- to use the tempfile package to get the current tmp directory
- to test against /private/tmp if Darwin platform is detected
=> fix(tests): support macos tmp dir to make tests pass

.gitguardian.yaml, ggshield/output/text/text_output.py
This PR fixes https://github.com/GitGuardian/ggshield/issues/116
A scan can be composed of a list of subscans. In this case, found secrets are not listed in the main scan.results list, but in sub scans results. This PR proposes to test if any sub scan has a result in order to trigger the "no secret found" message.
=> fix(ci) no secret found no more displayed if secrets found

.github/workflows/main.yml, .github/workflows/tag.yml
We tagged every Docker images we built as latest. It makes every merges
we did a release for our customers using latest Docker images.
This commit now makes the CI to tag images built on a merge into the
main branch as unstable instead of latest. We continue to tag Docker
images built for a release with the corresponding git tag and we add the
latest tag.
=> fix(ci): stop to tag every Docker images as latest

Pipfile, Pipfile.lock, ggshield/docker.py, ggshield/scan/docker.py, setup.py, tests/test_docker.py
This PR fixes several issues encountered while trying to use `ggshield scan docker` on Windows.
Each commit fixes one issue, so the PR is best reviewed commit by commit:
- yaspin spinner causes unicode error on Windows (#160) → use click.echo() instead
- `docker save` takes too long → add a `--docker-timeout` option (#161)
- `docker save` fails because the destination filename contains a `:` character (not allowed on NTFS) (#161) → use a fixed destination filename
=> Make `scan docker` work on Windows

ggshield/config.py, tests/test_config.py
This PR fixes an issue when ggshield runs on a read-only filesystem, by catching more general `OSError` during cache write.
=> Fix uncaught Exception when cache is created on a read-only FS

README.md
Add documentation to install `ggshield` using Homebrew on MacOs
=> docs: add brew command for easy install on :apple: macos

ggshield/output/__init__.py, ggshield/output/gitlab_webui/__init__.py, ggshield/output/gitlab_webui/gitlab_webui_output_handler.py, ggshield/output/text/message.py, ggshield/pre_receive_cmd.py, ggshield/scan/scannable.py, ggshield/text_utils.py, tests/conftest.py, tests/output/test_gitlab_webui_output.py, tests/test_prereceive_cmd.py
This PR detects if the pre-receive hook is running from GitLab Web UI. If it is the case, it uses a shorter error message, prefixed with what GitLab expects so that the message shows up in the UI instead of disabling the hook completely.
It also deprecates the --web option, which is no longer useful.
https://github.com/GitGuardian/ggshield/issues/151
Web UI:
Web IDE:
Not the pinnacle of design and user-friendliness, but GitLab UI does not allow any better.
=> Fix GitLab Web UI showing empty error messages

.gitlab-ci.yml
This file was previously used to Gitlab CI internally. Nowadays, GitHub Actions are used instead of gitguardian-oss.
=> chore(gitlab-ci): remove unused definition

README.md, ggshield/cmd.py, ggshield/pre_receive_cmd.py, tests/test_crash_log.py, tests/test_prereceive_cmd.py
This reverts commit 69204a9ba9a919250b464748ca06774ccceec8c0 and provides a different way to ensure we exit with 0 in case a `pre-receive` hits the timeout.
Fixes #150.
Before:
```
$ ggshield foo
Traceback (most recent call last):
File "/home/agateau/.local/bin/ggshield", line 8, in <module>
sys.exit(cli_wrapper())
File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/ggshield/cmd.py", line 229, in cli_wrapper
return_code: int = cli.main(standalone_mode=False)
File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/home/agateau/.local/pipx/venvs/ggshield/lib/python3.8/site-packages/click/core.py", line 1653, in invoke
cmd_name, cmd, args = self.resolve_command(ctx, args)
File …
```
=> Only show backtrace if GITGUARDIAN_CRASH_LOG is set

ggshield/output/text/message.py, tests/output/snapshots/snap_test_text_output.py, tests/output/test_text_output.py
Tests were not passing because Windows output differs from Linux/macOS output.
Now the output is made OS-independent by:
- removing color
- replacing the file info decoration
CC #168
=> fix(tests): Make test_text_output pass on Windows

ggshield/docker.py, tests/test_docker.py
If we run `ggshield scan docker <image>` and `<image>` is not available locally, `ggshield` downloads it first.
I broke this feature when I made other Docker fixes: ggshield currently raises an exception at the end of the download.
Fix that and add tests to cover this case to ensure that cannot go undetected anymore.
Fixes #181.
cc @Sayrus
=> Fix crash when scanning a non-local image

.prettierignore, CONTRIBUTING.md, Makefile, Pipfile.lock, ggshield/cmd.py, ggshield/quota.py, scripts/README.md, scripts/update-pipfile-lock/Dockerfile, scripts/update-pipfile-lock/update-pipfile-lock
This PR adds a script to update the Pipfile.lock file.
The script uses Docker to run `pipenv` on the oldest supported version of Python.
This PR removes the `.venv` directory because it gets in the way when ggshield source code is mounted inside the Docker container used to run `pipenv lock`.
=> Add script to update Pipfile.lock

.pre-commit-config.yaml, Pipfile, Pipfile.lock, ggshield/dev_scan.py, ggshield/docker.py, ggshield/hook_cmd.py, ggshield/pypi.py, ggshield/scan/scannable.py, tests/output/test_json_output.py, tests/scan/test_scannable.py, tests/test_ignore.py, tests/test_scan.py, tests/test_utils.py
Changes:
- Upgrade black to avoir click deprecation issues
- Compute headers based on click context
I've removed the param `mode_header` and now generate the headers using `click.get_current_context(silent=True)`. I've also changed the header to something more explicit, from `mode` to `GGShield-HeaderName`. The current headers are:
- `GGShield-Version` ggshield version
- `GGShield-Command-Path` full path of the scan, ie: `ggshield scan path`
- ~~`GGShield-Command-Name` name of the command, ie: `path-cmd`~~
=> feat(headers): Compute headers based on click context

ggshield/config.py, ggshield/utils.py, tests/test_config.py, tests/test_utils.py
The config refactoring break an Integration test in docker due to the GITGUARDIAN_API_URL format that highlighted a parsing issue. The trailing / being only cleaned if the URL had no params nor queries.
This MR fixes it and adds unit tests for the `dashboard_to_api_url` and `api_to_dashboard_url` to test these edge cases.
Also cleans a potential /v1 and warns about it.
=> fix(config): fix api/dashboard URLs parsing not handling params and queries

ggshield/path.py, ggshield/scan/docker.py, ggshield/scan/scannable.py, tests/test_path.py
This PR fixes #155.
I moved the decoding code used when reading files inside Docker images to a `File.from_bytes()` static method and then replaced the code used to decode files from the file system with `Files.from_bytes()`.
While working on the `File` class I realized it contains a `filesize` field, which is never used, so I removed it.
=> Fix scan stopping when encountering a file containing a 0 byte

README.md
Azure Pipelines expects the Docker container to start as root. They then run `useradd -m -u 1001 vsts_azpcontainer` in the container to create a matching non-root user.
This fails with ggshield Docker container because it starts as its own non-privileged user, which is not allowed to run `useradd`.
Tell Azure Pipelines to start the container as root (with `-u 0`) to avoid that issue.
=> Fix Azure Pipelines example script

.github/workflows/tag.yml, README.md, scripts/README.md, scripts/build-packages/build-packages, scripts/build-packages/ggshield-wrapper, scripts/build-packages/nfpm.yaml.tmpl, scripts/push-to-cloudsmith
This PR adds a script to publish packages on Cloudsmith and make the tag workflow call this script.
It also makes our package a bit more robust in situations where the default `python3` interpreter is too old.
Installing the package in a Fedora container.
Start the container:
```
$ docker run -it --rm -e GITGUARDIAN_API_KEY -v $PWD:/src fedora
```
Run Cloudsmith setup script:
```
[root@7fc7a79dbf5b /]# curl -1sLf 'https://dl.cloudsmith.io/public/gitguardian/ggshield/setup.rpm.sh' | bash
Executing the  setup script for the 'gitguardian/ggshield' repository ...
OK: Checking for required executable 'curl' ...
OK: Checking for required executable 'rpm' ...
OK: Detecting your OS distribution and release using system methods ...
^^^^: ... Detected/provided for your OS/distribution, version and …
```
=> Publish deb and rpm packages on Cloudsmith

ggshield/client.py, ggshield/config.py, tests/test_config.py, tests/test_utils.py
This ensures a first-time user trying to scan without having setup authentication first won't get that error message:
> Unrecognized instance 'https://dashboard.gitguardian.com'
Fixes #201.
=> Fix error message in blank state (#201)

ggshield/scan/docker.py, tests/scan/test_scan_docker.py
Some docker tests are currently skipped on Windows (see #168). They are skipped because path separator issues (`\` vs `/`) make them fail.
This PR fixes this.
- Decide that Docker output paths are always Unix. This is not always true (there are Windows-based Docker images), but extracting this information requires too much work.
- Simplify the output: do not report the archive name, it is the path to a temporary archive, which is gone by the time the command ends.
The second point means that before the output looked like this:
```
️  ⚔️  ️  1 incident has been found in file /tmp/tmpai92kygzggshield/archive.tar/fdcab29fec3e99c1bb251f62ec1064ba2e32682bcf70da7d0d16d7cc2e0f6dd7/layer.tar/etc/config.py
>>> Incident 1(Secrets detection): Generic High Entropy Secret (Validity: Cannot Check) …
```
=> Rework docker scan output, unskip tests on Windows

Pipfile, Pipfile.lock, ggshield/auth.py, ggshield/oauth.py, tests/test_auth_cli.py
Implement ggshield login auth "web" method which implement the OAuth2 flow.
The core logic is implemented in `OAuthClient.oauth_process()`. In short it does
* redirect to GitGuarian login page (with ggshield options)
* open a local server to start listening
* retrieve the code from the call to localhost
* validate the token and retrieve its data
* save the token to the config
* open a tab to the "authenticated" page
=> Implement ggshield web oauth flow

ggshield/cmd/auth/login.py, ggshield/core/oauth.py, tests/cmd/auth/test_login.py
- refactor tests into separate test functions
- handle optional parameters for the auth login web method
- token name
- lifetime of the token (in days)
- make sure that these value are included in the state passed to the authentication server and that they are returned unchanged in the callback url
- make the server silent so it doesn't log incoming http requests
- remove the feature flag for more clarity (as requested by @agateau-gg )
=> Add auth login optional params for web method

ggshield/cmd/auth/__init__.py, ggshield/cmd/ignore.py, ggshield/cmd/install.py, ggshield/cmd/main.py, ggshield/cmd/quota.py, ggshield/cmd/scan/__init__.py, ggshield/cmd/status.py, tests/cmd/scan/test_docker.py, tests/scan/test_scan_docker.py
This PR is a follow-up to #207.
What has been done:
- Improve naming consistency inside the `cmd` package: all command functions end with `_cmd()`, all group functions end with `_group()`
- Improve help messages
- Move some cli-independent docker tests from tests.cmd.scan.test_docker to tests.scan.test_scan_docker
=> Minor changes after source-tree reorganization

ggshield/cmd/scan/ci.py, ggshield/cmd/scan/prepush.py, ggshield/cmd/scan/prereceive.py, ggshield/cmd/scan/range.py, ggshield/core/extra_headers.py, ggshield/core/utils.py, ggshield/scan/repo.py, ggshield/scan/scannable.py, tests/cmd/scan/test_prepush.py
`mode_header` was still present in the code even if it was unused.
It was used to pass details about the type of CI in the headers, I've replaced it by using `obj` in Click's context to pass info to the function building the headers.
=> feat(headers): Completely replace mode_header with Click context

ggshield/cmd/auth/utils.py, ggshield/core/client.py, ggshield/core/oauth.py, ggshield/core/utils.py, tests/cmd/auth/test_login.py
The request to check the metadata was including the token in the headers. However this endpoint is public and doesn't expect any.
* manually call "metadata" endpoint during the auth process to avoid passing the token
* implement a custom `urljoin` helper to allow joining non-slash-trailing url parts (otherwise it would squeeze the '/v1')
=> Fix GitGuardian metadata check during web authentication process

ggshield/cmd/auth/login.py, ggshield/core/config.py, ggshield/core/oauth.py, tests/cmd/auth/test_login.py, tests/core/test_config.py
When using the web auth login method, if a token is found in the config for the current instance, skip the process with an explicit message.
This also include refactoring how the instance config are stored. instead of using a dict we know use a list.
This is not a real performance issue as the end users are not supposed to have many instances at once.
All the tests have been adapted to suit this new configuration file.
=> Skip auth if existing token

ggshield/core/oauth.py, tests/cmd/auth/test_login.py
For ggshield auth login web method, if an error occur on the server side, we want to be able to stop the client from listening for callback.
What this PR do:
* if the callback contains an "error" parameter, it will interrupt the flow directly and output the error message given by the server
Note: this can't really be tested as the local server logic can only be mocked.
=> Allow to interrupt auth flow from auth server

ggshield/output/text/text_output_handler.py, tests/cmd/scan/test_path.py
Print "No secrets have been found" when no secrets are found even in non verbose mode.
- Added a test to check the output without the verbose tag
- Closes #117
=> feat: print "No secrets have been found" when no secrets are found 

ggshield/cmd/auth/__init__.py, ggshield/cmd/auth/logout.py, ggshield/core/config.py, tests/cmd/auth/test_login.py, tests/cmd/auth/test_logout.py, tests/cmd/auth/utils.py
Add the `logout` command to ggshield client. It will delete the local configuration and attempt to revoke the token at the same time.
- implement the command `ggshield auth logout`
- it should remove the local configuration
- if `--instance` is not specified, it will resort to the default one
- it should revoke the old token by default unless `--no-revoke` option is passed
- if the `--all` option is passed, it will iterate over all found configs (`--instance` is ignored in this case)
=> Add auth logout command

ggshield/core/oauth.py, tests/cmd/auth/test_login.py
When an error is received during the oauth process, we convert this error code into a human-readable message.
This follows https://github.com/GitGuardian/ggshield/pull/219
example of error message
> Maximum number of personal access tokens reached. Could not provision a new personal access token.
> Go to your workspace to manage your tokens: https://dashboard.gitguardian.com/api/personal-access-tokens
=> Convert oauth server error code to message

ggshield/cmd/auth/login.py, ggshield/core/config.py, ggshield/core/oauth.py, tests/cmd/auth/test_login.py
This adds an optional `--sso-url` parameter to the `ggshield auth login` command. to use with `--method=web`.
- it handles the collision with a `--instance` declaring another host.
- it handles deducing the instance from the sso url if the instance is not specified in the command.
=> feat(auth): implement the --sso-url parameter to specify a SSO page to use for authentication

ggshield/cmd/scan/archive.py, ggshield/cmd/scan/ci.py, ggshield/cmd/scan/prepush.py, ggshield/cmd/scan/prereceive.py, ggshield/cmd/scan/pypi.py, ggshield/cmd/scan/range.py, ggshield/core/file_utils.py, ggshield/scan/docker.py, ggshield/scan/repo.py, tests/cmd/scan/test_ci.py, tests/cmd/scan/test_docker.py, tests/cmd/scan/test_path.py, tests/cmd/scan/test_pypi.py
Send verbose messages to stderr to fix `--json` and `--verbose` behavior.
Closes #157
=> fix: send verbose messages to stderr

ggshield/cmd/scan/archive.py, ggshield/cmd/scan/path.py, ggshield/cmd/scan/precommit.py, ggshield/cmd/scan/pypi.py, ggshield/core/utils.py, ggshield/scan/docker.py, ggshield/scan/repo.py, ggshield/scan/scannable.py, tests/cmd/test_ignore.py, tests/core/test_utils.py, tests/output/test_json_output.py, tests/scan/test_scan.py, tests/scan/test_scannable.py
In this PR, we re-introduce the "mode" header for API calls.  
This header can take several values depending on the type of scan launched.
**Note :** We also took advantage of this PR to remove a useless verbose parameter.
=> Plalanne/ /bring back mode header

ggshield/core/text_utils.py, tests/core/test_text_utils.py
Make our code more future proof: if a validity id is not known, return it instead of raising an exception.
=> Do not crash if we receive an unsupported validity check

ggshield/cmd/auth/utils.py, ggshield/cmd/config/__init__.py, ggshield/cmd/config/config_list.py, ggshield/core/oauth.py, ggshield/core/utils.py, tests/cmd/auth/test_login.py
* handle ConnectionError (unresolved host) when checking if ggshield flow is enabled. e.g. `gghsield auth login --method web --instance https://fake-host.com"
* recognize gitguardian.tech domain as gitguardian own domain (to allow logging in with gghsield on https://dashboard.staging.gitguardian.tech)
* fix `auth config` command documentation
* remove unused code
=> Various fixes related to ggshield auth and config commands

ggshield/cmd/auth/login.py
If `$GITGUARDIAN_API_KEY` is set to a valid token, then `ggshield auth login --method token` succeeds even if the entered token is invalid.
`ggshield auth login --method token` should ignore the `$GITGUARDIAN_API_KEY` environment variable.
1. Set `$GITGUARDIAN_API_KEY` to a valid token
1. Run `ggshield auth login --method token`
1. Enter an invalid token
1. A `.config/ggshield/auth_config.yaml` file with the invalid token is created
After the token is retrieved from the input, the API call to test it will use the token instead of the config's default token (which is the env variable by default if set).
=> Ignore env var when login token method

.pre-commit-config.yaml
Remove `types-click` from pre-commit. 
I suspect the package is no longer necessary (and cause bugs):
There is no `click` folder in https://github.com/python/typeshed/tree/master/stubs  (so the link in https://pypi.org/project/types-click/#history is dead).
I have tried adding `types-click` as a dev-dependency, but it somehow requires `ipython` ??? (see https://github.com/GitGuardian/ggshield/runs/6452203176?check_suite_focus=true)
=> fix(dev_dependencies): remove types-click from pre-comits

ggshield/cmd/main.py, tests/cmd/scan/test_path.py
`ggshield secret scan (...)` commands would exit with a non-zero code when a secret is found, but not the now deprecated `ggshield scan (...)` commands.
=> fix: fix deprecated scan commands exit code

ggshield/cmd/auth/login.py, ggshield/cmd/auth/logout.py, ggshield/cmd/config/config_get.py, ggshield/cmd/config/config_list.py, ggshield/cmd/config/config_set.py, ggshield/cmd/config/config_unset.py, ggshield/core/oauth.py, tests/cmd/auth/test_login.py, tests/cmd/auth/test_logout.py
* fix documentations appearing with  `--help` commands
* adjust message (and error messages) to be more explicit and readable to the users
* for auth login command, make `--method web` default (thus optional to specify)
=> Fix command documentation and messages

ggshield/cmd/auth/login.py, ggshield/cmd/auth/logout.py, ggshield/cmd/auth/utils.py, ggshield/cmd/config/config_list.py, ggshield/core/oauth.py, tests/cmd/auth/test_login.py, tests/cmd/auth/test_logout.py
* Fix SSO wrongly not matching witn instance url (it happened if the url of the instance was not the default one)
* update logout error message if no network
=> Fix SSO wrongly not matching with instance url

ggshield/core/client.py, ggshield/iac/models/__init__.py, ggshield/iac/models/iac_scan_parameters.py, ggshield/iac/models/iac_scan_result.py, tests/cmd/test_status.py, tests/iac/test_models.py
In order to be able to call the API and handle the results, we:
- inherit the GGClient, adding a method to call the iacscan endpoint and create the IAC Client to call
- add classes for an IaC scan result and vulnerability with the 
- add a scan parameters class which is passed to the client when doing the request to ignore some policies/severities
- Added a test to check deserialization of the introduced classes
- Currently missing a test for the client, will be added when we define the API response and get cassettes
=> feat(iac): add new classes to handle response from the client endpoint

ggshield/core/config/user_config.py, tests/core/config/test_user_config.py
- Allow setting iac settings by adding iac parameters to the user config file as described in the config file format v2 doc
- Added unit tests for the loading of the config, global or local
=> feat(iac): handle config file for iac

ggshield/cmd/iac/scan.py, ggshield/core/client.py, ggshield/core/file_utils.py, ggshield/iac/filter.py, ggshield/iac/models/__init__.py, ggshield/iac/models/iac_file_result.py, ggshield/iac/models/iac_scan_result.py, ggshield/iac/models/iac_vulnerability.py, ggshield/output/json/iac_json_output_handler.py, ggshield/output/json/schemas.py, ggshield/output/text/iac_text_output_handler.py, ggshield/output/text/message.py, ggshield/output/text/text_output_handler.py, ggshield/output/text/utils.py, ggshield/scan/scannable.py, tests/cassettes/test_iac_scan_error_response.yaml, tests/cmd/iac/test_scan.py, tests/iac/test_filter.py, tests/iac/test_models.py, tests/output/test_message.py
- Update iac scan command to call the API through the client, using the context passed as an argument (from local and global config files) and overriding it with cli arguments.
- Call the API to scan the path passed as a directory. Only support one path
- Update the filter method to remove the root path from the files name
- Introduce text and JSON output handlers for the iac scan, with the format as defined in the tech specs
- Added unit tests and updated current unit tests
- Need to add some cassettes when the API is ready
- Update classes to match {"id": "", type": "", "iac_engine_version": "","entities_with_incidents": [{"filename": "filename","incidents": [...]}]}
=> feat(iac): handle API result with text and json output handlers

ggshield/core/client.py, ggshield/output/json/iac_json_output_handler.py, ggshield/output/json/schemas.py, ggshield/output/text/iac_text_output_handler.py, ggshield/output/text/message.py, tests/cassettes/test_iac_scan_empty_directory.yaml, tests/cassettes/test_iac_scan_multiple_files.yaml, tests/cassettes/test_iac_scan_multiple_vulnerabilities.yaml, tests/cassettes/test_iac_scan_no_vulnerabilities.yaml, tests/cassettes/test_iac_scan_single_vulnerability.yaml, tests/cmd/iac/test_scan.py, tests/conftest.py, tests/output/test_iac_json_output.py, tests/output/test_iac_text_output.py
- Update json schemas to fix entities_with_incidents appearing in the incidents
- Update client to pass the bytes tar as files
- Fix total entities in json output
- Add a message when there are no vulnerabilities found for the iac text output
- Add cassettes tests for a file with a single vulnerability, a file with multiple vulnerabilities, a file with no vulnerabilities, multiple files, for the text output and the json output
=> fix(iac): add iac scan tests + few fixes on the iac integration

ggshield/cmd/iac/scan.py, ggshield/output/text/iac_text_output_handler.py, ggshield/output/text/message.py
fix(iac): fix ignore-policy click option
fix(iac): add default behavior in case files are not found to display for the text output handler, to prevent complete failure
fix(iac): remove default CLI input to minimum-severity to avoid overriding config files
=> Small fixes for iac

ggshield/scan/docker.py, tests/cmd/scan/test_docker.py
In this PR, we do mainly two things :  
- Improve the existing way we "pre-validate" filepath before sending them to the API.  
- Modify a bit the banlist to fix #193.  
- We now allow some very specific cases of `/usr/` filepath when the file relates to nginx. 
- We allow `/gems` filepath, as it introduces a low volume of results with some interesting results.  
- I tried to identify some other rules that we could change : I think this is outside the scope of this issue, and it would require some more work.
=> Improve docker filesystem banlist

ggshield/output/text/text_output_handler.py
Fixes #265 
Only display `no_leak_message()` when `ŧop=True` in `_process_scan_impl`
=> fix: avoid output flood when scanning repo

.pre-commit-config.yaml, ggshield/core/config/user_config.py, ggshield/core/types.py, pyproject.toml, tests/core/config/test_user_config.py
- Add a base config class to handle pre_load and output message with unknown keys in config
- Add marshmallow_dataclass plugin for mypy
Please note that we don't raise a warning for additional fields in IgnoredMatches. I thought those are less important since they don't change the behaviour of the scan and can be a very long output in the case of a faulty copy/paste. This can be changed if you think it is better to raise the warning.
Close #278
=> fix(user_config): #278 Don't fail on unknown keys for user config

ggshield/core/cache.py, ggshield/core/config/utils.py, ggshield/core/text_utils.py, ggshield/core/utils.py, ggshield/scan/docker.py, tests/core/test_cache.py, tests/core/test_config.py
Print progress info on stderr so that we can pipe ggshield output to tools consuming json from stdin.
Before:
```
$ ggshield secret scan --json docker ubuntu:20.04 | jq
parse error: Invalid numeric literal at line 1, column 7
Scanning  [####################################]  100%          
Error: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
After:
```
$ ggshield secret scan --json docker ubuntu:20.04 | jq      
Saving docker image... OK
Scanning  [####################################]  100%          
{
"id": "ubuntu:20.04",
"type": "scan_docker_archive",
"total_incidents": 0,
"total_occurrences": 0
}
```
=> fix: fix docker output breaking json redirection

Pipfile, ggshield/scan/scannable.py, tests/core/test_file_utils.py
Since version 1.3.5, py-gitguardian takes care of cleaning input documents by replacing `0` bytes. no need to do it ourselves.
Also, don't replace replacement characters: they do not cause problems and are a better fit than a space.
Fixes #264
=> Fix ggshield secret scan repo crashes on repositories containing files with a 0 bytes in them

.gitguardian.yaml
After merging the IAC branch, the scan of the repository history reported a test secret. Ignore it.
=> Ignore test secret reported in our history

action.yml, ggshield/cmd/secret/scan/ci.py
This PR cleans a few things I noticed while fixing #294:
- Use `ggshield secret scan` in our local action.
- Improve wording of CI messages, in particular do not talk about a `--ci` option: it does not exist anymore.
=> Scan CI fixes

README.md, ggshield/cmd/main.py, ggshield/core/config/user_config.py, ggshield/scan/scannable.py
To help with customer support, this PR adds a `--debug` option to log the following info:
- path of loaded config files
- command line arguments
- filename and filemode (added, removed, modified) of scanned documents
- sha of scanned commits
- scan exit code
=> Add --debug option

ggshield/cmd/main.py, ggshield/cmd/secret/scan/prepush.py, ggshield/core/git_shell.py, ggshield/scan/scannable_errors.py
This PR makes --debug more useful by:
- Logging the thread ID: this ensures we know which log messages go together
- Logging git commands and scan errors
=> Improvements to --debug

ggshield/scan/scannable.py, tests/scan/test_commit.py, tests/scan/test_scannable.py
This bug caused crashes in `scan pre-receive` and `scan repo`.
Refactors the parser to use a stricter way to extract the filename. As a result, test data in test_scannable.py had to be adjusted because their diff files were wrong.
Fixes #273
=> Fix diff parser failing to extract filenames containing spaces

ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/pypi.py, ggshield/output/json/json_output_handler.py, ggshield/output/json/schemas.py, ggshield/output/output_handler.py, ggshield/output/text/text_output_handler.py, ggshield/scan/__init__.py, ggshield/scan/scannable.py, tests/cmd/scan/test_prereceive.py, tests/cmd/test_ignore.py, tests/core/test_utils.py, tests/output/test_text_output.py, tests/scan/test_scannable.py
closes #267 
When an error occurs when scanning a commit, `ggshield` will no longer stop. The error is printed in stderr and included in the JSON output.
I changed the timeout to 0.3s to force errors during the scan, here an example of the JSON output:
```json
{
"id": "hello-gg",
"type": "commit-range",
"scans": [
{
"id": "5be496155e6c6a86199a744903a42419983d2592",
"type": "commit",
"errors": [
{
"files": [
{
"mode": "NEW",
"filename": "test.py"
}
],
"description": "HTTPSConnectionPool(host='api.gitguardian.com', port=443): Read timed out. (read timeout=0.3)"
}
],
"extra_info": {
"author": "Samuel Guillaume",
"email": "sguillaume@dev.dev",
"date": "Mon Aug 16 16:41:06 2021 +0200"
},
"total_incidents": 0,
"total_occurrences": 0
}
],
"total_incidents": 0,
"total_occurrences": 0
}
```
=> feat(scan): Do not abort repo scan if a commit fails to scan

.github/workflows/main.yml
Remove the `scanning-released` CI step. It uses the latest release of ggshield to scan our code. That does not work well when this repository .gitguardian.yaml files contains configuration keys that the latest release does not support.
Current breakage: https://github.com/GitGuardian/ggshield/runs/7425018269?check_suite_focus=true.
See #304 for more details.
=> Unbreak main branch

ggshield/cmd/iac/scan.py
Add a IaC scan helper message.
The help commands results are now:
```
> ggshield iac --help
Usage: ggshield iac [OPTIONS] COMMAND [ARGS]...
Commands to work with infrastructure as code.
Options:
-h, --help  Show this message and exit.
Commands:
scan  Scan a directory for IaC vulnerabilities.
```
```
> ggshield iac scan --help
Usage: ggshield iac scan [OPTIONS] DIRECTORY
Scan a directory for IaC vulnerabilities.
Options:
--exit-zero                     Always return 0 (non-error) status code.
--minimum-severity [LOW|MEDIUM|HIGH|CRITICAL]
Minimum severity of the policies
-v, --verbose                   Verbose display mode.
--ignore-policy, --ipo TEXT     Policies to exclude from the results.
--ignore-path, --ipa PATH       Do not scan the specified paths.
--json …
```
=> Add a helper message for iac scan command

README.md
We add the missing pre-receive command in the README.md
=> docs(readme): add pre-receive section in README

ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/core/cache.py
Issue #306 
Like it is done for `scan ci`, we do not want to create cache when running `scan pre-receive`
Tested manually using the doc/pre-receive.sample script :
After committing a secret, run `echo "HEAD <recent-commit-ID> <unused-arg>" | sh doc/pre-receive.sample`
No cache file .cache_ggshield is created
=> feat(scan): do not create ggshield cache when scan pre-receive

ggshield/scan/repo.py, ggshield/scan/scannable.py
We already catch exceptions happening when API calls fail, but not if the error happens *before* (or after) calling the API. With this change we catch all exceptions, report them and carry on.
Fixes #323
=> Fix `scan repo` aborting if parsing git diff fails

tests/conftest.py, tests/output/test_json_output.py, tests/scan/test_scannable.py
- Turn `_NO_SECRET` fixture into a proper patch, with header
- Rename it to `_NO_SECRET_PATCH` for consistency
=> Fix _NO_SECRET fixture being ignored

ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/range.py, ggshield/scan/repo.py, tests/cmd/scan/test_ci.py, tests/cmd/scan/test_prepush.py
fix: fix users not finding correct `scan ci` statistics on their page
Bring back the `ci/$CI_NAME` value of the `mode` header.
Fixes #320
=> Fix value for `mode` header in CI mode

ggshield/scan/repo.py
Add missing `f` which would prevent showing the error message.
=> Fix bad display of error messages in scan_commit_range()

ggshield/cmd/iac/scan.py, ggshield/core/extra_headers.py, ggshield/scan/repo.py, ggshield/scan/scannable.py, tests/scan/test_scan.py
This MR adds a new HTTP header, used for server-side debugging: `GGShield-Command-Id`. This header makes it possible to group all API calls generated by a single ggshield command.
- Reduce duplication in HTTP header handling code (this is #233).
- Add the necessary API to the `extra_headers` module to generate command_ids and send them.
- Use this API in the `scan.repo` module.
=> Add a GGShield-Command-Id HTTP header

ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/repo.py, ggshield/core/utils.py, ggshield/scan/docker.py, ggshield/scan/repo.py, ggshield/scan/scannable.py, tests/cmd/scan/test_ci.py, tests/cmd/scan/test_prepush.py, tests/cmd/test_ignore.py, tests/core/test_utils.py, tests/output/test_json_output.py, tests/scan/test_scan.py, tests/scan/test_scannable.py
This PR improves our scanning API with the following changes:
- Remove the `scan_id` argument from `scan_repo_path()` and `scan_commit_range()`. Reducing the number of arguments of these functions improves readability.
- Rename the SupportedScanMode enum to ScanMode.
- Rename the `mode_header` argument to `scan_mode`, and make it accept either a ScanMode or an str. It would have been better to make it only a ScanMode, but we need the str format for the CI mode.
=> Simplify and improve scanning API

ggshield/core/constants.py, ggshield/core/file_utils.py, ggshield/scan/docker.py, ggshield/scan/scannable.py, tests/core/test_file_utils.py, tests/scan/test_scannable.py
Use pygitguardian `DOCUMENT_SIZE_THRESHOLD_BYTES` constant instead of duplicating its value in core.constants.
Avoids head-scratching when one increases this value and wonders why the changes have no effects...
=> Do not duplicate pygitguardian upload-limit constant

README.md
Per Jérémy Lanfranchi, the number of things ggshields scans for is now over 350, this update is just to change that one number in the README.
=> update number of types of secrets in README

ggshield/cmd/main.py, ggshield/core/utils.py, tests/core/test_utils.py
This PR fixes loading .env files: ggshield was loading the parent .env file instead of the one in the current directory.
It also adds a debug log to report the path to the loaded .env file, which can be useful when debugging setup issues. To do this I had to move the load of the .env after the log setup, otherwise the path was not printed.
=> Fix .env loading, and log the loaded path

ggshield/scan/scannable.py
If you run `ggshield` without an internet connection, it will print errors but not fail. Within a CI if the server is not accessible, the CI will not fail.
This PR raises an exception when the status code is missing, meaning the server did not respond.
=> fix: Fail when the server cannot be accessed

Pipfile, Pipfile.lock, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/core/text_utils.py, ggshield/scan/docker.py, ggshield/scan/repo.py, ggshield/scan/scannable.py, tests/cmd/scan/test_prereceive.py, tests/scan/test_scan_repo.py
The `ggshield secret scan repo` command used to make one API call per commit. This implementation was not efficient and could result in thousands of call for important repos. In most cases, one commit contains modifications to only a couple of files. This implies a lot of very small API calls.   
We propose an implementation to group commits together as long as the total number of files sent to the API is below a fixed limit (20 at the time of writing).  
The implementation modifies `scan_commit_range` as follows : we create an intermediary steps where commits are iterated over and grouped to form batches of at most 20 files. These are ultimately sent to the API using the `Files.scan` interface.   
We also adapted the results parsing logic : now that one API call contains files from …
=> Improve scan repo perfs

ggshield/core/config/config.py, ggshield/core/config/utils.py, tests/core/config/test_utils.py
The only place in the code where the GITGUARDIAN_INSTANCE env variable was loaded was 'ggshield\ggshield\core\config\config.py' so removing the trailing slash when reading the url would make the command 
`ggshield auth login --instance https://dashboard.gitguardian.com/` 
Equals to:
`ggshield auth login --instance https://dashboard.gitguardian.com` 
and returns: 
`ggshield is already authenticated without an expiry date`
if used after a first call to `ggshield auth login --instance https://dashboard.gitguardian.com`
I simply unit tested my utils function that removed the traling slash. I tried to write a test for the two consecutive calls but got stuck so far as the configuration for the existing tests seems to try to assert that no instances are stored before the cli command is run. …
=> Fix issue 357 trailing slash in instance creates a new instance

ggshield/cmd/install.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/core/git_shell.py, tests/cmd/scan/test_prepush.py, tests/cmd/scan/test_prereceive.py, tests/cmd/test_install.py, tests/repository.py
This PR fixes #303: when ggshield is used a pre-push hook and the user pushes a new branch, ggshield does not know the branch start commit and scans up to 50 commits.
Some preliminary work has been done first:
- Adding a way to create *real* repositories in test code, so that tests are not out of touch with reality.
- Fixing some tests which were out of touch with reality.
Then the command was fixed, by taking inspiration from how pre-commit solves this problem, and extending our fix for scanning parent-less commits (#313) to apply there too.
Finally, the generated hook had to be fixed, because the `ggshield secret scan pre-push` now uses the command-line arguments, which were not forwarded by the hook we generated.
Fixes #303.
=> Make prepush smarter

ggshield/cmd/secret/scan/prereceive.py, tests/functional/secret/test_scan_prereceive.py, tests/unit/cmd/scan/test_prereceive.py
This PR makes `ggshield secret scan pre-receive` smarter when a new branch is pushed: it now only scans the new commits instead of scanning the last 50 ones by default.
- Clean existing pre-receive tests
- Implement the new behavior
- Add a functional test
Fixes #369
=> Make pre-receive smarter

ggshield/core/check_updates.py
This is consistent with the way we get the configuration dir in `core/config/utils.py`.
I created an issue to avoid this inconsistency in the future: #376.
=> Set appname and appauthor to get cache dir

ggshield/cmd/iac/scan.py, ggshield/core/utils.py
The modes for the IAC API analytics will be `directory` and `others` so we want to align with that.
=> Modify iac scan mode name for analytics

.github/workflows/tag.yml
Fix Homebrew formulas not being correctly update on release.
This can happen if the new package is not yet available from pypi.org when we update the formula. In this case `pip install ggshield` installs the previous version.
Fix this by explicitly requesting the new version and trying 5 times to install.
Tested on a fork of the repo:
- Failure to install the latest version (simulated by using a version number which is not available on pypi.org): https://github.com/agateau-gg/ggshield/actions/runs/3233886780/jobs/5296316238
- Successfully installing the new version (simulated by using the version number of the current release): https://github.com/agateau-gg/ggshield/actions/runs/3233900129/jobs/5296345794 (Job fails because the fork does not have the credentials to publish, as expected)
=> Fix homebrew update

ggshield/cmd/auth/login.py, ggshield/core/config/auth_config.py, ggshield/core/oauth.py, ggshield/core/utils.py, tests/unit/cmd/auth/test_login.py, tests/unit/core/config/test_auth_config.py
- Factorize code creating the AccountConfig instance from auth/login.py and oauth.py in a new method: InstanceConfig.init_account()
- Fix parsing of the optional "expire_at" value we receive from the API: we receive it as a string, so it must be converted into a `datetime`
=> Do not fail when `auth login` is called with a lifetime argument

README.md
Fix missing args in the Readme.
=> docs(readme): update missing args in pre-push commands

ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, tests/functional/secret/test_scan_prepush.py, tests/functional/secret/test_scan_prereceive.py, tests/unit/cmd/scan/test_prepush.py, tests/unit/cmd/scan/test_prereceive.py
In this case the call to `git rev-list...` returns no commits, causing
ggshield to crash because `ancestors` is empty.
=> Do not crash if pushed branch contains no new commits

ggshield/scan/scannable.py, tests/functional/secret/test_scan_path.py
GitGuardian API does not accept paths longer than 256 characters. Truncate longer paths to keep only the end.
Fixes a regression introduced in 1.13.3.
Fixes #391
=> Do not fail to scan paths longer than 256 characters

.github/workflows/tag.yml
Use the new Homebrew update script from the homebrew-tap repository.
Tested in my fork: https://github.com/agateau-gg/ggshield/actions/runs/3271811007/jobs/5382043742
I faked a release of 1.10.1: I had to overwrite existing tags (in my fork, don't worry!) so that the update script would find a matching release of ggshield on pypi.org.
Fixes #385.
=> Fix update of Homebrew taps on release

ggshield/core/check_updates.py, ggshield/core/config/auth_config.py, ggshield/core/config/utils.py, ggshield/core/dirs.py, tests/unit/cmd/auth/test_login.py, tests/unit/cmd/auth/test_logout.py, tests/unit/cmd/test_config.py
https://github.com/GitGuardian/ggshield/issues/376
This PR refactors ggshield's code.  We introduce a new module `core/dirs.py` that gets imported by two different files:
- `ggshield/core/check_updates.py`
- `ggshield/core/config/utils.py`
which helps us avoid interacting directly with `appdirs` package: narrowing the room for error.
=> Centralize directory access in a dirs.py module

ggshield/output/json/schemas.py
Running the test suite produces these warnings at the end:
```
../../.local/share/virtualenvs/ggshield-c3rFhSjf/lib/python3.8/site-packages/marshmallow/fields.py:173
../../.local/share/virtualenvs/ggshield-c3rFhSjf/lib/python3.8/site-packages/marshmallow/fields.py:173
/home/agateau/.local/share/virtualenvs/ggshield-c3rFhSjf/lib/python3.8/site-packages/marshmallow/fields.py:173: RemovedInMarshmallow4Warning: The 'default' argument to fields is deprecated. Use 'dump_default' instead.
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
Marshmallow deprecated `default` in favor of `dump_default` in [Marshmallow 3.13.0][changelog].
We depend on Marshmallow 3.15, so we can use `dump_default`.
[changelog]: …
=> Fix warnings when running unit-tests

ggshield/core/check_updates.py, ggshield/core/config/auth_config.py, ggshield/core/config/user_config.py, ggshield/core/config/utils.py, tests/unit/core/config/test_auth_config.py, tests/unit/core/config/test_config.py, tests/unit/core/config/test_user_config.py, tests/unit/core/test_cache.py
This PR fixes the problem we have when the `.gitguardian.yml` file contains a string (or anything else that is not a valid dict), we get a non-explanatory error message.
Moreover, this PR also cleans and refactors some parts of the code by:
- Removing unused imports
- Removing unused variables
- Removing unused arguments
It also changes the tests to make them compliant with the new changes.
https://github.com/GitGuardian/ggshield/issues/377
If the `configuration` is an invalid dict, we get the following output:
`The configuration in '.gitguardian.yml' is invalid. Please verify it.`
=> Make core.config.utils.load_yaml check the type of the loaded data

ggshield/core/config/user_config.py, ggshield/core/config/utils.py, tests/unit/core/config/test_auth_config.py, tests/unit/core/config/test_user_config.py
This PR slightly reworks error messages when we can't load the configuration. It removes some  `Error: Error in (...)` sequences and some duplication of the filename. The "Invalid YAML" error message is still a bit filled with jargon, but it's good enough for now I think.
It also reduces indentation in `load_yaml_dict()` to make code a bit easier to read.
Invalid YAML:
```
$ ggshield api-status
Error: Error in ./.gitguardian.yaml:
Parsing error while reading ./.gitguardian.yaml:
while parsing a flow node
expected the node content, but found '<stream end>'
in "./.gitguardian.yaml", line 2, column 1
```
YAML string:
```
$ ggshield api-status
Error: Error in ./.gitguardian.yaml:
The configuration in './.gitguardian.yaml' is invalid. Configuration must be a dict.
```
Invalid YAML:
```
$ …
```
=> Rework error messages when we can't load the configuration

.pre-commit-hooks.yaml, ggshield/cmd/main.py
By default, the pre-commit framework calls hooks with files to scan as arguments. If the file list is too long, it splits it and run scans in parallel.
This is not adapted for ggshield because `ggshield secret scan pre-commit` (and `pre-push`) gets the content to scan from the commit ID, the arguments are ignored. When pre-commit calls ggshield twice, ggshield scans the whole commit twice.
- Tell pre-commit to not call ggshield with filenames, we avoid this issue: ggshield is only called once. The loss of parallelism is not an problem since ggshield handles parallelism itself.
- In debug mode, log the PID in addition to the thread ID. This should make debugging multi-process issues easier in the future.
I created a repository with 100 new files, one of them containing 2 secrets.
I setup …
=> Fix pre-commit scanning commits with many files multiple times

.github/workflows/perfbench.yml, .pre-commit-config.yaml, scripts/perfbench/.gitignore, scripts/perfbench/perfbench, scripts/perfbench/perfbench_utils.py, scripts/perfbench/report_cmd.py, scripts/perfbench/run_cmd.py, scripts/perfbench/setup_cmd.py
This PR adds a `scripts/perfbench/perfbench` script.
Results show up in the summary of the "Performance benchmark" check.
TODO:
looks fast enough to run on each PR for now
=> Add a benchmark script

Pipfile, Pipfile.lock, setup.py
This is required to properly release a new version of ggshield.
=> chore: update pygitguardian dependency

.github/workflows/tag.yml
`gh-action-pypi-publish` action has sunset its master branch. We switch to branch `release/v1`.  
See this [part of the action's readme](https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-).
=> chore(workflows): update gh-action-pypi-publish action branch

ggshield/cmd/common_options.py, ggshield/cmd/scan/__init__.py, ggshield/cmd/secret/scan/__init__.py, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/cmd/secret/scan/docset.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/repo.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, tests/unit/cmd/scan/test_path.py
This is the second episode of #197.
First commit introduces a helper function to create Click callbacks which set config values: `create_config_callback()`. It then uses this helper for the --verbose and --allow-self-signed options.
Second commit introduces a `add_secret_scan_common_options()` decorator to define all scan options, similarly to `add_common_options()`. This decorator calls `add_common_options()`, so the commit modifies all scan commands to use `add_secret_scan_common_options()` instead of `add_common_options()`.
`add_secret_scan_common_options()` only implements the --exit-zero, --exclude  and --ignore-known-secrets options for now. Other options are coming in the next episode.
=> Allow using --exit-zero, --exclude and --ignore-known-secrets anywhere on the command line

ggshield/scan/repo.py, tests/unit/scan/test_scan_repo.py
Fixes issue https://github.com/GitGuardian/ggshield/issues/428
=> fix: same secret should be shown once in the results output for scan command

ggshield/cmd/install.py, ggshield/cmd/secret/scan/repo.py, ggshield/core/git_shell.py, ggshield/scan/scannable.py, tests/unit/cmd/scan/test_ci.py, tests/unit/cmd/scan/test_prereceive.py, tests/unit/core/test_git_shell.py, tests/unit/scan/test_scan_repo.py
This PR fixes the crash which happens when running on a machine where git is not installed.
Before:
```
$ ggshield --help
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/src-NVTF7jWz/bin/ggshield", line 5, in <module>
from ggshield.cmd.main import main
File "/src/ggshield/cmd/main.py", line 10, in <module>
from ggshield.cmd.auth import auth_group
File "/src/ggshield/cmd/auth/__init__.py", line 5, in <module>
from ggshield.cmd.common_options import add_common_options
File "/src/ggshield/cmd/common_options.py", line 18, in <module>
from ggshield.core.config.user_config import UserConfig
File "/src/ggshield/core/config/__init__.py", line 1, in <module>
from .auth_config import AccountConfig, InstanceConfig
File "/src/ggshield/core/config/auth_config.py", line 20, in …
```
=> Fix crash if git is not available

.github/workflows/main.yml, Pipfile.lock, scripts/update-pipfile-lock/Dockerfile
Recent pipenv versions fail to install our dependencies from the Pipfile when using Python 3.7. See https://github.com/GitGuardian/ggshield/actions/runs/3573106794/jobs/6007049578 for example.
This PR "fixes" this by pinning the version of pipenv we use.
It also updates the pinned version in the update-pipfile-lock script for consistency.
=> Fix build failure with Python 3.7

scripts/perfbench/run_cmd.py, scripts/perfbench/setup_cmd.py
To provide a more interesting benchmark, add a weird repositories with lots of secrets to our list.
Reduce the number of commits scanned, because the added repository does not have enough commits.
=> Add a repository with secrets to the performance bench

ggshield/scan/scan_context.py, tests/unit/conftest.py, tests/unit/core/test_utils.py, tests/unit/scan/test_scan.py
This MR introduces 3 new HTTP headers to the requests we submit to GG's API.
The headers include:
- `OS-Name` header: A header that contains the OS on which ggshield is running
- `OS-Version`: The version of said OS
- `Python-Version`: The python version used to run ggshield
The previously mentioned changes result in the reception of the following extra logs:
```
ggshield_os_name=ubuntu 
ggshield_os_version=22.04 
ggshield_python_version=3.10.6
``` 
I wonder whether these metadata are okay or if we should trim them. 
For instance, instead of submitting a full verbose Python version, we may probably just send the first part (e.g., `3.10.6 `).
> I would advise against trimming the OS version though because we'll probably fail to match the **version** only (e.g., `#59-Ubuntu`) given that …
=> feat: Introduce new headers (OS, Python) version

ggshield/cmd/secret/scan/prereceive.py, tests/functional/secret/test_scan_commit_range.py, tests/functional/secret/test_scan_precommit.py, tests/functional/secret/test_scan_prepush.py, tests/functional/secret/test_scan_prereceive.py, tests/functional/secret/test_scan_repo.py, tests/repository.py, tests/unit/cmd/scan/test_prereceive.py
When a branch is force-pushed, the pre-receive hook currently rescans the overwritten commits. This waste time and can report issues on code which is going away since it is being overwritten.
The pre-receive hook currently scans the commit range it receives via stdin (see [pre-receive hook doc][doc]), unless the code is pushing a new branch (because in this case the range start ref is the all-zeroes sha).
This PR fixes the bug by ignoring the range start ref received via stdin and always determining the start of the pushed code using the code currently used for the "new branch" case.
[doc]: https://git-scm.com/docs/githooks#pre-receive
- Some improvements to our `Repository` helper class: it learned how to `add()` and `push()`.
- Rewrote the pre-receive tests to use real repositories …
=> pre-receive: do not scan commits overwritten by push --force

ggshield/core/check_updates.py
GGShield checks for updates by connecting to GitHub anonymously.  The anonymous API quota is relatively small.  For organizations where hundreds of users all connect via a common egress IP, this can result in significant error messages (collectively across users) / confusion during GGShield operations.  For example:
```
% git commit -m 'My Awesome Commit' awesome.py
Failed to check: {"message":"API rate limit exceeded for 1.2.3.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
This PR address this issue by checking for quota exceeded condition and rescheduling the update check for after the quota has been …
=> Handle GitHub Rate Limits During Update Checks

ggshield/output/text/message.py, ggshield/output/text/text_output_handler.py, tests/unit/cmd/scan/test_path.py, tests/unit/output/test_text_output.py
This previous [commit](https://github.com/GitGuardian/ggshield/commit/5eda13805490f899491b9b0cf7ff7fbb6be05945) removed the "No secrets have been found" message.  
1. We re-introduce this message with a variation when ignore-known-secrets is used. 
2. We adapt the tests
3. We refactor the existing test `test_ignore_known_secrets`. Most of the logic is in the `assert_...` functions, it should be easier to read : refer to our internal documentation for the different cases.  
closes #448
=> fix(output): #448 Re-introduce the "all clear" message when applicable

.github/workflows/main.yml, setup.py
https://github.com/GitGuardian/ggshield/issues/383
This MR introduces two small changes:
- Now; ggshield does not install its tests folders and subfolders
- We have a new CI step that ensures such behavior (installing non-desired chunks of ggshield) does not occur again.
=> FIX: GGshield should not install its tests

.pre-commit-config.yaml, scripts/README.md, scripts/release
This PR introduces a `scripts/release` script to automate release steps. It knows about the following steps:
- running tests without cassettes
- bumping the version number and creating the tag
- pushing the tag
- publishing the GitHub release, once it has been created as a draft by the CI
=> Release script

Dockerfile
Our Docker image contains SSH server keys. These keys are generated when openssh server is installed. These keys are in /etc/ssh:
```
$ docker run --rm gitguardian/ggshield:latest ls /etc/ssh/
moduli
ssh_config
ssh_config.d
ssh_host_ecdsa_key
ssh_host_ecdsa_key.pub
ssh_host_ed25519_key
ssh_host_ed25519_key.pub
ssh_host_rsa_key
ssh_host_rsa_key.pub
sshd_config
sshd_config.d
```
`ggshield` Docker image does not need an SSH server though, it only needs an SSH *client*, to be able to clone git repositories over SSH.
This PR changes the Dockerfile to only install the SSH client, so now we have:
```
$ docker run --rm gitguardian/ggshield:tst ls /etc/ssh/ 
ssh_config
ssh_config.d
```
While I was at it, I simplified the package installation part of the Dockerfile a bit, in a separate commit.
=> Remove SSH server keys from our Docker image

ggshield/cmd/scan/__init__.py
Currently, we show a warning message when the deprecated command `ggshield scan` is used. The message we show is in yellow.
We would like to print it in red and inform the user that this command will be completely removed starting from version 1.15.0
We introduced a new boolean argument to the `display_warning` function called `critical`, which is set to False by default. If `¢ritical` is True, we show the message in red, and yellow otherwise.
We use the `error` style to display the message in red. We did not create another style `critical_warning` because we'll be duplicating the same style properties (red color) as the `error` style.
=> Make the `ggshield scan` deprecation message more alarming

ggshield/core/filter.py, tests/unit/cmd/scan/test_path.py
The --exclude option was not working as expected on Windows because of failing regexes when excluding filepaths.  
We use `pathlib.PurePosixPath` to convert Windows path to posix path and apply regex on them.  
We also add an extra test to test the exclusion of a whole directory from the scan.
=> feat(test_path): #168 unskip failing tests on Windows

ggshield/core/git_shell.py
Git recently patched a CVE that causes some commands to fail if a repository is not owned by the command executor. In this PR we raise a more explicit error in such cases.
Steps to validate :  
- Run a Docker image with the correct requirements to install ggshield
- Mount a volume containing : gghsield repo checked out on this branch, another git repository
- Open a shell in the container
- Install ggshield
- Run a `ggshield secret scan repo <PATH_TO_OTHER_REPO>`
You should get the following error message :
```
(ggshield) app@4ee33c28fd3e:/data/ggshield$ ggshield secret scan repo ../MY_REPO/
ERROR: Git command failed because of a dubious ownership in repository.
If you still want to run ggshield, make sure you mark the current repository as safe for git.
`git config --global --add …
```
=> Improve error management to better catch some git errors

.pre-commit-config.yaml, tests/functional/secret/test_scan_pypi.py
The release of 1.14.3 broke the `secret scan pypi` test. Thanks to #383, the ggshield pypi package no longer contains its tests, so it no longer contains test secrets. Pin the tested version to fix that.
While doing this, isort pre-commit decided to fail, because of https://github.com/PyCQA/isort/issues/2077, so fix that too.
=> Unbreak `secret scan pypi` functional tests

README.md
- Point Stars badge to stargazers
- Point Build badge to Actions tab"
Without this, clicking on those badges opens the image of the badge, which is useless.
=> Make all README.md badges clickable

.dockerignore, .github/workflows/main.yml, Dockerfile, docker/entrypoint.sh, tests/conftest.py, tests/functional/conftest.py, tests/functional/secret/test_scan_docker.py, tests/functional/test_docker_image.py, tests/unit/conftest.py
This PR changes gitguardian/ggshield image behavior so that $PWD is marked as a safe git directory at run time, instead of always marking /data. This ensures the Docker image can be used to run scan commands that use git, even if the source to scan is not mounted in /data.
Also adds a test for this.
=> Make our Docker image usable even if the source is not mounted in /data

ggshield/cmd/install.py, tests/unit/cmd/test_install.py
This PR fixes Visual Studio failing to run our git hook by using `/bin/sh` as a shebang, meaning only Posix shell (no more `if [[ something ]]`)
While working on this I noticed some output messages were mixing Windows and Unix path separators, producing things like that:
```
$ ggshield.exe install -m global -t pre-commit -f
pre-commit successfully added in C:\Users\User/.git/hooks/pre-commit
```
I took the opportunity to migrate the code in `install.py` to use `Path`, fixing that issue while doing so.
Best reviewed commit-by-commit.
Fixes #467
=> Fix hook failing in VisualStudio

.github/workflows/main.yml, .github/workflows/perfbench.yml
Do not run steps which require the GITGUARDIAN_API_KEY variable. These steps always fail because the variable is not available for pull-requests coming from forks.
Fixes #374
This PR merges a branch from the GitGuardian/ggshield repository, so all steps should run.
PR #484 merges the same branch, but from my fork of the repository, and this time not all steps run. 
Update: looks like GitHub is confused and now shows the same results as for this PR. You can look at this [previous run](https://github.com/GitGuardian/ggshield/actions/runs/4243739433) to see skipped jobs (the GitHub action test jobs) and steps (the functional tests inside the build jobs). There is also this [run of the performance benchmark](https://github.com/GitGuardian/ggshield/actions/runs/4243739426) which is skipped …
=> Fix fails on pull-requests from forks

ggshield/cmd/iac/scan.py, tests/unit/cassettes/test_iac_scan_no_argument.yaml, tests/unit/cmd/iac/test_scan.py
Allow `ggshield iac scan` to run with no provided argument (taking current directory as default)
=> fix: allow iac scan command to run with no argument

ggshield/core/client.py, tests/unit/core/test_client.py
When we fail to connect, do not let the error propagate: the backtrace is ugly to read in verbose mode.
When the key is invalid, do not show `response.detail`. It contains "Invalid API key", so we end up printing:
ERROR: Invalid API key. Details: Invalid API key.
When we receive a 404, tell the user to check the server URL.
=> chore: improve error handling in check_client_api_key()

ggshield/core/client.py, tests/unit/core/test_utils.py
When a user has no API key set, we add instructions about how to authenticate to GitGuardian's dashboard and get one as part of the error message.  
We also reference our documentation and mention how to deal with the login if the user have an on-prem install.
=> Improve error message when a user has no API key set

ggshield/core/check_updates.py, tests/unit/core/test_check_updates.py
Do not fail with a strange error message.
Reading the date of the last check from `update_check.yaml` failed because the name of the key is `check-at`, not `check_at`. This used to work because `load_yaml_dict()` transparently turned `-` into `_`, but it does not do this anymore now that we fixed #480.
- Fix the key name.
- Move loading and saving to separate functions to make the code easier to test.
- Add more tests.
=> Fix reading the time we last checked for updates

ggshield/core/config/config.py
If the user authenticated with `ggshield auth login` but has `$GITGUARDIAN_API_KEY` defined, then the environment variable overrides the key stored by `ggshield auth login`.
To make debugging that easier, add `logger.debug()` calls when ggshield successfully reads environment variables.
Tested manually with `ggshield --debug api-status` and `ggshield secret scan path ...`.
```
$ ggshield api-status --debug                            
2023-03-17 09:39:07,788 DEBUG ac3a:7f891735e1c0 ggshield.cmd.debug_logs:setup_debug_logs:35 args=['/home/agateau/.local/share/virtualenvs/ggshield-c3rFhSjf/bin/ggshield', 'api-status', '--debug']
2023-03-17 09:39:07,788 DEBUG ac3a:7f891735e1c0 ggshield.cmd.debug_logs:setup_debug_logs:36 py-gitguardian=1.5.0
2023-03-17 09:39:07,788 DEBUG ac3a:7f891735e1c0 …
```
=> Add debug logging when using environment variables

Pipfile, Pipfile.lock, setup.py
We used to list dependencies of ggshield both in the Pipfile and in the setup.py.   
This can lead to discrepancies between the two files, and hence packages being not correctly shipped with gg-shield.  
To prevent this in the future, this PR gets rid of gg-shield dependencies in the Pipfile. Pipenv will install the package along with its dependencies anyway.
**Extra note:** We also had to pin pytest to avoid conflicting dependencies.
=> Clean dependencies listed in the Pipfile

ggshield/cmd/auth/login.py, ggshield/core/client.py, ggshield/core/config/config.py, ggshield/core/constants.py, ggshield/core/oauth.py, tests/unit/cmd/auth/test_login.py, tests/unit/cmd/auth/test_logout.py, tests/unit/cmd/iac/test_scan.py, tests/unit/cmd/test_config.py, tests/unit/cmd/utils.py, tests/unit/conftest.py, tests/unit/request_mock.py
If `ggshield auth login` is used to create a token, but the token is then removed server-side, GGShield is not aware of it:
- When calling `ggshield auth login` at this point GGShield prints a message saying it's ready, but trying to scan prints an error message complaining about an invalid API key.
- Calling `ggshield auth logout` fails because the token does not exist server-side, so it can't be revoked.
One must call `ggshield auth logout --no-revoke` then `ggshield auth login` again.
With this PR, if a token is stored in the config, `ggshield auth login` checks it's valid. If it is not, it forgets it and start the auth workflow.
The amount of changes necessary to implement this new behavior was small, but writing tests was not. I ended up heavily refactoring …
=> Make `auth login` handle server-side removed tokens

.github/workflows/perfbench.yml, ggshield/cmd/iac/scan.py, ggshield/cmd/secret/scan/docset.py, ggshield/core/file_utils.py, ggshield/iac/filter.py, ggshield/output/text/iac_text_output_handler.py, ggshield/scan/__init__.py, ggshield/scan/docker.py, ggshield/scan/scannable.py, ggshield/scan/scanner.py, tests/conftest.py, tests/unit/cmd/scan/test_docker.py, tests/unit/cmd/scan/test_prereceive.py, tests/unit/core/test_file_utils.py, tests/unit/core/test_utils.py, tests/unit/iac/test_filter.py, tests/unit/output/test_json_output.py, tests/unit/output/test_text_output.py, tests/unit/scan/test_scan_docker.py, tests/unit/scan/test_scan_repo.py, tests/unit/scan/test_scannable.py, tests/unit/scan/test_scanner.py
This PR paves the way to supporting server-side config and reading from various sources. It does so by refactoring the File class and introducing an abstract base class for scannable content, called Scannable.
Scannable has the following API:
- `url` property: Act as a unique identifier for the Scannable. May use custom protocols if required
- `path` property: "path" part of the API, returned as a `pathlib.Path`. Useful for local files
- `is_longer_than(self, size: int) -> bool`: returns true if the length of the *decoded* content is greater than `size`. Used by SecretScanner to decide if afile should be scanned or not
- `content` property: Returns the *decoded* content
File now inherits from Scannable and implements its API.
This PR also introduces StringScannable, which inherits from …
=> Refactor file reading

ggshield/core/file_utils.py, ggshield/scan/docker.py, ggshield/scan/scannable.py, ggshield/scan/scanner.py, scripts/perfbench/perfbench_utils.py, scripts/perfbench/report_cmd.py, scripts/perfbench/run_cmd.py
This PR is a follow-up for #503. It reworks the way we read the content of Docker images to avoid enforcing document size limits manually.
It also adds calls to `ggshield secret scan docker` to our performance benchmark.
After this change, `DOCUMENT_SIZE_THRESHOLD_BYTES` is only used by `SecretScanner`, except for tests. This puts us in a better position to make this value customizable for on-prem instances.
The work is done by introducing a `DockerContentScannable` class, which knows how to read content inside a Docker image archive (which is a tar archive containing other tar archives, one per layer)
It also introduces a `DockerFiles` class, which inherits from `Files`, and keeps a reference to the overall opened tar archive, so that it stays open.
Some of the code from `File` has been …
=> Refactor file reading, Docker part

Pipfile, Pipfile.lock, changelog.d/20230417_123418_aurelien.gateau_cache_docker_successful_scan.md, ggshield/core/dirs.py, ggshield/scan/docker.py, ggshield/scan/id_cache.py, ggshield/scan/scanner.py, scripts/perfbench/run_cmd.py, setup.py, tests/conftest.py, tests/functional/secret/test_scan_docker.py, tests/unit/cmd/scan/test_docker.py, tests/unit/conftest.py, tests/unit/scan/test_id_cache.py, tests/unit/scan/test_scan_docker.py
This PR makes `ggshield secret scan docker` remember the IDs of layers which did not contain policy breaks so that it does not scan them again.
This is implemented by storing the IDs of clean layers in a cache file on disk. The file name is based on the secrets engine version so that when a new version of the secrets engine is deployed the cache is invalidated.
1st commit rework scanning a bit to avoid loading the content of a layer too early: we don't want to load the content if the layer is known to be clean.
2nd commit implements the cache itself and make use of it in the scan implementation.
3rd commit factorizes some test data used by docker tests. It was actually not needed after all, but the code is cleaner this way so I kept it.
4th commit adds a functional test. Unfortunately it …
=> Cache Docker successful scans

ggshield/scan/docker.py, tests/unit/cmd/scan/test_docker.py, tests/unit/conftest.py, tests/unit/scan/test_scan_docker.py
The current implementation of the Docker cache refers to layers using the random ID used as a folder name to store layer tarballs. This PR changes this to use the [layer DiffID](https://github.com/moby/moby/blob/master/image/spec/v1.2.md#terminology). There are two benefits to this:
- The ID is generated from the content: no risk of (unlikely) clash, higher chances of cache hits
- This ID is more likely to be known by the user: it is visible in the output of `docker inspect` for example
First two commits do some more cleanups to the code reading the Docker archives: they turn many helper functions into class members of either DockerImage or LayerInfo. They also makes it clearer which JSON files are read.
Third commit introduces the use of DiffID.
=> Make `ggshield secret scan docker` use DiffID for layers

ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/core/config/user_config.py, tests/unit/core/config/test_user_config.py
When we added the `--ignore-known-secrets` option, we made a small mistake: the `ignore-known-secrets` configuration key should have been created in `UserConfig.secret` instead of `UserConfig`.
This PR fixes that. It silently loads the key from UserConfig if it's there to avoid any breakage.
=> Move ignore-known-secrets configuration key

.github/workflows/main.yml, .github/workflows/tag.yml
This PR fixes a few minor issues found during 1.15.0 release:
- Extend tests to Python 3.11.0.
- Fix GitHub deprecation warnings about `set-output` usage (see https://github.com/GitGuardian/ggshield/actions/runs/4795329835: scroll the page to the "Annotations" section to see what I mean)
One of the deprecation fixes replaces usage of GitHub actions with `gh`. I tested this change in a [sandbox repository](https://github.com/agateau-gg/ci-sandbox).
=> Post release fixes

CONTRIBUTING.md, doc/dev/architecture.md, doc/dev/dependencies.md, doc/dev/getting-started.md, scripts/release, tests/unit/conftest.py
This MR splits the `CONTRIBUTE.md` file and expands its content.
It also removes the need to define the `$TEST_GITGUARDIAN_API_KEY` to run tests. This makes running tests for the first time simpler.
To get a better preview of what the end result looks like, here is a direct link to  [CONTRIBUTE.md](https://github.com/GitGuardian/ggshield/blob/agateau/expand-dev-doc/CONTRIBUTING.md) on this branch.
=> Expand developer documentation

.github/workflows/main.yml, Pipfile
vcrpy does not use urllib3 correctly. Pin urllib3 until https://github.com/kevin1024/vcrpy/issues/688 is fixed.
=> Fix test failure

changelog.d/20230510_161532_samuel.guillaume_fix_scan_option_ignore_known_secrets.md, ggshield/cmd/secret/scan/secret_scan_common_options.py
The flag `--ignore-known-secrets` does not work because the path of the corresponding value in the config is now `config.secret.ignore_known_secrets` since b37d1a1b52a4ed591d55fccc986c85cf9f545521
=> fix(cli): # Fix the common scan option --ignore-known-secrets

scripts/release
Our `scripts/release` branch refused to run unless it was on the main branch (or `--dev-mode` was set). This PR makes it accept running on other release branches.
=> Make it possible to run the release script from any release branch

changelog.d/20230517_105917_pierrelalanne_add_incident_url_to_json_output.md, ggshield/output/json/json_output_handler.py, ggshield/output/json/schemas.py, tests/unit/output/test_json_output.py
Closes #525 
We included an `incident_url` key in the `FlattenedPolicyBreak` schema.  
This key will always be present and defaults to "N/A" if no matching incident exists in the dashboard.  
We chose "N/A" to have a consistent `str` type, to match the text output and to ease validation with voluptuous. 
We adapted tests in consequence.
Given this input (fake creds):  
```python
apikey=rk_live_VZpzxUqUVrzX2eajXf4MCGgyxJlBoIspDEso68lKmE8RxPEYHHf3IMEuKXOzA4P5Vz2VRB7GyAPAs
apikey=rk_live_VZpzxUqUVrzX2eajXf4MCGgyxJlBoIspDEso68lKmE8RxPEYHHf3IMEuKXOzA4P5Vz2VRB7GyAPAz
```
This command :
```shell
ggshield secret scan path --ignore-known-secrets dummy.py --json | jq '.'
```
Will generate this json:
```json
{
"id": "........./dummy.py",
"type": "path_scan",
"entities_with_incidents": [
{
"mode": …
```
=> Add incident url to json output

changelog.d/20230517_164846_samuel.guillaume_417_pre_receive_timeout_is_not_precise_enough.md, ggshield/cmd/secret/scan/prereceive.py, ggshield/core/git_shell.py, tests/functional/conftest.py, tests/functional/secret/test_scan_prereceive.py, tests/unit/cmd/scan/test_prereceive.py
Fixes #417 
I first tried the solution proposed in the issue, but it did not work. Threads can not be killed and Python will always wait for all of its threads to end before exiting. If an API call is stuck, nothing can be done from the same process.
I've implemented a more brutal solution: move the logic within a sub-process which can be killed when it takes too long. To test it, I've added a functional test with a fake server which won't response in the middle of a request.
In the unit tests, to not rewrite the existing tests, the `multiprocessing.Process` is mock to run in the main-process and `multiprocessing.Pipe` to not use a unix socket.
=> fix(pre-receive): #417 Execute pre-receive within a sub-process to accurately enforce the timeout

ggshield/core/utils.py
As discussed earlier, this method is not often used but I think it should have the same logic as `dashboard_to_api_url()`.
=> fix: use GITGUARDIAN_DOMAINS in api_to_dashboard

scripts/perfbench/run_cmd.py, scripts/perfbench/setup_cmd.py
The performance benchmark is broken because one of the repo (`leaky-repo`) it uses has been removed. Replace it with the `sample_secrets` repository.
=> Fix performance benchmark

Pipfile.lock, setup.py
Requests gets installed via py-gitguardian, but ggshield uses it itself, so add it to our dependencies.
Set the minimum version to 2.31.0 because of
https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q.
This takes care of #538 too.
=> Add explicit dependency on requests and update it

Pipfile.lock, setup.py
Following the [release of py-gitguardian 1.7.0](https://github.com/GitGuardian/py-gitguardian/releases/tag/v1.7.0), we update the dependency in GG-Shield.
=> chore: update to py-gitguardian 1.7.0

changelog.d/20230526_113935_samuel.guillaume_json_and_text_outputs_dont_display_the_same_sha.md, ggshield/secret/output/secret_json_output_handler.py, tests/conftest.py, tests/functional/secret/test_scan_path.py, tests/functional/utils.py, tests/unit/secret/output/test_json_output.py, tests/unit/secret/output/test_text_output.py
The field `ignore_sha` in the JSON output differs from the one outputted by the text output when `--show-secrets` is not used, because it is computed after censoring the matches.
The PR fixes the bug and add both unit and functional tests to prevent regression.
=> fix(json_output_handler): Compute the ignore sha before censoring the matches

changelog.d/20230529_173848_pierrelalanne_fix_gitlab_web_ui_output.md, ggshield/cmd/secret/scan/prereceive.py, ggshield/secret/output/secret_gitlab_webui_output_handler.py, ggshield/secret/output/secret_output_handler.py, tests/unit/secret/output/test_gitlab_webui_output.py
We recently experienced a bug where one of our users could not correctly visualize the results of a `scan pre-receive` in the GitLab UI. Especially, an error message was still displayed when pushing known secrets with the `ignore-known-secrets` option. Indeed, this option had not been ported to the GitLab web UI handler.  
While reproducing the bug, we realized that a regression now simply made it impossible to visualize the `GL-HOOK-ERR` message in the UI.   
This PR does mainly two things:  
1. We adapt GitLab Web UI output handler to behave as expected when used with the `ignore-known-secrets` option  
To do so, we add an `ignore_known_secrets` property to the `SecretGitLabWebUIOutputHandler` object. We also modify `_process_scan_impl` to make sure that only relevant secrets incidents …
=> Fix GitLab web UI output handler

scripts/release
This PR fixes a small issue caught during 1.15.1 release: the changes done in the `1.15.x` branch were not pushed.
=> Fix `scripts/release tag` not pushing the hotfix branch

.env.example, .github/workflows/ci.yml, doc/dev/getting-started.md, tests/conftest.py, tests/functional/secret/test_scan_path.py
This PR adds a functional test for the `--ignore-known-secrets` option.
Since testing this requires a known secret, it adds a new test environment variable: `TEST_KNOWN_SECRET`, containing the known secret. I added it to our CI configuration so that the test can pass.
=> Add functional tests for --ignore-known-secrets

Pipfile, ggshield/cmd/config/__init__.py, ggshield/core/dirs.py, ggshield/secret/output/schemas.py, tests/conftest.py, tests/functional/test_docker_image.py
This PR fixes a few minor issues:
- Fix a Marshmallow deprecation warning
- Update to mypy 1.3.0, and fix related issues
- Fix the test_docker_image functional test failing when not started from the repository root directory
=> Minor cleanups

ggshield/cmd/iac/scan.py, ggshield/cmd/install.py, ggshield/cmd/secret/ignore.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/secret_scan_common_options.py
Click default help messages are sentences: they start with an upper-case letter and end with a point. Make our help messages follow the same format for consistency.
=> Improve consistency of --help messages

ggshield/cmd/common_options.py, ggshield/cmd/iac/scan.py, ggshield/cmd/quota.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/cmd/status.py, ggshield/core/utils.py
Defining `--json` in 3 different places is a bit too much :)
Move `utils.json_output_option_decorator()` to common_options, renaming it `json_option()`. Make it use `create_ctx_callback()`.
Add a `use_json()` helper function to common_options, to know if `--json` has been set.
Uses these new functions in:
- cmd.iac.scan
- cmd.secret.scan.secret_scan_common_options
- cmd.status
- cmd.quota
=> Factorize all --json option decorators

changelog.d/20230607_193232_aurelien.gateau_improve_error_reporting.md, ggshield/cmd/debug_logs.py, ggshield/cmd/main.py, ggshield/core/cache.py, ggshield/core/config/utils.py, ggshield/core/errors.py, ggshield/secret/secret_scanner.py, tests/unit/secret/snapshots/snap_test_secret_scanner.py
When an error occurs, for example a network timeout, sometimes the error is reported twice: as a human-friendly message and using the logger. This can be seen in this example:
```
$ ggshield secret scan path -ry .
status_code=None detail=HTTPSConnectionPool(host='api.gitguardian.com', port=443): Read timed out. (read timeout=60)
Scanning Path... ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  10% 45 files scanned out of 469 0:00:14
ERROR: Error scanning: HTTPSConnectionPool(host='api.gitguardian.com', port=443): Read timed out. (read timeout=60)
```
This PR disables logging by default, unless --debug or --log-file is set. It also rework some exception messages to make them more user-friendly. The error from above is now reported like this:
```
$ ggshield secret scan path -ry .
Scanning Path... …
```
=> Improve error reporting

changelog.d/20230612_161810_antonin.lacombe_update_honeytoken_helps_and_error.md, ggshield/cmd/honeytoken/create.py, tests/unit/cassettes/test_honeytoken_create_error_403.yaml, tests/unit/cmd/honeytoken/test_honeytoken.py
This PR improve the `honeytoken create` command, 
The help text has been updated by the product team. 
The error displayed when a 403 is received has changed to help the user to setup honeytokens on their account.
=> docs(honeytoken): Honeytoken improve help textes and error 

ggshield/cmd/iac/scan/diff.py, ggshield/scan/scan_mode.py
IaC diff scans must send a distinct scan mode header to GIM.
GIM uses the header for analytics.
=> New diff scan mode

changelog.d/20230615_104700_arnaud.lustrat_support_max_lifetime_tokens.md, ggshield/core/oauth.py, tests/unit/cmd/auth/test_login.py
These changes aim to support the maximum lifetime feature that will be added to the business workspace. This setting enforces the maximum allowed lifetime for all personal access tokens created on the workspace.
Information about if the new personal access token expiration date has been downsized to fit the workspace setting is added to the API. Following this information, a warning message is added to the login output to inform the client.
The maximum lifetime feature is still in development and should be released soon. But these changes should not be breaking even if the API is not yet updated.
=> feat(oauth): #COR-1425 Support max lifetime on access tokens

ggshield/core/git_shell.py
Scanning a subfolder should work as long as it is inside a git repository. This is the (working) behaviour for the `iac scan all` command.
However, it fails with the `iac scan diff` command, and throws an ugly error message
Currently, the only fix in this PR is to throw a prettier message to the user, suggesting them to execute the scan at the git root.
However, we might prefer fixing the issue.
It comes from the `git show` command used to create the tars. This only works with a path relative to the git root (not relative to the cwd).
=> Fix error when executing a diff scan in a subfolder of a git repository

ggshield/cmd/common_options.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, tests/unit/cassettes/test_iac_scan_all_exit_zero.yaml, tests/unit/cassettes/test_iac_scan_diff_exit_zero.yaml, tests/unit/cassettes/test_iac_scan_exit_zero.yaml, tests/unit/cmd/iac/test_scan_common.py
How it works:
We connect the exit-zero option for iac  scans to the existing callback for secret scans.
The option is then handled in main.py
Depends on #569 for some tests to work
=> fix(iac-scan): exit-zero option was ignored for both iac scans

ggshield/iac/filter.py, tests/unit/iac/test_filter.py
Validation was weak on file extensions.
=> fix(iac): fix filter on extensions / remove .py extension

Pipfile.lock, setup.py
- Update py-gitguardian from git ref to 1.8.0
- Update cryptography from 40.0.2 to 41.0.0, to fix OpenSSL vulnerability (see https://github.com/GitGuardian/ggshield/security/dependabot/6)
=> chore: update dependencies

scripts/release
This PR adds another test to scripts/release to ensure all dependencies point to a released version and not a git commit (pointing to a git commit is bad-practice and is dangerous because they can go away with a force-push).
- Copy the Pipfile.lock from https://github.com/GitGuardian/ggshield/blob/94ad722a36a88f0c420dbede0d632cbddc88b288/Pipfile.lock
- Run `scripts/release run-tests`
- Get an error
=> Prevent releasing with a git dependency on py-gitguardian

ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_utils.py, ggshield/core/git_shell.py, ggshield/core/utils.py, ggshield/iac/filter.py, ggshield/iac/iac_scan_models.py, ggshield/iac/output/iac_json_output_handler.py, ggshield/iac/output/iac_output_handler.py, ggshield/iac/output/iac_text_output_handler.py, ggshield/scan/commit.py, ggshield/scan/scannable.py, ggshield/secret/output/secret_json_output_handler.py, ggshield/secret/output/secret_text_output_handler.py, ggshield/secret/secret_scan_collection.py, tests/functional/iac/test_iac_scan_diff.py, tests/unit/iac/test_filter.py, tests/unit/scan/test_commit.py, tests/unit/secret/output/test_json_output.py, tests/unit/secret/output/test_text_output.py, tests/unit/secret/test_secret_scanner.py
This PR fixes a problematic behavior in IaC diff scans.
When no IaC files have been changed and a diff scan is requested, the tar archives are still built and sent for scanning even though no additional IaC incident will be found.
While it is true the scanning backend could have gotten new vulnerability detectors in the meantime, we generally do not want the scan to raise warnings when no IaC files have been touched.
With an additional function in `git_shell.py`, we can detect the status of files relative to the given git reference.
If any file has been added/removed/modified AND is an IaC file, we perform the diff scan as usual. Else, we notify that the scan was skipped and return 0.
- the `git_diff_file_status(...)` function has been added to `git_shell.py`. This function returns the …
=> fix: no changed iac files leads to empty diff iac scan

changelog.d/20230704_152111_aurelien.gateau_docker_max_workers.md, ggshield/cmd/secret/scan/docset.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/secret/docker.py, ggshield/secret/secret_scanner.py
While investigating a bug which eventually proved to be unrelated, I found out `secret scan docker` did not honor the $GG_MAX_WORKERS environment variable.
Change the default value for the `scan_threads` argument of `SecretScanner.scan()` to use `ggshield.constants.MAX_WORKERS` (which is initialized from $GG_MAX_WORKERS) instead of 4. This makes it possible to simplify all scan callers since they do not have to pass a value for the `scan_threads` argument.
~I also improved logging a bit, so that logging with --debug produce a less messy output.~
Update: just removed that part because it was not reliable.
=> Make `ggshield secret scan docker` honor $GG_MAX_WORKERS

ggshield/iac/collection/iac_diff_scan_collection.py, ggshield/iac/collection/iac_path_scan_collection.py, ggshield/iac/collection/iac_scan_collection.py, tests/functional/iac/test_iac_scan_all.py, tests/functional/iac/test_iac_scan_diff.py, tests/unit/iac/collection/test_iac_scan_collection.py
Currently, having unchanged or deleted vulnerabilities would also trigger an exit code 1.
This makes it more difficult to use the command in CI, as only new vulnerabilities should throw an alert.
=> Fix: iac scan diff should only return an exit code 1 if new vulnerabilities are found

ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_utils.py, ggshield/core/git_shell.py, tests/unit/core/test_git_shell.py
When executing a `iac scan diff`,
- all files in the repo are listed
- non-IaC files are filtered out of the list
- remaining files are added to a tar
Currently, files are filtered based on their path only, but their content is read and passed to the filter function anyway.
This PR removes the `acceptation_func` from the tar creation function, which now expects the filepaths list to be already filtered.
Also, caching is added to the file opening function, in case the iac filter requires to read them in the future.
Execution time for `iac scan diff --ref 253d331b8b44e87d11238f715b904828330ed84e` on the ggshield repo:
- with the old behaviour: ~7,5s
- with this new behaviour: ~5,8s
=> Perf: in iac diff scan, allow file filter to operate without opening the files

Pipfile, Pipfile.lock, changelog.d/20230705_120528_samuel.guillaume_scrt_3734_ggshield_improve_handling_of_quota_limit_reached_errors.md, ggshield/core/errors.py, ggshield/secret/repo.py, ggshield/secret/secret_scanner.py, tests/functional/conftest.py, tests/functional/secret/test_scan_repo.py, tests/unit/secret/test_secret_scanner.py
closes #309 
The output of ggshield when the quota limit is reached can be confusing:
```shell
$ ggshield secret scan path setup.py
Scanning Path... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0 files scanned out of 1 -:--:--
Scanning failed. Results may be incomplete.
The following chunk is affected:
/Users/sguillaume/gg-src/ggshield/setup.py
403:Quota limit reached.
Scanning Path... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1 files scanned out of 1 0:00:00
No secrets have been found
```
Even more with the JSON output:
```shell
$ ggshield secret scan path setup.py --json
Scanning Path... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0 files scanned out of 1 -:--:--
Scanning failed. Results may be incomplete.
The following chunk is affected: …
```
=> Improve handling of quota limit reached errors

ggshield/cmd/sca/scan.py, tests/unit/cassettes/test_sca_get_scan_all_filepaths.yaml, tests/unit/cassettes/test_sca_scan_all_no_file.yaml, tests/unit/cassettes/test_sca_scan_all_valid.yaml, tests/unit/sca/conftest.py
- fix `compute_sca_files` call and cassettes
- remove fix for python 3.7, whose support was just dropped (https://github.com/GitGuardian/ggshield/pull/613)
=> Mmillet/ /fixes

.gitguardian.yml
In the iac scan tests, we need to test the CI integration. To do this we scan the HEAD of this repo.
However with the update of iac-api, new policies have been added.
Among them, the policy GG_IAC_0079 is detected in this repo.
Information on the policy :
https://docs.gitguardian.com/iac-scanning/policies/GG_IAC_0079
Present in these files :
Dockerfile
scripts/update-pipfile-lock/Dockerfile
tests/functional/data/docker-leaking-in-env/Dockerfile
tests/functional/data/docker-leaking-in-layer/Dockerfile 
For now, we chose to ignore it  to enable the CI to pass but another solution would be to correct this vulnerabilities.
=> ignore-policy-gg-iac-0079-on-self-scan

.gitguardian.yaml, .gitguardian.yml
Merge .gitguardian.yml into .gitguardian.yaml and remove .gitguardian.yml.
Having both causes .gitguardian.yaml to not be loaded, causing the `tests/functional/test_docker_image.py` tests to fail (they did not fail in the PR because the test clones ggshield `main` branch).
=> Fix gitlab functional tests

ggshield/cmd/iac/scan/scan.py
When receiving tar files in GIM, we first hash the tarfile bytes content to generate a key used for caching.
The goal is to not scan the same tar file twice.
However, the order of bytes are important and if we do not generate the tarfile using always the same path order, the tarfile will have different bytes order (event if the uncompressed directory is the same)
=> sort paths to enable iac scan all caching

Pipfile.lock, changelog.d/20230712_171932_aurelien.gateau_fix_maximum_size_check.md, ggshield/scan/file.py, ggshield/scan/scannable.py, ggshield/secret/docker.py, setup.py, tests/unit/scan/test_file.py, tests/unit/scan/test_scannable.py
`Scannable.is_longer_than()` currently compares the size passed to it to the decoded size, but what we actually want to compare it to is the *UTF-8 encoded size*.
To implement this without reading the content multiple times, `Scannable` implementations now store the UTF-8 encoded size, and `Scannable` helper methods (`_is_file_longer_than()` and `_decode_bytes()`) return the UTF-8 encoded size in addition to their current return value.
When the content they work on is already UTF-8, the helpers try to avoid reading it until necessary.
This PR also integrates the latest py-gitguardian changes, which are also related to this issue.
Issue: #561
=> Fix ggshield secret scan trying to scan too large documents

scripts/run-functional-tests
Fix the functional tests in the CI. `cryptography` wasn't installed and the tests failed.
=> chore(functest): Install ggshield with all extras before functional tests

ggshield/iac/output/iac_text_output_handler.py, tests/unit/iac/output/test_iac_diff_text_output.py, tests/unit/iac/output/test_iac_text_output.py
https://linear.app/gitguardian/issue/IAC-136/ggshield-add-link-to-the-policy-documentation
=> IaC scans: display a link to the policy documentation

ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/secret/scan/secret_scan_common_options.py
`--ignore-path` and `--exclude` expect a pattern rather than a file path.
Regex patterns do not work, as special characters are escaped.
Here is how the input value is transformed:
```
if pattern[-1] != "/":
pattern += "$"
if pattern[0] == "/":
pattern = "^" + pattern[1:]
else:
pattern = "(^|/)" + pattern
pattern = re.sub(r"\\\*\\\*/", "([^/]+/)*", pattern)
pattern = re.sub(r"\\\*", "([^/]+)", pattern)
```
And here is how the filtering is done:
```
def is_filepath_excluded(filepath: str, exclusion_regexes: Set[re.Pattern]) -> bool:
return any(r.search(str(PurePosixPath(Path(filepath)))) for r in exclusion_regexes)
```
=> Improve help message for --ignore-path (iac) and --exclude (secret)

ggshield/cmd/common_options.py, ggshield/cmd/iac/scan/__init__.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/iac/scan/scan.py, ggshield/cmd/sca/scan.py, ggshield/cmd/sca/scan_common_options.py, ggshield/core/config/user_config.py, ggshield/sca/client.py, ggshield/sca/sca_scan_models.py, tests/unit/core/config/test_user_config.py, tests/unit/sca/test_client.py
Added CI params common to `secrets` and `iac` scans as well as `ignore-paths` and `minimum-severity` to `sca`'s scan commands.
=> feat(sca): add CI params for sca scan commands

ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/prepush.py, ggshield/cmd/secret/scan/prepush.py, ggshield/core/git_hooks/prepush.py, ggshield/core/git_shell.py, tests/functional/iac/test_iac_scan_prepush.py, tests/functional/utils.py, tests/unit/cassettes/test_iac_scan_prepush_no_iac_changes_all.yaml, tests/unit/cassettes/test_iac_scan_prepush_output_all.yaml, tests/unit/cassettes/test_iac_scan_prepush_output_diff.yaml, tests/unit/cmd/iac/test_scan_prepush.py, tests/unit/core/test_git_shell.py
Command meant to be used in a pre-push git hook to scan iac files for vulnerabilities.
Some parts to focus on:
- moved some functions from `ggshield/cmd/secret/scan/prepush.py` to `ggshield/core/git_hooks/prepush.py` in order for them to be used both in secrets and iac (and maybe sca in the future)
=> `iac scan prepush` command

ggshield/cmd/main.py, tests/conftest.py
enables color output in CI.
Adds the option to disable color entirely with NO_COLOR (https://no-color.org/)
=> feat(color): Enable color output in GitLab CI

ggshield/core/text_utils.py, ggshield/iac/output/iac_text_output_handler.py
Update colors in `ggshield iac scan diff`.
=> feat(iac): Improved color output of iac diff scan

Pipfile.lock, changelog.d/20230727_102601_samuel.guillaume_pin_pyyaml_gte_6_0_1.md, setup.py
Cython 3.0 was released and breaks building PyYAML 6.0,0. PyYAML 6.0.1 pins the Cython build dependency to Cython<3.0 so it can build.
As a side-effect of updating the `Pipefile.lock`, it fixes https://github.com/GitGuardian/ggshield/security/dependabot/7
=> chore: pin PyYAML>=6.0.1

changelog.d/20230720_140628_antonin.lacombe_logout_hmsl_when_auth_logout.md, ggshield/cmd/auth/logout.py, ggshield/hmsl/utils.py, tests/unit/hmsl/test_hmsl_utils.py
Remove the JWT token when doing a ggshield logout
=> alacombe/expl-187/Logout HMSL when calling GGshield auth logout

ggshield/cmd/sca/scan/sca_scan_utils.py, ggshield/sca/client.py, ggshield/sca/file_selection.py, tests/unit/cassettes/test_sca_scan_diff_ignore.yaml, tests/unit/cmd/sca/test_scan.py
There is a bit of a weird behavior in the tests. All files are ignored, but an API call will still be made to filter the SCA files. This is probably fine as it will never happen in real cases, but makes the cassette necessary in the tests even though the API calls are useless.
=> jgriffe/sca 871/ignore paths declared in configuration

changelog.d/20230801_185552_henri.hubert_add_ghsa_id.md, ggshield/sca/output/text_handler.py, tests/functional/sca/test_sca_scan_all.py, tests/unit/cmd/sca/test_precommit.py, tests/unit/cmd/sca/test_scan.py
Add the vulnerability identifier in the text output when present.
It should appear with the next release
=> add vulnerability identifier in text output for SCA scans

.pre-commit-config.yaml
Pyright and ggshield are the slowest pre-commit tasks, having them at the end of the file makes them run last.
Having those last allows to have error from linters (most common IMO) first, leading to a more pleasant experience. WDYT ?
=> chore(pre-commit): reorder pre-commit to fail fast

ggshield/iac/output/iac_text_output_handler.py
In the diff scan output summary, for each status (new/deleted/remaining), the counts of vulnerabilities are now sorted by severity order.
=> chore(iac): Sort summary vulns by severity order

changelog.d/20230807_180315_aurelien.gateau_config_set_instance.md, ggshield/cmd/config/__init__.py, ggshield/cmd/config/config_get.py, ggshield/cmd/config/config_set.py, ggshield/cmd/config/config_unset.py, ggshield/cmd/config/constants.py, ggshield/core/config/user_config.py, ggshield/core/config/utils.py, ggshield/core/constants.py, ggshield/core/dirs.py, tests/conftest.py, tests/unit/cmd/test_config.py, tests/unit/core/config/conftest.py
This PR makes it possible to set the default instance of GitGuardian to use with `ggshield config set instance <THE_INSTANCE_URL>`.
What the command does is setting the `instance` field of the user global configuration file (~/.gitguardian.yaml, ~/.gitguardian.yml or ~/.gitguardian). If no such file exists, it creates the ~/.gitguardian.yaml file.
The next PR completes this by allowing the default instance to be read with `ggshield config get instance`, unset with `ggshield config unset instance` and listed in `ggshield config list`.
The first 3 commits make some cleanups.
Then the next two rework the way we find the user config file to make it possible to implement and test `ggshield config set instance`.
The final commit really implements the feature.
This should make bug #359 a bit …
=> Allow defining the default config instance

.pre-commit-config.yaml
Remove filter on Python files
For an unknown reason, this filter was added. According to [the documentation](https://pre-commit.com/#config-types), it acts as a filter (logical AND) and will not trigger a scan for non python files.
To test the behavior before the change:
- modify the `.prettierignore`
- commit
- the `GitGuardian Shield` job is skipped
=> chore(pre-commit): run ggshield-local on all files

changelog.d/20230807_180315_aurelien.gateau_config_set_instance.md, ggshield/cmd/config/config_get.py, ggshield/cmd/config/config_list.py, ggshield/cmd/config/config_set.py, ggshield/cmd/config/config_unset.py, tests/unit/cmd/test_config.py
This PR is the continuation of #670. #670 added support for `ggshield config set instance <NAME>`. This PR adds support for `ggshield config get instance`, `ggshield config unset instance` and make `ggshield config list` show the instance.
=> Add support for "instance" to "ggshield config get", "unset", and "list"

Pipfile, ggshield/cmd/main.py, setup.py
Now that our [Homebrew formula supports cryptography](https://github.com/GitGuardian/homebrew-tap/pull/4) we can re-enable HMSL.
This PR more-or-less undoes what was done for 1.17.2 in eeca9e30dd05441ba3fca525b268fafcaa7d6814.
=> Re-enable HMSL by default

.github/workflows/ci.yml, ggshield/cmd/iac/scan/ci.py, ggshield/cmd/sca/scan/ci.py, ggshield/core/git_hooks/ci/__init__.py, ggshield/core/git_hooks/ci/commit_range.py, ggshield/core/git_hooks/ci/current_and_previous_state.py, ggshield/core/git_hooks/ci/previous_commit.py, ggshield/core/git_hooks/ci/supported_ci.py, ggshield/core/git_shell.py, tests/functional/sca/test_sca_scan_ci.py, tests/unit/cmd/sca/test_ci.py, tests/unit/cmd/scan/test_ci.py
This MR adds a util to get the previous state of the targeted branch in CI for github, and use it in sca scan ci.
It also removes the need of defining a custom env variable for PR in github CI. A custom env variable is still required for push event on github.
For now, SCA and IaC CI scans work only with github and gitlab CIs. 
All other CIs will come in a next PR.
=> Xblanchot/sca 942/fix commit range in ci

changelog.d/20230811_135805_aurelien.gateau_unhide_hmsl.md, ggshield/cmd/hmsl/__init__.py
This PR makes the `hmsl` command group visible, so that it can be discovered in the upcoming release.
=> Unhide hmsl command group

ggshield/cmd/auth/login.py, ggshield/core/config/config.py, ggshield/core/oauth.py, tests/unit/cmd/auth/test_login.py, tests/unit/core/config/test_config.py, tests/unit/core/test_utils.py
To login on an instance other than the default instance, users pass the `--instance INSTANCE_URL` option to `ggshield auth login`. This does not make INSTANCE_URL the default instance though, leading to confusion.
This PR makes `ggshield auth login` print a message suggesting to use `ggshield config set instance INSTANCE_URL` when `auth login` is called with `--instance`.
- Turn `Config.set_cmdline_instance()` into a `cmdline_instance` property
- Add the message
Logging in on the default instance, no message:
```
$ ggshield auth login --method token
Enter your GitGuardian API token: 
Authentication was successful.
```
Logging in on a custom instance, suggestion message is printed:
```
$ ggshield auth login --method token --instance https://example.com
Enter your GitGuardian API token: …
```
=> Suggest using `ggshield config set instance` at login

changelog.d/20230725_144801_paul.beslin.ext_update_github_action_iac_command.md, docker/actions-iac-entrypoint.sh
Depends on #628 to be deployed for the stable action to work.
Updates the IaC Github Action to use the new `ggshield iac scan ci` command instead of `ggshield iac scan all`.
=> feat(iac): github action should now use the new CI command

ggshield/core/config/config.py, tests/unit/cmd/hmsl/test_api_status.py, tests/unit/cmd/hmsl/test_check.py, tests/unit/cmd/hmsl/test_query.py, tests/unit/cmd/hmsl/test_quota.py, tests/unit/hmsl/test_hmsl_utils.py
Fixes EXPL-201
When GITGUARDIAN_SAAS_API_KEY is not set and GITGUARDIAN_API_KEY is set, the auth will use the later.
=> HMSL Auth uses GITGUARDIAN_API_KEY if GITGUARDIAN_SAAS_API_KEY is not set

changelog.d/20230818_111845_aurelien.gateau_fix_typo.md, ggshield/core/git_shell.py
Found this while testing ggshield from inside a Docker container.
=> Fix typo in git command to mark a directory as safe

ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/ci.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/precommit.py, ggshield/cmd/iac/scan/prepush.py, ggshield/cmd/iac/scan/prereceive.py, ggshield/core/errors.py, ggshield/core/git_shell.py
We used to call UsageError raising an exception which was not of type _ExitError. However, we are using the function handle_exception from this same file ggshield/core/errors.py, which tests if the exception raised is from type _ExitError else return an UNEXPECTED_ERROR. So with the old way and after adding the exception wrapper, we always ended up having this exit code whereas we wanted a USAGE_ERROR one.
=> feat(iac): #IAC-211 add exception wrapper in commands

.github/workflows/perfbench.yml
Pin pipenv to a version which still supports the --skip-lock option, like we do in the ci.yml workflow.
This fixes https://github.com/GitGuardian/ggshield/actions/runs/5924686760/job/16062675817?pr=700
```
Successfully installed certifi-2023.7.22 distlib-0.3.7 filelock-3.12.2 pipenv-2023.8.20 platformdirs-3.10.0 setuptools-68.1.2 virtualenv-20.24.3
The flag --skip-lock has been functionally removed.  Without running the lock 
resolver it is not possible to manage multiple package indexes.  Additionally it
bypassed the build consistency guarantees provided by maintaining a lock file.
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.12/x64/bin/pipenv", line 8, in <module>
sys.exit(cli())
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pipen …
```
=> fix: unbreak perfbench step

Makefile, scripts/run-functional-tests, tests/conftest.py
Some users could have hooks defined in their Git template directory. The content of this directory is copied every time a repository is cloned or created. We have to isolate our functional tests to avoid the user Git config interferes with our tests.
=> Isolate functional tests from user Git config

README.md
- Changed the documentation installation method with pip to use `--user` to prevent
installing system-wide. It's not recommended to install system wide and may not work anyway on OS where the system Python is marked as externally managed (see [PEP 668](https://peps.python.org/pep-0668/). It's the case for Debian 12 for example.
- Documented the fact that the tool can also be installed with [pipx](https://pypa.github.io/pipx/).
=> docs(readme): update installation instructions

ggshield/cmd/auth/login.py, ggshield/core/text_utils.py, ggshield/verticals/auth/__init__.py, ggshield/verticals/auth/oauth.py, tests/unit/cmd/auth/test_login.py, tests/unit/verticals/auth/test_oauth.py
This PR introduces an `auth` "vertical". It's not a real vertical but it provides the same support as other `ggshield.verticals` packages to the `ggshield.cmd` packages.
I initially considered moving part of cmd.login and cmd.logout there but it would require more refactoring to make the code less tied to the CLI parsing and output. It is not worth the move without these refactoring IMHO and I do not want to spend time on it for now.
Instead I just moved OAuthClient and its related code there, and moved an helper date formatting function to core.textutils.
While I was at it, I simplified said helper date and made it output a more correctly formatted string.
Part of #521.
=> Create the auth "vertical"

.github/workflows/ci.yml
Forks do not have GITGUARDIAN_API_KEY defined, causing the ggshield hooks of pre-commit to fail.
This PR makes the CI skip these hooks for PR from forks. It has been tested via #712.
=> chore(ci): do not fail the build for forks

doc/dev/getting-started.md, ggshield/cmd/hmsl/__init__.py, ggshield/cmd/hmsl/check_secret_manager/__init__.py, ggshield/cmd/hmsl/check_secret_manager/hashicorp_vault.py, ggshield/verticals/hmsl/secret_manager/hashicorp_vault.py, tests/unit/cmd/hmsl/check_secret_manager/test_hashicorp_vault.py, tests/unit/verticals/hmsl/hashicorp_vault/test_hashicorp_vault.py
- Add initial structure for the new `hmsl check-secret-manager`
- Add initial structure for the first command, `hashicorp-vault` (corresponding code in the verticals module will be in a later PR). For now the command and the group are hidden due to the implementation not being done. The aim is to have an early feedback on the structure and to split the work in multiple and smaller PRs.
- Add note in doc to use an old version of pipenv when developing due to missing `--skip-lock` option in recent versions
I added the `skip-changelog` label due to the implementation not being done, I will add the changelog once the command is functional.
=> feat(hmsl): add initial structure for check-secret-manager group

.importlinter, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_utils.py, ggshield/core/scan/commit.py, ggshield/core/scan/file.py, ggshield/utils/files.py, ggshield/verticals/sca/file_selection.py, ggshield/verticals/secret/docker.py, scripts/generate-import-linter-config.py, tests/unit/utils/test_files.py
The functions inside the module are not ggshield specific and should be in the ggshield.utils module according to the architecture described in #521.
refs #521
=> refactor: Move ggshield.core.file_utils to ggshield.utils.files

ggshield/utils/git_shell.py, ggshield/verticals/iac/output/iac_text_output_handler.py, tests/functional/iac/test_iac_scan_diff.py, tests/unit/verticals/iac/output/test_iac_diff_text_output.py
In case of a scan launched on a directory within a repository, the related file content was not found.
=> fix: file content could not be found

setup.cfg
Use the new entrypoint. This got lost during the conversion from setup.py to setup.cfg.
=> Fix the build

ggshield/cmd/honeytoken/create.py, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/cmd/utils/common_options.py, ggshield/core/check_updates.py, ggshield/core/config/utils.py, ggshield/core/scan/file.py, ggshield/utils/click/__init__.py, ggshield/utils/click/real_path.py, ggshield/utils/files.py, ggshield/verticals/hmsl/utils.py, ggshield/verticals/iac/filter.py, ggshield/verticals/sca/file_selection.py, ggshield/verticals/secret/docker.py, ggshield/verticals/secret/output/secret_output_handler.py, ggshield/verticals/secret/secret_scan_collection.py, tests/unit/cmd/scan/test_docker.py, tests/unit/cmd/scan/test_pypi.py, tests/unit/verticals/secret/test_scan_docker.py
This PR makes more code use Path instead of os.path.
Part of #464
- Added a RealPath helper to utils.click
- Migrated all of cmd.secret to Path
- Some fixes on the type of arguments accepting wildcards: they should not be defined as path, since they are not paths
- Minor changes in honeytoken code to make it use Path to read/write files
- Rework of DockerImage to use Path, this required a slightly-more-involved-than-expected refactor
- Make core.check_updates() use Path
This does not solve #464 completely, but it moves in the right direction. I prefer merging this work early to avoid a giant, hard to merge, PR.
=> Migrate more code to use Path

ggshield/__main__.py, ggshield/core/constants.py, ggshield/core/env_utils.py, ggshield/core/git_hooks/prereceive.py, ggshield/utils/git_shell.py, ggshield/utils/os.py, tests/unit/utils/test_os.py
This PR makes it possible to override the timeout applied to all git commands with the `GG_GIT_TIMEOUT` environment variable.
I got a bit annoyed by the multiple places where we read environment variables and turn them into int, float or boolean, sometimes in different ways (at least for boolean variables) so I went a bit overboard and added new functions to `utils.os` to read int, float or boolean values from the environment. This is the first commit.
the second commit uses the new function to read the timeout, and log it in debug mode.
=> Add a way to override the default git timeout

ggshield/core/cache.py, ggshield/core/constants.py, tests/unit/core/test_cache.py
This PR makes `Cache` use Path and simplifies `Cache.load_cache()`.
I tried to update the constants in `core.constants` to use Path too but that caused issues in test (see the comment I added about this).
I think at this point we can consider #464 to be done.
=> Convert more code to use Path

.github/workflows/ci.yml, .github/workflows/perfbench.yml, Dockerfile, Pipfile.lock, doc/dev/getting-started.md, scripts/generate-import-linter-config.py, scripts/update-pipfile-lock/Dockerfile
This should fix build fails like [this one](https://github.com/GitGuardian/ggshield/actions/runs/6420681773/job/17456049876?pr=761), which after some investigation was found to be caused by two versions of charset-normalizer being installed, despite what `pip freeze` reported:
```
(ggshield) root@c906d7edca9b:~/ggshield# pip freeze | grep charset-normalizer
charset-normalizer==3.1.0
(ggshield) root@c906d7edca9b:~/ggshield# ls $VIRTUAL_ENV/lib/python3.10/site-packages/charset_normalizer* -d
/root/.local/share/virtualenvs/ggshield-UCtrC-t_/lib/python3.10/site-packages/charset_normalizer
/root/.local/share/virtualenvs/ggshield-UCtrC-t_/lib/python3.10/site-packages/charset_normalizer-3.1.0.dist-info
/root/.local/share/virtualenvs/ggshield-UCtrC-t_/lib/python3.10/site-packages/charset_normalize …
```
=> Fix `pipenv install --dev --skip-lock` installing multiple versions of a package

changelog.d/20231005_164337_henri.hubert_improve_vault_secret_name.md, ggshield/verticals/hmsl/collection.py, ggshield/verticals/hmsl/secret_manager/hashicorp_vault/api_client.py, tests/unit/verticals/hmsl/secret_manager/hashicorp_vault/test_api_client.py
We now return the full path of the secret when the naming strategy of the hint is the key
=> feat(hmsl,vault): use the full path of the secret as hint in results

ggshield/cmd/hmsl/api_status.py, ggshield/cmd/hmsl/hmsl_utils.py, ggshield/cmd/hmsl/query.py, ggshield/cmd/hmsl/quota.py, ggshield/verticals/hmsl/client.py, ggshield/verticals/hmsl/utils.py, tests/unit/verticals/hmsl/test_hmsl_client.py
- Add User-Agent header to HMSLClient
- Add a `GGShield-HMSL-Command-Name`, similar to `GGShield-Command-Path` in the secret module but which takes an enum value of possible HMSL command
=> chore: add headers to HMSL commands

ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/core/scan/__init__.py, ggshield/core/scan/commit.py, ggshield/core/scan/file.py, ggshield/core/scan/scannable.py, ggshield/verticals/iac/filter.py, ggshield/verticals/sca/file_selection.py, ggshield/verticals/secret/docker.py, tests/unit/cmd/scan/test_docker.py, tests/unit/core/scan/test_scannable.py, tests/unit/core/test_match_indices.py, tests/unit/verticals/secret/test_scan_docker.py
This PR removes the `Files` class, either inlining its features (like the filtering) or merging it into its only descendant class: `Commit`. The rationale for this removal is to prepare for the refactoring of the scanning classes to scan patches as we parse them instead of all at the end.
=> Remove the Files class

.github/workflows/ci.yml, .github/workflows/perfbench.yml, .github/workflows/tag.yml
This PR does some CI improvements:
- Add a CI check to prevent merging `fixup!` commits (you can see it working [here](https://github.com/GitGuardian/ggshield/actions/runs/6498289798/job/17649298419?pr=770))
- Update checkout action to v4
- Update codecov action to v3
=> CI improvements

Pipfile.lock, setup.cfg
Update lock for `py-gitguardian`.
=> chore(env): # Use py-gitguardian 1.11.0

changelog.d/20231016_140309_pierrelalanne_improve_hmsl_output.md, ggshield/verticals/hmsl/client.py, ggshield/verticals/hmsl/output.py, tests/unit/cmd/hmsl/test_check.py, tests/unit/cmd/hmsl/test_decrypt.py
This MR improve the model for Secret as well as the output to handle the cases where there is no url.
Please note that I choose to always keep a field "url" in the json output but it is nullable.
=> chore(hmsl): handle missing urls

tests/unit/cassettes/test_hmsl_query_hash.yaml, tests/unit/cmd/hmsl/test_query.py
After running the tests without cassettes, we modify one test:
- For HMSL: an URL is not returned by the API anymore
=> Modify some tests and cassettes

ggshield/verticals/iac/output/iac_text_output_handler.py, tests/unit/verticals/iac/output/test_iac_diff_text_output.py
https://linear.app/gitguardian/issue/IAC-420/scan-diff-isnt-showing-the-right-number-of-detected-new-incidents
In iac scan diff, text output: count of incidents in a file was always set to 1.
=> fix(iac): fix file incidents count in iac scan diff text output

changelog.d/20231006_173320_aurelien.gateau_oauth_scopes.md, ggshield/cmd/auth/login.py, ggshield/cmd/honeytoken/create.py, ggshield/verticals/auth/oauth.py, tests/unit/cmd/auth/test_login.py, tests/unit/request_mock.py, tests/unit/verticals/auth/test_oauth.py
This PR makes it possible to create a GitGuardian token with extra scopes in addition to the `scan` scope.
=> Add support for creating a token with extra scopes

tests/unit/verticals/iac/output/test_iac_text_output.py
In #767 we updated policy documentation url references in tests, but left one for compatibility reasons. This PR cleans the last reference.
=> test(iac): remove old policy documentation url from tests

.gitguardian.example.yml, changelog.d/20231019_095052_paul.beslin.ext_accept_comment_until_iac_config.md, ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/core/config/user_config.py, tests/unit/core/config/test_user_config.py
For both `ignored_policies` and `ignored_paths` in IAC config file, the expected data was changed.
Format before (still handled):
```
iac:
ignored-policies:
- "GG_IAC_0001"
```
New format handled:
```
iac:
ignored-policies:
- policy: "GG_IAC_0001"
comment: "This policy isn't vulnerable for this repo."
until: "2024-01-01T00:00:01Z"
```
Mixed formats are supported too.
Ignored policies and paths are only applied if no until date is provided, or if the date is in the future
=> Add comment and until date to iac config file

ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/sca/scan/sca_scan_utils.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/repo.py, ggshield/core/scan/scan_context.py, ggshield/utils/git_shell.py, tests/unit/cassettes/test_sca_scan_context_repository.yaml, tests/unit/cassettes/test_sca_scan_diff_context_repository.yaml, tests/unit/cassettes/test_scan_context_repository.yaml, tests/unit/cmd/iac/test_scan_all.py, tests/unit/cmd/iac/test_scan_diff.py, tests/unit/cmd/sca/test_diff.py, tests/unit/cmd/sca/test_scan.py, tests/unit/cmd/scan/test_path.py, tests/unit/cmd/scan/test_prepush.py, tests/unit/core/scan/test_scan_context.py, tests/unit/utils/test_git_shell.py
Compute the repository remote url. Pick one at random if several are found. This will allow a better connection between ggshield and GIM's database.
This will appear in the request headers: `'GGShield-Repository-URL': 'https://github.com/bridgecrewio/terragoat.git'`
All verticals will send this header. For IAC/SCA, the repository found is based on the provided path in the command.
For Secrets:
- No repository are sent for subcommands `archive`, `docker`, `docker-archive`, `docset`, `pypi`.
- Current working directory is sent for subcommands `ci`, `pre-commit`, `pre-push`, `pre-receive`, `range`. This is the directory that is checked by `check_git_dir`.
- For `path` subcommand, if the `paths` argument has exactly one element, it is sent. Otherwise cwd is sent.
- For `repo` subcommand, the …
=> Send the scanned repository's origin url as an extra header

ggshield/verticals/sca/file_selection.py
See https://linear.app/gitguardian/issue/SCA-1147/deactivate-correctly-in-on-prem
Note that the other API calls already display the associate error message.
=> chore(sca): show error in case of HTTP 501

changelog.d/20231006_173320_aurelien.gateau_oauth_scopes.md, ggshield/cmd/auth/login.py
Server-side is not fully ready for `--scopes`, so hide the option for now.
=> Hide --scopes for now

changelog.d/20231103_145927_paul.beslin.ext_change_diff_scan_json_output.md, ggshield/verticals/iac/output/iac_json_output_handler.py, ggshield/verticals/iac/output/schemas.py, tests/unit/verticals/iac/output/test_iac_diff_json_output.py
Changes the format of the JSON output for an iac diff scan.
<details>
<summary>Before</summary>
```json
{
"added_vulns": [
{
"filename": "terraform/aws/s3.tf",
"incidents": [
{
"policy": "Allowing public exposure of a S3 bucket can lead to data leakage",
"policy_id": "GG_IAC_0055",
"line_end": 8,
"line_start": 1,
"description": "AWS S3 Block Public Access is a feature that allows setting up centralized controls\\nto manage public access to S3 resources.\\n\\nEnforcing the BlockPublicAcls, BlockPublicPolicy and IgnorePublicAcls rule on a bucket\\nallows to make sure that no ACL (Access control list) or policy giving public access\\ncan be associated with the bucket, and that existing ACL giving public access to\\nthe bucket will not be taken into account.",
"documentation_url": …
```
=> refactor(iac): change iac diff scan json output format

ggshield/core/git_hooks/ci/__init__.py, ggshield/core/git_hooks/ci/repository.py, ggshield/core/scan/scan_context.py, tests/unit/core/scan/test_scan_context.py
Following #747, we want CI commands to gather the current repository URL from the CI environment variables first, falling back on `git remote -v` if variables are not found.
=> feat(core): try to extract repository url from ci env variables

ggshield/cmd/auth/login.py
=> Do not mention scopes in `auth login` description

ggshield/cmd/config/config_list.py, ggshield/cmd/sca/scan/__init__.py, ggshield/cmd/utils/common_decorators.py, ggshield/core/config/user_config.py, ggshield/core/filter.py, ggshield/utils/click/natural_order_group.py, ggshield/verticals/auth/oauth.py, ggshield/verticals/secret/secret_scan_collection.py, pyproject.toml
Pyright settings are a bit lax. Tighten them.
This PR enables`reportUnnecessaryTypeIgnoreComment` and `reportMissingParameterType` options. Going to file another PR in the future to enable `reportIncompatibleMethodOverride` and `reportMissingParameterType`.
=> More type checks

ggshield/core/config/config.py, ggshield/verticals/hmsl/utils.py
Please note that this is a bad fix because the isolated fs is not isolated and this should be fixed.
If I run this test alone with a hmsl_token in my file system, then it fails.
Please note that running the test will delete your current HMSL token if any.
=> chore: ensure no token is present before the test

changelog.d/20231120_192320_samuel.guillaume_scrt_3964_print_name_of_what_is_being_scanned_when_scanning_with.md, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/verticals/secret/docker.py, ggshield/verticals/secret/repo.py, ggshield/verticals/secret/rich_secret_scanner_ui.py, tests/unit/verticals/secret/test_scan_repo.py
Closes #212 
When using `--verbose` additional logs are printed per element scan: `Scanned {name of the element}`:
- `scan path`, `scan archive` and `scan pypi` print the filenames
- `scan repo` and `scan commit-range` print the commit ids
- `scan docker` keep the same behavior and print the name of the layers
=> Print name of what is being scanned when scanning with --verbose

Pipfile, Pipfile.lock, doc/schemas/api-status.json, doc/schemas/quota.json, doc/schemas/secret.json, scripts/run-functional-tests, tests/conftest.py, tests/functional/secret/test_scan_docker.py, tests/functional/secret/test_scan_path.py, tests/functional/secret/test_scan_repo.py, tests/unit/cmd/test_status.py
This PR adds JSON schemas for ggshield stable JSON outputs. It also modifies tests to use these schema to check ggshield JSON outputs actually match the schemas.
The schemas included cover the `secret scan`, `api-status` and `quota` commands.
=> Add JSON schemas for ggshield JSON outputs, test JSON outputs match them

Pipfile.lock, changelog.d/20231115_165150_paul.beslin.ext_implement_auto_ignore.md, ggshield/verticals/iac/collection/filter_ignored.py, ggshield/verticals/iac/collection/iac_diff_scan_collection.py, ggshield/verticals/iac/collection/iac_path_scan_collection.py, ggshield/verticals/iac/collection/iac_scan_collection.py, ggshield/verticals/iac/output/iac_json_output_handler.py, ggshield/verticals/iac/output/iac_output_handler.py, ggshield/verticals/iac/output/iac_text_output_handler.py, ggshield/verticals/iac/output/schemas.py, setup.cfg, tests/unit/verticals/iac/collection/test_filter_ignored.py, tests/unit/verticals/iac/collection/test_iac_scan_collection.py, tests/unit/verticals/iac/output/test_iac_json_output.py, tests/unit/verticals/iac/output/test_iac_output.py, tests/unit/verticals/iac/output/test_iac_text_output.py, tests/unit/verticals/iac/utils.py
The API now returns the status of each IaC incident on the GitGuardian app. We should use it to display only incidents that were not ignored on the app.
This applies to all IaC scan commands (all, diff, ci...) in all formats (text, JSON).
Depends on https://github.com/GitGuardian/py-gitguardian/pull/80
Commit 1 bumps the py-gitguardian version
Commits 2 and 3 contain some refactoring
Commit 4 is the main feature, described above
Commit 5 is a warning message in verbose mode when the source is not found by the API
=> Implement auto-ignore

ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/diff.py
Using an f-string on an enum will not return its value.
=> fix(iac): fix headers value for scanning mode

changelog.d/20231128_134023_carla.martet.ext_update_output_after_end_of_grace_period.md, ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/ci.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_utils.py, ggshield/cmd/iac/scan/precommit.py, ggshield/cmd/iac/scan/prepush.py, ggshield/cmd/iac/scan/prereceive.py, ggshield/core/config/user_config.py, ggshield/verticals/iac/output/iac_text_output_handler.py, tests/unit/cmd/iac/test_iac_scan_utils.py, tests/unit/verticals/iac/output/test_iac_text_output.py, tests/unit/verticals/iac/utils.py
Adapt ggshield's output when the grace period of an IAC incident ignored by a developer has been expired, for both all and diff scans.
=> feat(ignore): add output for no longer ignored incidents

changelog.d/20231201_155919_paul.beslin.ext_gitlab_ci_new_branch.md, ggshield/core/git_hooks/ci/previous_commit.py, ggshield/utils/git_shell.py, tests/functional/iac/test_iac_scan_ci.py, tests/unit/utils/test_git_shell.py
When pushing a new branch for the first time, the GGshield IAC and SCA CI cannot find the commit to use as ref.
As described [here](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html), `CI_COMMIT_BEFORE_SHA` is empty in that case.
Here we use git commands to find the starting commit of the new branch.
=> fix: fix gitlab push pipelines for new branches

tests/unit/cmd/iac/test_iac_scan_utils.py
Fix a test creating a file outside the `tmp_path`
=> fix(iac,test): use tmp file in test

doc/pre-receive-docker.sample
Our sample script to run GGShield as pre-receive via Docker does not work. This is because pre-receive commits are kept in a "quarantine" environment (see https://git-scm.com/docs/git-receive-pack#_quarantine_environment), git sets some environment variables before running the pre-receive hook so that git commands run by the hook can find the quarantined commits.
Furthermore, since these environment variables contain absolute path to directories, the path to the git checkout inside the Docker container must be the same as the path on the host.
- Propagate GIT_ALTERNATE_OBJECT_DIRECTORIES, GIT_OBJECT_DIRECTORY and GIT_QUARANTINE_PATH,
- Map PWD to PWD and use it as the current work directory.
=> Fix our pre-receive docker sample

changelog.d/20231219_154446_paul.beslin.ext.md, ggshield/cmd/iac/scan/all.py, ggshield/cmd/sca/scan/sca_scan_utils.py, ggshield/core/dirs.py, ggshield/verticals/iac/filter.py, ggshield/verticals/iac/output/iac_text_output_handler.py, tests/functional/iac/test_iac_scan_all.py, tests/unit/cassettes/test_sca_scan_subdir_tar.yaml, tests/unit/cmd/iac/test_scan_all.py, tests/unit/cmd/sca/test_scan.py, tests/unit/verticals/iac/test_filter.py
Currently, tars have two ways to be created in GGShield:
- For iac/sca scan diff, filepaths are listed using `git ls-tree --full-name`, which return filepaths relative to the git root
- For iac/sca scan all, filepaths are listed using `directory.rglob("*")` (where `directory` is the argument passed to the command), then returned relative to the directory using `path.relative_to(directory)`
- The difference comes from the necessity of listing files for a given git reference, for diff scans
However, the `all` behavior introduces two issues for IAC when calling the command with a Git subdirectory as argument:
1. File contents are not shown in the output, as the output handler looks for files relative to the git root, but is given filepaths relative to the subdir argument
2. Only the subdir …
=> Fix IAC scan all on subdirectories

Pipfile.lock, changelog.d/20231222_144942_aurelien.gateau_report_rate_limit.md, ggshield/cmd/honeytoken/create.py, ggshield/cmd/iac/scan/__init__.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/quota.py, ggshield/cmd/sca/scan/scan_common_options.py, ggshield/cmd/secret/scan/__init__.py, ggshield/cmd/status.py, ggshield/core/client.py, ggshield/core/ui/client_callbacks.py, setup.cfg, tests/unit/core/ui/test_client_callbacks.py
This PR makes use of the new callback introduced by https://github.com/GitGuardian/py-gitguardian/pull/83 to show a message when GGShield hits a rate-limit.
- 1st commit does more conversion to `ContextObj.get()`.
- 2nd commit shows a warning message when the rate-limit is hit.
=> Report rate-limits

changelog.d/20240105_163641_carla.martet.ext_fix_prepush_scan_all.md, ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/prepush.py, ggshield/core/scan/file.py, ggshield/utils/files.py, ggshield/verticals/iac/filter.py, tests/functional/iac/test_iac_scan_prepush.py
This MR aims to fix 2 edge cases during IaC pre-push scans:
- Use scan diff (instead of all) when pushing a new branch. The ref commit should be the last one on the parent branch.
- Prevent staged files to be scanned during pre-push "all" scans. It should only occurs on the first push for each repo. This avoids to push a vulnerability that could have been fixed in the staged files only.
=> fix(iac): prepush scan all

ggshield/__main__.py, ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/ci.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/precommit.py, ggshield/cmd/iac/scan/prepush.py, ggshield/cmd/iac/scan/prereceive.py, ggshield/cmd/sca/scan/sca_scan_utils.py, ggshield/cmd/secret/ignore.py, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/docset.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/cmd/utils/common_options.py, ggshield/cmd/utils/context_obj.py, tests/unit/cmd/sca/test_scan.py
This PR finishes the migration to ContextObj. It does two things:
- convert the remaining code to use ContextObj instead of dict access.
- remove dict-like support from ContextObj.
Interestingly this pointed out harmless typing errors, for example:
```python
if not scan.success or not isinstance(scan, IaCScanResult):
handle_scan_error(client, scan)
return None
```
pyright complained because the 2nd argument of `handle_scan_error()` expects a `Detail` instance, but pyright thought it could be a `IaCScanResult`. From a typing perspective, it could happen if `scan.success` was False but `isinstance(scan, IaCScanResult)` was True. In practice it cannot happen because `scan` is always a `Detail` when `scan.success` is False.
I wondered why it did not complain before, and I realized it's …
=> Finish migrating to ContextObj

Pipfile.lock, setup.cfg
Update py-gitguardian, preparing for next GGShield release.
=> Update py-gitguardian to 1.22.0

tests/unit/cassettes/test_sca_scan_subdir_with_ignored_vuln.yaml, tests/unit/cmd/sca/test_scan.py
- Adds a regression test for the case where a vuln isignored and scanning the subdir containing this vuln
- Did not change the way we filter SCA files as it seems required for Paul's fix to work
=> Xblanchot/sca 1322/fix sca ignored path

scripts/perfbench/perfbench_utils.py, scripts/perfbench/report_cmd.py, scripts/perfbench/run_cmd.py
This PR makes the following improvements to our performance benchmark script, following the exploration of tools to build standalone binaries for GGShield (see `agateau/pyinstaller` and `agateau/nuitka` branches):
- `run` command: add the ability to pass the path to a `ggshield` executable to the `-V` option.
- `report` command: add a CSV output mode.
It also fixes a bug in `--work-dir` which made it unusable.
=> Performance benchmark script improvements

changelog.d/20240115_102510_carla.martet.ext_handle_ci_on_force_pushing.md, ggshield/cmd/iac/scan/diff.py, ggshield/core/git_hooks/ci/previous_commit.py, tests/repository.py, tests/unit/core/git_hooks/ci/test_previous_commit.py
This MR intends to fix the behaviour of CI jobs after a forced push, on both IAC and SCA scans.
It used to trigger an error, trying to access a commit from before the history was rewritten.
This situation will now trigger a scan on all commits instead.
=> Handle IAC scans on CI after force pushing

Pipfile.lock, changelog.d/20240118_114340_xavier.blanchot_add_flags_on_fix_available.md, ggshield/cmd/sca/scan/all.py, ggshield/cmd/sca/scan/ci.py, ggshield/cmd/sca/scan/diff.py, ggshield/cmd/sca/scan/precommit.py, ggshield/cmd/sca/scan/prepush.py, ggshield/cmd/sca/scan/prereceive.py, ggshield/cmd/sca/scan/sca_scan_utils.py, ggshield/cmd/sca/scan/scan_common_options.py, ggshield/core/config/user_config.py, setup.cfg, tests/conftest.py, tests/unit/cassettes/test_sca_scan_all_ignore_fixable.yaml, tests/unit/cassettes/test_sca_scan_all_ignore_not_fixable.yaml, tests/unit/cassettes/test_sca_scan_diff_ignore_fixable.yaml, tests/unit/cassettes/test_sca_scan_diff_ignore_not_fixable.yaml, tests/unit/cmd/sca/test_sca_scan_utils.py, tests/unit/cmd/sca/test_scan.py, tests/unit/cmd/sca/test_scan_common_options.py
- Adds two new flags for sca scan commands : `--ignore-fix-available` and `--ignore-no-fix`
- Bump py-gitguardian version that fixes scan diff commands not sending user params to backend
=> Xblanchot/sca 1345/add flags on fix available

ggshield/verticals/auth/oauth.py
With this PR, GGShield makes use of the new `authentication-error` endpoint to show a nicely presented error message instead of the crude HTML page it previously generated.
Before:
After:
=> Redirect the user to a nicer page when the token cannot be created

setup.cfg
Change required before releasing ggshield 1.24.0
**Side effect:** pipenv also wanted to upgrade ipython to 8.20.0 which I prevented since this version is incompatible with Python 3.8.
=> chore(env): # Use py-gitguardian v1.13.0

Pipfile, Pipfile.lock, tests/unit/conftest.py
Latest versions of ipython do not support Python 3.8, we get rid of it. Devs can still install it if they need it.
=> chore(env): # Get rid of ipdb as a dependency

.github/workflows/ci.yml, Dockerfile, Pipfile.lock, ggshield/__main__.py, scripts/build-standalone-exe, scripts/standalone-exe/README.md, scripts/update-pipfile-lock/Dockerfile, tests/functional/conftest.py, tests/functional/utils.py
This PR adds the `scripts/build-standalone-exe` script. This script builds a standalone ggshield executable using [Pyinstaller](https://pyinstaller.org/en/stable/).
It builds binaries for:
- Windows x86_64
- Linux x86_64
- Mac x86_64
- Mac M1
The binaries can be downloaded from the bottom of the [summary page](https://github.com/GitGuardian/ggshield/actions/runs/7888013682?pr=833) of the action run (after all the deprecation warnings 😅)
Note: Building for Mac M1 required bumping the default Python version to 3.10 because 3.9 was not available on the GitHub M1 runner.
Best reviewed commit-by-commit.
=> Add a script to build a standalone binary

.github/workflows/ci.yml
Do not run functional tests for standalone executables when the PR comes from a fork: they fail because secrets are not available for PR from forks.
=> Unbreak PR from forks

tests/functional/conftest.py
This MR fixes `pytest_report_header`. The `startdir` argument was deprecated and removed in the new pytest release.
=> fix(tests): remove deprecated argument from pytest_report_header

ggshield/verticals/sca/file_selection.py, tests/unit/verticals/sca/test_file_selection.py
Changed `SCA_EXCLUSION_REGEXES` pattern & added a test.
=> chore(sca): ignore by default some more paths in sca

changelog.d/20240305_173920_aurelien.gateau_oauth_scopes.md, ggshield/cmd/auth/login.py
Now that the server-side is fully ready, we can unhide the `--scopes` option of `ggshield auth login`.
=> Unhide --scopes option

ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_utils.py, ggshield/cmd/utils/files.py, ggshield/core/config/utils.py, ggshield/core/dirs.py, ggshield/core/scan/commit_utils.py, ggshield/utils/files.py, ggshield/verticals/sca/file_selection.py, tests/unit/cmd/iac/test_scan_all.py, tests/unit/cmd/iac/test_scan_diff.py, tests/unit/cmd/sca/test_scan.py, tests/unit/cmd/scan/test_path.py, tests/unit/conftest.py, tests/unit/core/config/test_utils.py, tests/unit/core/scan/test_scan_context.py, tests/unit/core/test_client.py, tests/unit/utils/test_files.py
This MR :
- Adds a fixture in auto use to clear the cache from functools.lru_cache between tests
- Makes ggshield get the local config from the root of the repo (if it can find git and is scanning a git repo)
- Corrects the check to return an error when scanning an ignored directory
- Fixes the test `test_retrieve_client_invalid_api_url`
=> fix: Fix ignored paths in GGShield

.pre-commit-config.yaml, Pipfile.lock
This PR updates the Pipfile.lock and updates the version of ggshield to v1.26.0 in the pre-commit config file.
=> Post release changes

.pre-commit-config.yaml, Pipfile, Pipfile.lock, ggshield/cmd/iac/scan/all.py, ggshield/cmd/iac/scan/diff.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/sca/scan/scan_common_options.py, ggshield/cmd/utils/common_options.py, ggshield/core/config/utils.py, ggshield/core/errors.py, ggshield/core/scan/scan_context.py, ggshield/utils/git_shell.py, ggshield/utils/os.py, ggshield/verticals/iac/output/iac_text_output_handler.py, setup.cfg
Update Black to 24.3.0 to fix [CVE-2024-21503](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-21503).
This required disabling E704 in flake8. That seems to be expected: https://github.com/psf/black/issues/3887.
Needs #867 for CI to be green.
=> Update Black to 24.3.0

.github/workflows/ci.yml, .github/workflows/sign.yml, doc/dev/standalone-executables.md, scripts/build-standalone-exe, scripts/download
This PR extends `scripts/build-standalone-exe` to produce signed macOS binaries.
Signing .zip archives is not supported so the PR switches to producing .pkg installers for macOS.
GGShield files are installed in `/opt/gitguardian/ggshield-$version` and a `ggshield` symlink is created in `/usr/local/bin` so that ggshield can be started without having to modify $PATH.
Signing and notarizing is done using [rcodesign](https://gregoryszorc.com/docs/apple-codesign/0.27.0/index.html), a cross-platform tool to sign and notarize macOS applications.
Signing a .pkg installer requires first signing all executables and libraries we ship, then creating the .pkg, then signing the .pkg itself.
`scripts/build-standalone-exe` does not sign binaries unless called with `--sign`. It then expect some …
=> Sign macOS binaries

ggshield/cmd/sca/scan/sca_scan_utils.py, tests/unit/cassettes/test_sca_scan_subdir_with_ignored_vuln_with_until.yaml, tests/unit/cmd/sca/test_sca_scan_utils.py, tests/unit/cmd/sca/test_scan.py
Ggshield breaks when a vulnerability is ignored until a certain date.
1. Add a Pipfile and a Pipfile.lock with celery=4.4.7 as dependency
2. Ignore by adding the following in .gitguardian.yaml
```
- identifier: GHSA-q4xr-rc97-m4xx
path: "Pipfile.lock"
comment: "need to update code for compat"
until: "2024-06-30T10:00:00"
```
3. Run `ggshield sca scan all`
=> Ignoring with an until date is broken

.github/workflows/build_release_assets.yml, .github/workflows/ci.yml, .github/workflows/perfbench.yml, .github/workflows/tag.yml, changelog.d/20240410_114708_aurelien.gateau_release_signed_binaries.md
This PR extends our CI so that signed macOS binaries are built on each release.
Since testing CI code which only triggers on tags is not really possible, I used the following workarounds:
1. The existing sign.yml workflow has been turned into a more generic build_release_assets.yml workflow. This workflow is called by the tag.yml workflow. It can also be called manually.
2. I added a faketag.yml workflow. This is a copy of tag.yml except it triggers on pull requests and does not publish anything: each publish step is replaced by a step listing the downloaded artifacts which would be published. This allow verifies the changes to tag.yml as much as possible. You can see a run of it [here](https://github.com/GitGuardian/ggshield/actions/runs/8629377759).
This faketag.yml will be removed …
=> Release signed binaries

.gitguardian.example.yml, .gitguardian.yaml, changelog.d/20240405_171107_aurelien.gateau_deprecate_dash_config_keys.md, ggshield/core/config/auth_config.py, ggshield/core/config/user_config.py, ggshield/core/config/utils.py, ggshield/core/types.py, ggshield/verticals/secret/secret_scanner.py, tests/unit/cmd/iac/test_scan_all.py, tests/unit/cmd/sca/test_scan.py, tests/unit/cmd/scan/test_path.py, tests/unit/cmd/test_config_migrate.py, tests/unit/core/config/conftest.py, tests/unit/core/config/test_auth_config.py, tests/unit/core/config/test_user_config.py, tests/unit/core/config/test_utils.py, tests/unit/verticals/secret/snapshots/snap_test_secret_scanner.py
This PR makes deprecate dash-separated config keys and suggest using underscore-separate keys instead. This means one must use `show_secrets` and not `show-secrets`.
Using dash syntax still works but ggshield prints a warning message when it finds them and no longer makes any effort to refer to a key in the syntax it was written.
Here is what the output looks like with a dash-separated key in the "global" config and 3 other dash-separated keys in the current directory (~/src/ggshield-alt in my example):
```
$ ggshield api-status
/home/agateau/.gitguardian.yaml: Config key show-secrets is deprecated, use show_secrets instead.
/home/agateau/src/ggshield-alt/.gitguardian.yaml: Config key ignored-matches is deprecated, use ignored_matches instead. …
```
=> Deprecate dash-separated config keys

tests/functional/sca/test_sca_scan_ci.py, tests/functional/sca/test_sca_scan_diff.py, tests/functional/sca/test_sca_scan_prepush.py, tests/functional/sca/test_sca_scan_prereceive.py
New vulnerability on packages used for SCA testing were declared, making the tests fail because of the test on the number of found vulnerabilities.
Modifying functional test so that they're not dependant anymore on the number of found vulnerabilities (assuming they will remain greater than 1).
=> fix(sca): fixing functional tests after remote data being modified

changelog.d/20240412_143500_aurelien.gateau_fix_config_override.md, ggshield/core/config/user_config.py, ggshield/core/config/utils.py, ggshield/core/config/v1_config.py, tests/unit/core/config/test_auth_config.py, tests/unit/core/config/test_user_config.py, tests/unit/core/config/test_utils.py
If a key is set in the global configuration file, but not in the local one, then the global value is ignored unless it's a list key.
The current code loads each configuration file (global and local) as UserConfig instances, then merge the instances.
When the local UserConfig instance is loaded, if a key is not set, its field uses the default value. This is a problem because then the code responsible for merging the global and local UserConfig instances considers that the local value has explicitly been set and ignores the global value.
With this change, ggshield now loads each config as a *dict*, merges the dicts and creates a UserConfig instance from the merged dict. This fixes the bug because a dict keeps the notion of whether a key was set or not, so the merge works as expected.
Sorry …
=> Fix configuration override

changelog.d/20240430_143900_jonathan.griffe_allow_to_ignore_vulns_by_cve_id.md, ggshield/core/config/user_config.py, tests/unit/cmd/sca/test_sca_scan_utils.py, tests/unit/cmd/sca/test_scan.py
We want to allow ignoring vulnerabilities by CVE id in the config.
Ignore vulnerabilities identifier validation now additionally allows identifiers following the CVE id pattern.
=> feat(sca): allow ignoring vulnerabilities by CVE id

README.md
This PR improves the "Installation" and "Initial setup" sections of the README. See individual commit messages for details on the changes.
Note: This PR should not be merged until 1.27.0 is out, because the current release does not include the .pkg installer mentioned in the "Installation" section. This is why it's in draft mode.
=> Document standalone binaries

.github/workflows/build_release_assets.yml
The standalone binary smoke test would fail with:
```
build-os-packages: [INFO] test: running --help
Traceback (most recent call last):
File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>
File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook
File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
File "pkg_resources/__init__.py", line 77, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'
[2870] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```
This is caused by a breaking change in setuptools 70.0.0, fixed in pyinstaller 6.7.0.
References:
https://github.com/pypa/setuptools/issues/4374
https://github.com/pyinstaller/pyinstaller/issues/8554 …
=> Fix ggshield binary failing on Windows and Linux

actions-unstable/sca/action.yml, ggshield/core/constants.py, ggshield/verticals/sca/output/text_handler.py, tests/unit/cmd/sca/test_precommit.py, tests/unit/cmd/sca/test_scan.py
We want to see malicious vulnerabilities in the output of `ggshield sca scan all`
1. Updated `IncidentSeverity`
2. Changed some tests
=> feat(sca): Add support for malicious package detection

changelog.d/20240527_155007_salome.voltz_scrt_4543_ggshield_auth_login_flow_errors_are_not_handled_when.md, ggshield/cmd/auth/login.py, ggshield/core/config/config.py, ggshield/core/url_utils.py, tests/unit/cmd/auth/test_login.py, tests/unit/core/config/test_config.py
ggshield auth login flow errors were not handled when instance URL is invalid. 
Error thrown are handled, similarly to how error are handled with `GITGUARDIAN_INSTANCE='https://dashboard.gitguardian.com/abc' ggshield auth login --method=token` 
Run the following commands:
- `GITGUARDIAN_INSTANCE='https://dashboard.gitguardian.com/abc' ggshield auth login`
-  `GITGUARDIAN_INSTANCE='https://dashboard.example.com' ggshield auth login`
This also fixes the following issue: #892
=> fix(auth_login): error handling with invalid instance URL

changelog.d/20240520_164203_samuel.guillaume_secret_scan_change.md, ggshield/cmd/secret/scan/__init__.py, ggshield/cmd/secret/scan/changes.py, ggshield/core/scan/scan_mode.py, ggshield/utils/git_shell.py, ggshield/verticals/secret/repo.py, tests/repository.py, tests/unit/utils/test_git_shell.py
Add a command to scan the change between the current state and the default branch. Useful to check a feature branch does not add any new secret.
The naming (`changes`) may be discussed.
- Add an util to list the remotes
- Add an util to get the default branch
- Add a `changes` command under `secret scan`
- Clone a repository
- Checkout an un-merged feature branch
- Run `ggshield secret scan changes`
```
$ git clone git@github.com:GitGuardian/ggshield.git
$ git checkout sguillaume/secret-scan-change
$ ggshield secret scan change
Scanning... ━━━━━━━━━━━━━━━━━━ 100% 2 / 2
No secrets have been found
```
=> Add cmd to scan changes between the default branch and the current state (commits + staged)

changelog.d/20240515_144740_salome.voltz_scrt_4125_add_an_option_to_make_ggshield_secret_scan_path_honor.md, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/pypi.py, ggshield/core/scan/file.py, ggshield/utils/files.py, ggshield/utils/git_shell.py, ggshield/verticals/iac/filter.py, ggshield/verticals/sca/file_selection.py, tests/unit/cmd/scan/test_path.py, tests/unit/cmd/scan/test_pypi.py, tests/unit/utils/test_files.py, tests/unit/utils/test_git_shell.py, tests/unit/verticals/sca/test_file_selection.py
When running a scan at the root of a git checkout with `ggshield secret scan path`, files that are not part of the repository are scanned because the .gitignore is not honored. 
This creates irrelevant results. 
`secret scan path` now supports a `--use-gitignore` option to honor .gitignore files and related files (.git/info/exclude, $HOME/.config/git/ignore).
- Clone a repo 
- Checkout a branch
- You can scan the current state of the checkout with `ggshield secret scan path -r --use-gitignore .`
- Modify some file
- You can scan the modified files (even unstaged) with the same command
=> feat(secret): Add option --use-gitignore to command secret scan path

.gitguardian.yaml, changelog.d/20240604_110454_fnareoh_refacto_censor_lines.md, ggshield/core/filter.py, ggshield/core/lines.py, ggshield/verticals/secret/extended_match.py, ggshield/verticals/secret/output/secret_json_output_handler.py, ggshield/verticals/secret/output/secret_text_output_handler.py, ggshield/verticals/secret/secret_scan_collection.py, tests/unit/cassettes/multiple_secret_one_line.yaml, tests/unit/cassettes/test_scan_file_secret-False.yaml, tests/unit/cassettes/test_scan_file_secret-True.yaml, tests/unit/cassettes/test_scan_path_file_secret_with_validity.yaml, tests/unit/conftest.py, tests/unit/core/test_filter.py, tests/unit/core/test_lines.py, tests/unit/core/test_match_span.py, tests/unit/verticals/secret/output/snapshots/snap_test_text_output.py, tests/unit/verticals/secret/test_censor_extended_matches.py, tests/unit/verticals/secret/test_extended_match.py
After having worked on factorizing `make_matches` the new goal is to start storing context lines in the Extended Match and have the output entirely depend those line and no longer the `result.file.content`. 
In particular this means a way to censor Extended Match based on the lines and the indices in MatchSpan and no longer relying on censor content.
This MR is divided into several commits and test should pass after each commit (best reviewed by commit?). 
Several important change have been made:
- the `Line` class has been changed from a `NamedTuple` to a `SimpleNamespace` to be able to modify the line.content for censoring.
- The display patch hunk indication is no longer present in the patch output as it is not really part of the file and we do not display the patch symbols '+/-/ ' . …
=> Refactor: save lines in extended match and add censor method

changelog.d/20240606_114213_james.sinclair_auth_login_allow_self_signed.md, ggshield/cmd/auth/login.py
The `ggshield auth login` command isn't using the `--allow-self-hosted` flag.
Passing `allow_self_hosted` to the `create_client` function--as we're already doing for `auth logout`.
Without the fix, trying run `ggshield auth login --allow-self-signed` against a GitGuardian instance using an untrusted certificate or being routed through a TLS bump proxy will result in an error:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='hostname.example.com', port=443): Max retries exceeded with url: /exposed/v1/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
```
With the fix the certificate error won't appear.
=> Use allow-self-signed in auth login command

.github/workflows/build_release_assets.yml, .github/workflows/ci.yml, .github/workflows/perfbench.yml, Dockerfile, Pipfile.lock, changelog.d/20240606_180255_aurelien.gateau_update_pygitguardian.md, scripts/update-pipfile-lock/Dockerfile, setup.cfg
pygitguardian recently received [some error handling improvements](https://github.com/GitGuardian/py-gitguardian/pull/104). This PR makes ggshield use them.
Update pygitguardian, also update pipenv so that locking does not fail if there is a `.venv` directory in the project directory.
Point ggshield to a server which returns an HTTP response without the `Content-Type` header, it no longer crashes.
=> Update pygitguardian and pipenv

.github/workflows/build_release_assets.yml, .github/workflows/tag.yml, .gitignore, changelog.d/20240613_171809_aurelien.gateau_sign_windows_binaries.md, doc/dev/os-packages.md, scripts/build-os-packages/build-os-packages, scripts/build-os-packages/install-keylockertools, scripts/build-os-packages/macos-functions.bash, scripts/build-os-packages/windows-functions.bash
To make it easier to deploy GGShield on Windows, this PR makes the release process produce a signed standalone Windows binary, similar to the macOS one.
First commit refactors `scripts/build-os-packages/build-os-packages` to make room for Windows-specific signing code.
Second commit implements Windows signing code.
Third commit adds the signed binaries to the release assets.
- Trigger the [Build release assets](https://github.com/GitGuardian/ggshield/actions/workflows/build_release_assets.yml) CI workflow on the `agateau/sign-windows-binaries` branch. Tick the "Release mode" check box.
- From a Windows machine:
- Download the Windows asset.
- Unpack it.
- Double-click on `ggshield.exe`: no scary "Windows has prevented you from opening this file" popup should appear.
- Right-click on …
=> Add signed standalone binaries for Windows

Pipfile.lock, setup.cfg
The version of requests and urllib3 we depend on contained security issues. Those issues [were spotted](https://github.com/GitGuardian/ggshield/actions/runs/9566657039/job/26372468817) by `ggshield sca scan` when running on main, preventing the push of the unstable Docker images.
Update dependencies.
- CI still pass.
- Cross fingers that once this is merged in main, it triggers the push of the images.
=> Unblock push of the unstable Docker images

scripts/run-functional-tests
While debugging a CI failure, I tried to run functional tests using `make functest` and it failed. This PR fixes that.
- Do not fail if the `build` directory exists
- Do not fail (at least on my machine) when listing the wheel
- Remove the `[all]` when installing the wheel: there is no `all` variant anymore
Run `make functest` locally, with a `build` dir.
=> Make run-functional-tests script more robust

Pipfile, Pipfile.lock, setup.cfg
Update to py-gitguardian 1.15.2.
Pin voluptuous to avoid breaking tests on Python 3.8.
=> Update py-gitguardian to latest release

.github/workflows/ci.yml
Our CI included a workaround for a weird Windows-only failure with urllib3 and vcrpy. It seems it no longer happens so we can remove it.
=> Remove urllib3<2 hack

changelog.d/20240624_175518_aurelien.gateau_sarif.md, changelog.d/20240626_173927_aurelien.gateau_sarif.md, ggshield/cmd/hmsl/check.py, ggshield/cmd/hmsl/check_secret_manager/hashicorp_vault.py, ggshield/cmd/hmsl/decrypt.py, ggshield/cmd/hmsl/hmsl_utils.py, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/quota.py, ggshield/cmd/sca/scan/scan_common_options.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/cmd/status.py, ggshield/cmd/utils/common_options.py, ggshield/cmd/utils/context_obj.py, ggshield/cmd/utils/output_format.py, ggshield/core/scan/commit.py, ggshield/core/scan/file.py, ggshield/utils/files.py, ggshield/verticals/secret/output/__init__.py, ggshield/verticals/secret/output/secret_sarif_output_handler.py, tests/unit/core/scan/test_file.py, tests/unit/utils/test_files.py, tests/unit/verticals/secret/output/test_sarif_output.py
This PR adds support for generating reports in [SARIF format](https://sarifweb.azurewebsites.net/) when scanning for secrets.
See #869.
The PR first introduces a `--format (text|json)` option, and make existing commands use it. `--format json` is a more verbose version of `--json`, but it makes it possible to add new formats without adding a new flag for each format.
Then it introduces a `sarif` value for `--format`. This value is only used by `secret scan` commands for now. Adding it to other verticals will be done separately.
There is a bit of an impedance mismatch between ggshield secret output and SARIF output. A SARIF result is supposed to have one location, but a secret often contains multiple matches, so each match needs to be a separate location. To reconcile this, the result …
=> Add support for SARIF output for secret scanning

actions-unstable/sca/action.yml, changelog.d/20240709_183759_florian.perucki_sca_malicious_minimum_severity.md, ggshield/cmd/iac/scan/iac_scan_common_options.py, ggshield/cmd/sca/scan/scan_common_options.py, ggshield/cmd/utils/common_options.py
Malicious vulnerabilities support was introduced in #889 but the CLI severity argument for SCA was not updated.
Add support for `--minimum-severity MALICIOUS`, only for SCA scans
- ` pipenv run ggshield sca scan ci -h` should display MALICIOUS in the possible values of `--minimum-severity`
- ` pipenv run ggshield sca scan all -h` should display MALICIOUS in the possible values of `--minimum-severity`
- ` pipenv run ggshield iac scan ci -h` should NOT display MALICIOUS in the possible values of `--minimum-severity`
- ` pipenv run ggshield iac scan all -h` should NOT display MALICIOUS in the possible values of `--minimum-severity`
=> Add malicious severity option for SCA scans

Pipfile
The CI unit test on windows are[ currently broken](https://github.com/GitGuardian/ggshield/actions/runs/9874525991/job/27463370150) see also current MR like #931, I suspect it is coming from  pyfakefs 5.6.0, so I am constraining for now.
=> chore(ci): lock pyfakefs <5.6.0

ggshield/cmd/honeytoken/create.py, ggshield/cmd/honeytoken/create_with_context.py, tests/unit/cmd/honeytoken/test_honeytoken.py
The message from 403 errors in honeytoken commands is not used and replaced by a static one in order to explain how to access to the honeytoken feature, but if the error come from a rejection by IP allow list rules, this message is pointless.
If the error message from API is about the allowlist, then it is displayed instead of the static error message.
=> Reword error messages in honeytoken command

actions/sca/action.yml
- Change a typo made when creating the action from the IaC one, the wrong word was modified
=> doc(sca): fix name of the command in action documentation

.github/workflows/ci.yml
Jobs are failing for an obscure reason : see for instance https://github.com/GitGuardian/ggshield/actions/runs/10262514554/job/28392351544
Let's try a simple fix which is also good for tech debt.
I changed the value
Can you see the coverage in codecov ?
=> ci: use codecov action v4

.env.example, tests/conftest.py
We cannot run the functional tests on an instance monitoring the repo because the GG_VALID_SECRET has been marked as ignored which means it is ignored when scanning (see documentation).
- Add the ability to override the value with the .env so that we can have a secret not known by the dashboard
BEWARE: I did not modify the environment variables yet in the ggshield repo.
- functional tests should run with an account monitoring ggshield
=> Add a test secret as environment variable to hide it from the dashboard

.github/workflows/build_release_assets.yml, .github/workflows/ci.yml
I changed the values used in CI so that it uses env variable but forgot to grant access to these in the job. 
Checked occurrences of other env variables and add the new ones at the same place
All jobs are green during the next release
=> fix(ci): grant access to the correct environment variables for tests

changelog.d/20240807_172738_aurelien.gateau_macos_targz.md, scripts/build-os-packages/build-os-packages
In some circumstances, it's easier to deploy using a plain archive than using an installer. This PR makes `build-os-packages` create tar.gz archives in addition to the pkg files.
Modify `build-os-packages` to create tar.gz archives.
Unpack the archive, tests the ggshield binary works.
=> Make build-os-packages create tar.gz archives on macOS

changelog.d/20240819_162411_fnareoh_scrt_4759_optimize_files_to_scan_on_merge_commits.md, ggshield/cmd/secret/scan/precommit.py, ggshield/core/scan/commit.py, ggshield/core/scan/commit_utils.py, tests/functional/secret/test_merge_commit.py, tests/functional/utils_create_merge_repo.py, tests/unit/cmd/scan/test_precommit.py, tests/unit/core/scan/test_commit.py
The goal of this Merge Request is to improve the speed of the ggshield pre-commit scan when commiting after a merge conflict.
I created a script `gen_merge_commit.py` (temporarily added at the repository root) that creates a repo with two branches (master and feature_branch) a merge commit (with or without commit depending on the options) giving the following commit graph:
```
*   17d3a27 (HEAD -> feature_branch) Merge branch 'master' into feature_branch
|\  
| * db20e84 (master) Commit master n°2
| * 53a4cd0 Commit master n°1
| * a78f68d Commit master n°0
* | 9f5717c Commit feature branch
|/  
* e1db622 Initial commit
```
I then experimented and with it:
* Without conflict: our pre-commit does not seem to be called on merge
* With conflict: I implemented a proof of concept way to limit …
=> feat(performance): reduce the number of files scanned after merge conflict

changelog.d/20240819_162411_fnareoh_scrt_4759_optimize_files_to_scan_on_merge_commits.md, ggshield/cmd/secret/scan/precommit.py, tests/functional/utils_create_merge_repo.py
I failed and forgot to push my changes to the naming  :facepalm:
=> fix(naming): rename option to skip merge files

Pipfile.lock, changelog.d/20240906_141336_fnareoh_scrt_4693_ggshield_output_expose_incident_date_and_severity.md, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/core/config/user_config.py, ggshield/core/errors.py, ggshield/verticals/secret/output/schemas.py, ggshield/verticals/secret/output/secret_json_output_handler.py, ggshield/verticals/secret/output/secret_output_handler.py, ggshield/verticals/secret/output/secret_sarif_output_handler.py, ggshield/verticals/secret/secret_scan_collection.py, ggshield/verticals/secret/secret_scanner.py, setup.cfg, tests/unit/conftest.py, tests/unit/verticals/secret/output/test_json_output.py, tests/unit/verticals/secret/output/test_sarif_output.py
- Add `--with-incident-details` to output (json and sarif output only) more information about incident when the secret is already known by the gitguardian dashboard.
=> Add incident details option for json and sarif formats

changelog.d/20240910_170441_aurelien.gateau_fix_git_parser.md, ggshield/core/scan/commit_information.py, ggshield/core/scan/commit_utils.py, tests/unit/core/scan/test_commit.py
This PR fixes two problems:
Problem 1: sometimes the path for a diff is wrong. This is because `commit_utils.parse_patch()` assumes that the diffs are in the same order as the filenames in the commit header, which turns out to not always be true.
Problem 2: turning merge commits into individual commits by calling `git show` with the `-m` option does not work when fetching only some files inside the commit (which we do when scanning huge commits): it always return the changes from the first parent.
For problem 1: get the path name from the `+++ b/path` or `--- a/path` lines of the diff header.
For problem 2: maybe it would be possible to return the changes from the correct parents, but it felt simpler to stop using the `-m` option.
As a bonus, it simplifies `parse_patch()` because it can …
=> Fix git parser

changelog.d/20240819_162411_fnareoh_scrt_4759_optimize_files_to_scan_on_merge_commits.md, ggshield/cmd/secret/scan/precommit.py, tests/functional/secret/test_merge_commit.py, tests/functional/utils_create_merge_repo.py
Since #957, `secret scan ci` no longer scans non-conflicting files when scanning a merge commit. This PR changes the behavior of `secret scan pre-commit` to do the same, making the behavior more consistent.
Rename `--skip-unchanged-merge-files` to `--scan-all-merge-files`, invert its behavior in the code. Adjust the tests and the changelog entry.
Tests still pass.
=> Change behavior of `secret scan pre-commit` on merge commits

ggshield/core/scan/commit_utils.py, tests/unit/cassettes/test_scan_merge_commit.yaml, tests/unit/core/scan/test_commit.py, tests/unit/core/scan/test_commit_utils.py, tests/unit/verticals/secret/test_secret_scanner.py
GGShield output handlers currently do not support multi-parent commits. When they try to output them, they fail with list index errors:
```
$ ggshield secret scan commit-range HEAD^..
Error: list index out of range
Error: list index out of range
Scanning... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2 / 2
No secrets have been found
```
This only happens in the `main` branch, not in the current release.
Workaround this by post-processing the diff to turn it into a single-parent commit.
Using the same repository as in "Context":
```
$ ggshield secret scan commit-range HEAD^..
Scanning... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2 / 2
commit ca68e177596982fa38f181aa9944340a359748d2
Author: Aurelien Gateau <aurelien.gateau@gitguardian.com>
Date: Thu Sep 5 18:39:58 2024 +0200
> …
```
=> Fix output handling of merge commits

scripts/hmsl/hashicorp_vault.py, tests/functional/secret/test_scan_prereceive.py
This PR fixes two issues I hit during the release:
- The test vault server taking too long to start
- Some tests failing if `$GITGUARDIAN_INSTANCE` is set
- Increase timeout for the Vault server (also, turn that `while` loop into a `for`!)
- monkeypatch GITGUARDIAN_INSTANCE
=> Post-release fixes

changelog.d/20241010_171735_aurelien.gateau_fix_install_global.md, ggshield/cmd/install.py, ggshield/core/dirs.py, ggshield/utils/git_shell.py, tests/conftest.py, tests/unit/cmd/test_install.py
The fix from 1.32.1 to ignore the user git configuration when running git commands broke `ggshield install -m global` because this command modifies the global git config so it must not ignore the user git configuration.
This is #972.
- Add a `ignore_git_config` optional argument to `git_shell.git()`, which defaults to True. Set it to False in calls from cmd.install.
- Make `install_global()` install the git hooks in a sub-directory of the dir returned by `get_data_dir()`, this is required to be able to have tests which fail in the situation of 1.32.1.
- Rework test_install to be able to reproduce the bug. Add more tests.
Run `ggshield install -m global`. It should not crash anymore.
=> Fix `ggshield install -m global`

changelog.d/20241022_155052_jonathan.griffe_gitignore_paths.md, ggshield/utils/files.py, tests/unit/utils/test_files.py
In the GitGuardian vscode extension, we want to be able to avoid scanning files that are in the .gitignore.
The secret scan path command has an `use-gitignore` option that could do this, however it currently only applies to directories scanned recursively and not single files.
This MR proposes to also apply it to single files, which would allow the use of this argument in the vscode extension to avoid scanning gitignored files. This would also match the behavior of ignored paths in the `.gitguardian.yaml` config, for which an error is raised if an ignored directory is passed to the secret scan path command.
- In a repo, put a file in the `.gitignore`
- run `ggshield secret scan path --use-gitignore <your_file>`
No file should be scanned.
-->
=> feat: apply gitignore for file paths when using use-gitignore option

ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/changes.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/cmd/secret/scan/docset.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/verticals/secret/docker.py, ggshield/verticals/secret/output/secret_gitlab_webui_output_handler.py, ggshield/verticals/secret/output/secret_output_handler.py, ggshield/verticals/secret/repo.py, ggshield/verticals/secret/secret_scanner.py, tests/unit/cmd/scan/test_prepush.py, tests/unit/cmd/scan/test_prereceive.py, tests/unit/cmd/test_ignore.py, tests/unit/verticals/secret/output/test_gitlab_webui_output.py, tests/unit/verticals/secret/output/test_json_output.py, tests/unit/verticals/secret/output/test_sarif_output.py, tests/unit/verticals/secret/output/test_text_output.py, tests/unit/verticals/secret/test_scan.py, tests/unit/verticals/secret/test_scan_repo.py, tests/unit/verticals/secret/test_secret_scanner.py
Refactor how secret scan parameters are passed around: pass the SecretConfig around, instead of discrete args (both to the scanner, and in output handlers).
There should be no functional change.
=> chore: pass secret config around instead of discrete args

changelog.d/20241028_113440_jonathan.griffe_fix_precommit_git_merge_filename_with_spaces.md, ggshield/core/scan/commit_utils.py, tests/unit/core/scan/test_commit.py
When using `git merge` with a file which has a space in its name, the command fails with the error : 
- ValueError: too many values to unpack (expected 4)
Since the path is at the end of the parsed line (whose other components do not include spaces), we can simple add `maxsplit=3` as an argument to split.
- Make a repo
- Create a file with a space in its name in a first branch
- In another branch, create the same file with a different content
- In a branch run `git merge <other_branch>`
- Resolve the conflict and run `git merge --continue`
If there is no error, it means the bug is fixed.
=> fix(precommit): handle filenames with spaces in Commit.from_merge

.github/workflows/build_release_assets.yml, changelog.d/20241028_140533_aurelien.gateau_use_manylinux.md, scripts/build-os-packages/build-os-packages
Our RPM packages are built using GitHub Linux runner, which uses libc 2.35. This is too recent for RHEL 8.8, which uses libc 2.28.
This PR reworks the CI to build the RPM and deb packages inside a Rocky Linux 8.8 container.
Download the RPM from https://github.com/GitGuardian/ggshield/actions/runs/11552704333 (the RPM is inside the os-packages-ubuntu-22.04 artifact).
Start a rockylinux/rockylinux:8.8 container. The following command assumes $PWD contains code to scan and $GITGUARDIAN_API_KEY contains a valid API key (the `SUDO_UID` is a way to workaround the "dubious ownership" git error):
```
docker run -it --rm \
-e GITGUARDIAN_API_KEY \
-e SUDO_UID=$UID \
-v$PWD:$PWD -w $PWD \
rockylinux/rockylinux:8.8
```
Inside the container:
```
yum install -y git
rpm -i …
```
=> Fix RPM packages not working on RHEL 8.8

ggshield/core/config/config.py, tests/unit/verticals/hmsl/test_hmsl_utils.py
This MR teaches ggshield and HMSL how to support GitGuardian EU instance without special configurations.   
**Reminder:** ggshield gets a JWT from a GitGuardian dashboard to later be authorized to call an HMSL instance.
Before this MR, the GitGuardian instance targeted to get a JWT was derived from the HMSL_URL defined in the config if any.  This means that, unless you explicitly define it in your environment variable, you could never end up targeting the EU GitGuardian instance (there is no EU HMSL instance).
After this MR:  
- If a non-default HMSL_URL is defined with an env variable, we follow the user's logic, and we derive the GitGuardian dashboard URL from the HMSL URL.
- If not, we just use the dashboard URL defined by the user.
The logic is a bit complex here. Note that anyway, …
=> Add default EU support for HMSL

.github/workflows/build_release_assets.yml, changelog.d/20241029_092310_aurelien.gateau_improve_rpm_dependencies.md, scripts/build-os-packages/nfpm.yaml
This PR adds some smoke tests for our binary archives, and then make use of them to safely trim the dependencies of our RPM packages, fixing #983.
- Add smoke tests for:
- debian:stable (deb based)
- ubuntu:latest (deb based)
- rockylinux/rockylinux:8.8 (rpm based)
- opensuse/leap (rpm based)
- clearlinux:latest (test the raw tar.gz)
- Adjust dependencies of RPM packages.
Download the RPM from https://github.com/GitGuardian/ggshield/actions/runs/11569940273 (the RPM is inside the os-packages-ubuntu-22.04 artifact).
Start a rockylinux/rockylinux:8.8 container. The following command assumes $PWD contains code to scan and $GITGUARDIAN_API_KEY contains a valid API key (the `SUDO_UID` is a way to workaround the "dubious ownership" git error):
```
docker run -it --rm \
-e GITGUARDIAN_API_KEY \ …
```
=> Improve RPM dependencies

changelog.d/20241030_095506_guillaume.valadon_git_clone_mirror.md, ggshield/cmd/secret/scan/repo.py
Cloning a repository with `git clone --mirror` may retrieve more git objects, and lead to more secrets being detected.
By default ggshield now used `--mirror`. A new command line option could be used to disable this feature.
Clone `https://github.com/nightwatchcybersecurity/gb_testrepo_delete?tab=readme-ov-file`with and without the new option.
=> feat: add --no-mirror option

.pre-commit-config.yaml, changelog.d/20241028_145054_salome.voltz_refacto_json_output.md, doc/schemas/api-status.json, doc/schemas/config_list.json, ggshield/cmd/config/config_list.py, ggshield/cmd/status.py, tests/conftest.py, tests/unit/cmd/test_config.py, tests/unit/cmd/test_status.py
This MR contains two commits: 
-  [feat(config_list): Add JSON output] : Adds JSON output to command `ggshield config list`
- [fix(api-status): Update JSON output] : Updates JSON output for command `ggshield api-status` to include the instance which is checked. (This info is present in the text output). 
Also, [some stages name for pre-commit have been changed](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages).
=> fix(config_list): Add JSON output

changelog.d/20241104_101412_jonathan.griffe_improve_scan_ci_commit_selection.md, ggshield/core/git_hooks/ci/commit_range.py, ggshield/core/git_hooks/ci/get_scan_ci_parameters.py, tests/unit/cmd/scan/test_ci.py
There are some issues in the `ggshield secret scan ci` commit selection, as in some CIs including GitLab, when scanning a MR, new commits from the target branch were also scanned, leading to false positives. Also, in some CIs such as bitbucket only scanned the last commit, and did not handle scanning all the pushed commits or all the MR's commits when inside a MR.
This MR refactors the commit selection process, and unifies the code for all the different CIs, taking inspiration from what is done for SCA and IaC. Except for a few exceptions due to each CI's uniqueness, the behavior is always the following, in order of priority :
- If inside an MR, and inside a CI which gives access to the target branch, scan all commits from the MR.
- If the CI specifies a range of commits, scan that range, …
=> feat(ci): improve scan ci commit selection

changelog.d/20241107_194448_pierrelalanne_fix_with_incident_details_option.md, ggshield/cmd/secret/scan/secret_scan_common_options.py
If no default value is defined for the option `with-incident-details`, the behavior of ggshield can be misleading and actually bugged.
Indeed, each command or subcommand uses the decorator "add_secret_scan_common_options" to
collect values of several command options. This lets the user place the option --with-incident-details
at several level in the command line.
If they do so, the command or subcommand that does not have the flag will set the value to False
which can prevent the option from working correctly. For instance:
`ggshield secret scan --with-incident-details path dummy.py` => The option is set to False in the end because the path subcommand does not have the option defined.
`ggshield secret scan path --with-incident-details dummy.py` => The optiton is set to True, because …
=> Fix with-incident-details option

changelog.d/20241112_172503_jonathan.griffe_expand_instance_option.md, ggshield/cmd/quota.py, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/cmd/status.py, ggshield/cmd/utils/common_options.py, tests/unit/cmd/scan/test_path.py, tests/unit/cmd/test_status.py
Currently, we can login to a specific instance by using the --instance option.
We want to also be able to use a specific instance for other commands
The `--instance` option has been added to all `secret scan` command, as well as `api-status` and `quota` commands
Use commands specified above using the `--instance` with a non default instance and an API KEY for the instance in the `.env`. Verify that the command succeeds.
=> feat(cmd): add the instance option to more commands

.github/CODEOWNERS
Adding team as codeowners of the repo, to then add a branch protection rule on `main` requesting a review from codeowners.
=> chore: adding ggshield-admins team as codeowner

changelog.d/20241112_170752_jonathan.griffe_fix_secret_scan_option.md, ggshield/cmd/secret/scan/__init__.py, ggshield/cmd/secret/scan/archive.py, ggshield/cmd/secret/scan/changes.py, ggshield/cmd/secret/scan/ci.py, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/cmd/secret/scan/docset.py, ggshield/cmd/secret/scan/path.py, ggshield/cmd/secret/scan/precommit.py, ggshield/cmd/secret/scan/prepush.py, ggshield/cmd/secret/scan/prereceive.py, ggshield/cmd/secret/scan/pypi.py, ggshield/cmd/secret/scan/range.py, ggshield/cmd/secret/scan/repo.py, tests/unit/cmd/scan/test_path.py
The `--allow-self-signed` option can theoretically be placed at any level in all `ggshield secret scan` commands, but in practice does not work when passed at the last level (ex: `ggshield secret scan path --allow-self-signed`). This is due to the GGClient being instantiated before taking into account higher level options.
This MR makes the GGClient be instantiated in the command function to fix this issue.
Set up a proxy, for example with mitmproxy. To verify that it works, run `ggshield secret scan path <file>`, this should return a certificate error.
Run `ggshield secret scan path <file> --allow-self-signed`. It should succeed.
=> fix(scan): instantiate client after computing options

changelog.d/20241113_152802_jonathan.griffe_improve_api_status_output_info.md, doc/schemas/api-status.json, ggshield/__main__.py, ggshield/cmd/status.py, ggshield/core/config/config.py, ggshield/core/env_utils.py, tests/unit/cmd/test_status.py, tests/unit/core/test_env_utils.py
There are a lot of ways for ggshield users to set authentication credentials. When these credentials are invalid, it can be difficult to search where they were set. When multiple sources are set, it can also be complicated to find the source that was used.
This MR makes the api-status command return the source of the instance and API key used.
Run `ggshield api-status` and verify that the sources are the correct ones.
Repeat for all possible api key and instance locations.
=> feat(api-status): add api key and instance sources to the api-status command output

tests/unit/verticals/secret/output/test_sarif_output.py
test_leak_message() would sometimes fail because of a policy break fixture having its known_secret field set to True.
This was caused by test_sarif_output_for_flat_scan_with_secrets() modifying its test data, which comes from conftest.py.
Make the test copy its test data before modifying it to fix that.
Tests pass.
=> Unflakify test_text_output.py::test_leak_message()

ggshield/core/ui/plain_text/plain_text_scanner_ui.py
Micro-PR to fix a stray `print` I found while working on another PR.
Scan a file to skip, forcing ggshield to use the text UI.
Before:
```console
$ ggshield secret scan path --debug /boot/initrd.img 2>&1 | tee
...
2024-11-14 10:45:13 337171:337171 [D] root:140 max_doc_size=1048576
2024-11-14 10:45:13 337171:337171 [D] root:141 max_docs=20
Skipped file:///boot/initrd.img: content is over 1,048,576 bytes
...
```
After:
```console
$ ggshield secret scan path --debug /boot/initrd.img 2>&1 | tee
...
2024-11-14 10:45:28 337290:337290 [D] root:140 max_doc_size=1048576
2024-11-14 10:45:28 337290:337290 [D] root:141 max_docs=20
2024-11-14 10:45:28 337290:337290 [I] Skipped file:///boot/initrd.img: content is over 1,048,576 bytes
```
=> Replace stray print() call with ui.display_info()

ggshield/core/config/utils.py, tests/unit/core/config/test_user_config.py
GGshield was crashing when merging two badly formed user config. This was returning exit code 1 instead of 128.
=> fix(error): Catch error when merging two configs

changelog.d/20241120_160018_salome.voltz_scrt_4913_ggshield_with_incident_details_does_not_tell_about_required.md, ggshield/cmd/secret/scan/secret_scan_common_options.py, ggshield/core/errors.py, ggshield/verticals/secret/secret_scanner.py, pdm.lock, pyproject.toml, tests/unit/conftest.py, tests/unit/verticals/secret/test_secret_scanner.py
ggshield 1.32.0 can now return the details of an incident when a scan is run with the --with-incident-details option. For this feature to work, the token used to authenticate with the API must have the 'incidents:read' scope. This is currently not documented and if the token does not have the required scope, the flag will be silently ignored.
Ensure the token has the required scope before running a command with `--with-incident-details` flag. This MR goes with https://github.com/GitGuardian/py-gitguardian/pull/126
=> fix(with-incident-details): Ensure the token has the correct scope

pdm.lock, pyproject.toml, scripts/build-os-packages/build-os-packages, scripts/run-functional-tests, tests/functional/iac/test_iac_scan_diff.py, tests/unit/cmd/test_status.py, tests/unit/conftest.py, tests/unit/core/test_env_utils.py
Our test suites can run faster by making use of the pytest-xdist plugin, which can distribute tests on several cores.
- Install pytest-xdist
- Make our functional test suite use it
- Fix some pytest-xdist-related issues in our unit-test suite
Unfortunately this PR does not activate pytest-xdist on our unit-test suite for now because some tests randomly fail: sometimes log messages are not received when they should be (that could be related to the recent logging work I did 😒) and sometimes SecretScanner tests fail because of a corrupted `.cache_ggshield` file.
Run `make functest`. It should be faster.
=> Make functional tests faster

README.md, changelog.d/20241125_113845_severine.bonnechere_scrt_5123_before_next_ggshield_release.md, ggshield/__main__.py, tests/unit/cmd/auth/test_login.py, tests/unit/cmd/auth/test_logout.py, tests/unit/cmd/scan/test_docker.py, tests/unit/cmd/test_config.py, tests/unit/cmd/test_status.py
Python 3.8 is no longer supported by the Python Software Foundation. Thus, GGShield will soon require Python 3.9 and above to run.
In this PR we add a deprecation warning message to warn Python 3.8 users about future deprecation.
Output example:
```
$ ggshield api-status
API URL: https://dashboard.gitguardian.com
Status: healthy
App version: v2.119.0
Secrets engine version: 2.126.0
Instance source: default
API key source: user config
Warning: Python 3.8 is no longer supported by the Python Software Foundation. GGShield will soon require Python 3.9 or above to run.
```
=> chore: adding a warning message about Python 3.8

ggshield/cmd/utils/debug.py, ggshield/core/scan/scannable.py, ggshield/verticals/secret/repo.py, ggshield/verticals/secret/secret_scan_collection.py, tests/unit/verticals/secret/test_secret_scan_collection.py
This MR improves our logging, to help diagnose problems:
- Log ggshield version (in addition to logging py-gitguardian version)
- Log details about detected file encodings
- Improve logging for errors during scan
=> Logging improvements

scripts/release
When I ported ggshield to pdm, I forgot to update the code in `scripts/release` that checks in the lock file that we don't depend on a git version of a package.
Update the dependency check of scripts/release to use pdm.lock.
pdm.lock is a TOML file, whereas Pipfile.lock is a JSON file. This means the script now requires Python 3.11 because the `tomllib` package was only added in Python 3.11.
Replace pdm.lock with the one from a commit before the update to 1.18 and run `scripts/release prepare`. It should not crash and complain about a bad dependency.
=> Fix check_dependencies to use pdm.lock

tests/functional/secret/test_scan_path.py
I merged a PR which came from a fork. In this conditions functional tests are skipped (they can't be run because they don't have access to secrets). This broke `main` because there was a small bug in a test added by the PR.
Fix the test, and actually merge it with an existing one.
Tests pass!
=> Fix functional tests

changelog.d/20241129_155452_samuel.guillaume_spi_526_implement_deletion_commit_identification_in_ggshield.md, ggshield/verticals/secret/secret_scan_collection.py, ggshield/verticals/secret/secret_scanner.py
Related to SPI-526 and will close  #1001
We want to only fail secret scans when the secret is introduced.  
New fields have been added to the API to automatically detect if the content is a diff and if the secret has been added, deleted or in the context. (https://github.com/GitGuardian/py-gitguardian/pull/122)
- Add `not_introduced` as an ignore reason
- Make use of `diff_kind` to ignore policy breaks
`diff_kind` can be `null` (outside of commit) or `ADDITION`/`DELETION`/`CONTEXT`. We want to keep only the policy breaks with `diff_kind`:
- `null` => outside of commits, when scanning files or docker layers
- `ADDITION` => introduced by a commit
In #1024, a `--all-secrets` option will allow user to display ignored secrets.
- Create a repository
- Add a secret in commit A
- Edit the line …
=> feat(output): Only fail secret scans when the secret is introduced

.pre-commit-hooks.yaml
Fix deprecated pre-commit stages.
Fix #980
* Create a minimal pre-commit config (see below)
* Run `pre-commit run --all-files`
* No warning should appear.
Minimal config:
```yaml
repos:
- repo: https://github.com/gitguardian/ggshield
rev: v1.34.0 # update this version
hooks:
- id: ggshield
```
❓ Does this require a changelog entry? I'd be tempted to say no but I don't know your policies.
=> pre-commit: fix deprecated stages

ggshield/core/cache.py, ggshield/core/filter.py, ggshield/core/text_utils.py, ggshield/verticals/secret/docker.py, ggshield/verticals/secret/extended_match.py, ggshield/verticals/secret/output/schemas.py, ggshield/verticals/secret/output/secret_gitlab_webui_output_handler.py, ggshield/verticals/secret/output/secret_json_output_handler.py, ggshield/verticals/secret/output/secret_output_handler.py, ggshield/verticals/secret/output/secret_sarif_output_handler.py, ggshield/verticals/secret/output/secret_text_output_handler.py, ggshield/verticals/secret/secret_scan_collection.py, ggshield/verticals/secret/secret_scanner.py, tests/factories.py, tests/unit/cmd/test_ignore.py, tests/unit/verticals/secret/output/test_gitlab_webui_output.py, tests/unit/verticals/secret/output/test_json_output.py, tests/unit/verticals/secret/output/test_sarif_output.py, tests/unit/verticals/secret/output/test_text_output.py, tests/unit/verticals/secret/test_scan_repo.py, tests/unit/verticals/secret/test_secret_scan_collection.py, tests/unit/verticals/secret/test_secret_scanner.py
Following https://github.com/GitGuardian/ggshield/pull/1024 ,
-  ~~small~~ fix to make ignore reasons human readable.
- add ignore reason to json output schema
Perform scans with ignored secrets (either from config or  backend), with the `--all-secrets` options.
Ensure the output contains ignore info (both for text and json output)
Note: skipping changelog as it was included in previous MR.
=> chore: make ignore reason human readable in text output

changelog.d/20241213_184336_severine.bonnechere_handle_multi_parent_hunk_header.md, ggshield/core/scan/commit_utils.py, tests/unit/core/scan/test_commit_utils.py
When running a scan on a multi-parent commit with a hunk header with a trailing content, parsing of the header would fail and raise a `PatchParseError`.
This PR relates to https://github.com/GitGuardian/ggshield/pull/1022.
Handle trailing content in the regex used to parse multi-parent hunk header.
- Using previous version, on this repo
```bash
ggshield secret scan commit-range eb052f92b8bdaf0b32b9de1f1bc8c9493496c50f^..eb052f92b8bdaf0b32b9de1f1bc8c9493496c50f
Error: Could not parse patch (sha: eb052f92b8bdaf0b32b9de1f1bc8c9493496c50f): Failed to parse multi-parent hunk header '@@@ -23,37 -22,21 +23,52 @@@ from ggshield.core.types import Ignored'
Error: Could not parse patch (sha: eb052f92b8bdaf0b32b9de1f1bc8c9493496c50f): Failed to parse multi-parent hunk header '@@@ -23,37 -22,21 +23,52 …
```
=> Handle trailing content in multi-parent hunk header

.github/workflows/build_release_assets.yml, changelog.d/20250107_114112_aurelien.gateau_add_missing_dependency.md, scripts/build-os-packages/nfpm.yaml
The Python interpreter we bundle in our RPM package depends on libcrypt.so.1, but some distributions do not ship it anymore. This is why ggshield fails when it's installed using its RPM package on Red Hat Enterprise Linux 9 (See #1036).
- Update nfpm configuration to bundle the version of libcrypt we depend on.
- Update CI to test the RPM on RockyLinux 9 (more-or-less equivalent to RHEL 9).
- Build the RPM using rockylinux:8 instead of rockylinux:8.8 because the 8.8 Docker image does not receive security upgrades (we still test with 8.8 to ensure it works)
- Start a rockylinux 9 container
- Install git
- Install ggshield from the RPM
- Run `ggshield --version` → with the released version it fails, with the version from the CI it works
=> Add missing dependency

changelog.d/20250107_183611_aurelien.gateau_fix_windows_encoding.md, ggshield/__main__.py
When a Python program runs on Windows and its stdout or stderr is redirected to a file, the encoding changes from UTF-8 to the default OS encoding. This causes problems when Visual Studio tries to show pre-commit errors if they contain non-ASCII UTF-8 characters such as the ellipsis `…` (see #170).
Following a suggestion from @mherzberg (thanks!), force stdout and stderr to always be UTf-8.
- Install Visual Studio
- Setup a repository using ggshield as a pre-commit hook
- Leak a secret in a very long line (so that ggshield uses the ellipsis to crop it)
- Try to commit
Without the fix, Visual Studio says it can't decode the output of the pre-commit hook.
=> fix: force utf-8 to fix visual studio failure to print error messages

ggshield/cmd/utils/common_options.py
The help message for the `exit-zero` option can be slightly misleading, as one could understand that it will make the command exit with the 0 exit code, regardless of the error raised.
The `exit-zero` option help message was modified to make it clear it only applies when a secret is detected.
=> chore(cmd): improve the exit-zero option help message

.pre-commit-config.yaml, ggshield/verticals/secret/secret_scan_collection.py, scripts/check-import-linter-config.sh
This PR makes a few fixes in our pre-commit config:
- Make the import-linter-config hook work on Windows.
- Update hooks using `pre-commit autoupdate` (required one fix for a new error found by flake8).
- Run `pre-commit run -a`, on Windows.
=> Pre-commit fixes

changelog.d/20250108_124709_severine.bonnechere_handle_product_doc_api_urls.md, ggshield/core/config/config.py, tests/unit/cmd/auth/test_login.py
See https://github.com/GitGuardian/gitguardian-vscode/pull/67
When running `ggshield cmd --instance ${INSTANCE}`, if `INSTANCE` matches any of the URLs mentioned https://api.eu1.gitguardian.com/docs, it is replaced by the relevant URL.
- Checkout this branch
- Run any `ggshield` command having the `--instance` option available with `--instance https://api.gitguardian.com/v1` or `--instance https://api.eu1.gitguardian.com/v1`
- Command should work the same as if you put `--instance https://dashboard.gitguardian.com/` or `--instance https://dashboard.eu1.gitguardian.com/`
- Checkout this branch
- Checkout `main` at https://github.com/GitGuardian/gitguardian-vscode
- Replace [this line](https://github.com/GitGuardian/gitguardian-vscode/blob/816b609fba6dc09617216b2e3c9f22d14a9a3c83/src/lib/ggs …
=> fix: make API urls from GitGuardian work with GGShield

changelog.d/20250110_162407_salome.voltz_scrt_5247_ggshield_crashed_on_windows_because_of_git_command_too_long.md, ggshield/core/scan/commit.py, ggshield/core/scan/commit_utils.py, tests/unit/core/scan/test_commit_utils.py
`ggshield secret scan pre-commit` crashes on Windows when committing a merge with many long file names with `[WinError 206] The filename or extension is too long`. 
This happens because ggshield is building a git command that is longer than the maximum path length on Windows. (see #1032 ).
Functions that execute git commands on all files in a merge were updated to process files in batches, respecting the limit defined by `MAX_FILES_PER_GIT_COMMAND`.
On Windows:
- Runs the script provided in the issue description. ggshield should crash
- Test with the updated ggshield version. ggshield should proceed as expected.
=> fix: secret scan pre-commit crashing on big merges

README.md
Update Readme to indicate our Python version support
=> Update section in README for Python support

changelog.d/20250226_170555_severine.bonnechere_fix_paths_exclusion_in_docker.md, ggshield/cmd/secret/scan/docker.py, ggshield/cmd/secret/scan/dockerarchive.py, ggshield/verticals/secret/docker.py, tests/unit/cmd/scan/test_docker.py, tests/unit/verticals/secret/test_scan_docker.py
Fix https://github.com/GitGuardian/ggshield/issues/548
When a `.gitguardian.yaml` file was present with an `ignored_paths` entry, it wouldn't be taken into account.
- Paths to exclude are retrieved in the cli `_exclude_callback` function (see [here](https://github.com/GitGuardian/ggshield/blob/61c5bf3103eb490c9bb91f526b273e3408b72254/ggshield/cmd/secret/scan/secret_scan_common_options.py#L71)). They are then available in `ctx_obj.exclusion_regexes`. These `exclusion_regexes` are now passed as an option to the main function `docker_scan_archive` and then properly handled.
- Note that this fix consists in plugging the whole `_exclude_callback` feature in docker scanning: it means that other patterns such as `IGNORED_DEFAULT_WILDCARDS` are now applied too.
- Create a minimalist Dockerfile. …
=> fix: handle ignored_paths in docker scan

changelog.d/20250306_155222_severine.bonnechere_scrt_5358_ggshield_error_with_emojis_in_file_name.md, ggshield/utils/git_shell.py, tests/unit/cassettes/test_emoji_filename.yaml, tests/unit/cmd/scan/test_precommit.py
Today, when running `ggshield secret scan pre-commit` on a patch modifying a file which has an emoji in its name, the command fails and raises an error.
Surprisingly, the issue is coming from the git command itself. The header and content are not encoded the same in the output of below command (cf screenshot).
We can see that
- in the header the emoji is there
- in the diff part, the emoji was replaced by its utf-8 octal representation (`\360\237\230\212`).
In ggshield internals, we encode both header and content in utf-8. But the emoji in the header is getting encoding by an utf-8 byte (hexadecimal) representation: `\xf0\x9f\x98\x8a`. At some point we check filenames against each other and this is were the issue arises.
From what I understood, octal-representation occurs in some …
=> Fix ggshield error with emojis in file name

changelog.d/20250310_144245_severine.bonnechere_handle_longpaths.md, ggshield/utils/git_shell.py, tests/unit/utils/test_git_shell.py
We have been informed of an issue with ggshield and longpaths on Windows in https://github.com/GitGuardian/ggshield/issues/1032.
As the issuer reported, setting `core.longpaths` to true fixes the issue.
ℹ️  Note that this option is only available on the [git-for-windows fork](https://github.com/search?q=repo%3Agit-for-windows%2Fgit%20longpaths&type=code). With the standard git cli, this option has no effect.
It was not possible to replicate the encountered issue, but the issuer confirmed [it worked](https://github.com/GitGuardian/ggshield/issues/1032#issuecomment-2694550173) with their original case.
=> fix: enable core.longpaths on git commands

.github/workflows/ci.yml, changelog.d/20250319_112122_jonathan.griffe_remove_python_3_9_support.md, doc/dev/getting-started.md, doc/pre-receive.sample, ggshield/__main__.py, pdm.lock, pyproject.toml, scripts/create-ghe-environment, tests/unit/cmd/auth/test_login.py, tests/unit/cmd/auth/test_logout.py, tests/unit/cmd/scan/test_docker.py, tests/unit/cmd/test_config.py, tests/unit/utils/test_files.py
We have previously added deprecation warning when the python version was 3.8, to prepare removing its support in GGShield.
This MR removes support for GGShield 3.8
=> chore: remove support for python 3.8

.github/workflows/build_release_assets.yml, changelog.d/20250321_152657_aurelien.gateau_support_host_certs.md, ggshield/__main__.py, pdm.lock, pyproject.toml
This PR makes ggshield use the system certificates instead of the bundled ones.
Fixes #1067.
Integrate [truststore](https://pypi.org/project/truststore/) and use it. Note that this only works with Python >= 3.10.
The 2nd commit changes the CI so that the Linux standalone installer uses Python 3.10 instead of 3.9.
I tested this using `mitmproxy`:
- Install it (`pipx install mitmproxy` for example)
- Follow [the documentation](https://docs.mitmproxy.org/stable/overview-getting-started/) to generate and install its certificate
- Tell ggshield to use the proxy (`export https_proxy=http://localhost:8080`)
- Run `ggshield api-status` using the main branch → it crashes with SSL errors
- Run `ggshield api-status` using this branch → it does not crash and you can see the exchange in mitmproxy UI
=> Use system certificates

.github/workflows/tag.yml, changelog.d/20250408_150950_jonathan.griffe_add_ci_push_to_choco_job.md, scripts/push-to-chocolatey/ggshield.nuspec, scripts/push-to-chocolatey/push-to-chocolatey
A job was added to automatically publish new ggshield versions on chocolatey.
This MR also introduces the ggshield.nuspec used for the ggshield chocolatey package.
- Test the push-to-chocolatey script
- Download the nupkg and install it on a windows VM with "choco install ggshield -source ."
=> chore(ci): add job to push new version to chocolatey

.github/workflows/tag.yml
See https://github.com/GitGuardian/homebrew-tap/pull/8.
Remove CI job updating ggshield formula on https://github.com/GitGuardian/homebrew-tap.
Not really possible to validate locally.
=> chore: don't update GitGuardian/homebrew-tap/ anymore

scripts/push-to-chocolatey/push-to-chocolatey
According to the documentation, VERIFICATION.txt should be in the tools folder of the package.
Moving it there also makes it included in the package since all files in "tools" are included.
=> chore: move VERIFICATION.txt to tools package folder

scripts/push-to-chocolatey/push-to-chocolatey
To be able to preview the license in the chocolatey community repository, the license must have a .txt extension.
In the chocolatey package build script, when copying the LICENSE into the package, add a .txt extension
=> chore: add txt extension to license in chocolatey package

changelog.d/20250506_160702_aurelien.gateau_fix_censor.md, ggshield/core/filter.py, tests/unit/core/test_filter.py
When called with a one-char string, censor_string() would return the same
char doubled (so `censor_string("a")` would return "aa").
The behavior was also not good on 2-char string: it would leave the string
unchanged, and on 3-char string it would hide only the middle char.
1st commit changes this behavior to make sure that:
- 1 & 2 char strings are fully censored
- 2 chars out of 3 are censored in a 3 char string
2nd commit simplifies the implementation.
- Create a file containing a one-char match secret.
- Scan it with `ggshield secret scan path` → it should not crash.
=> Fix censor_string() behavior on short strings

changelog.d/20250514_134109_aurelien.gateau_docker_scan_usr_src_app.md, ggshield/verticals/secret/docker.py, tests/unit/cmd/scan/test_docker.py
`/usr/src/app` is often used to store the containerized app, so we should scan it.
Tune the file ban list to ensure we scan the wanted directory.
- Put a secret in a file called config.py
- Create a Dockerfile with this content:
```
FROM scratch
COPY config.py /usr/src/app
```
- Build an image for it: `docker build -t ggshield-src-app .`
- Scan it with ggshield: `ggshield secret scan docker ggshield-src-app` → it finds the secret
=> Make `scan docker` scan files in /usr/src/app

changelog.d/20250515_155151_aurelien.gateau_dont_require_git.md, ggshield/core/env_utils.py, ggshield/core/errors.py, ggshield/utils/git_shell.py, tests/functional/secret/test_scan_path.py, tests/unit/utils/test_git_shell.py
When running on a machine where git is not in $PATH, ggshield would crash because there are a few places that tries to use git at startup. This is annoying because there are valid situations (such being installed inside a Docker image) where git is not available but we would like to use non-git-related scan commands such as `secret scan path`.
- Add a test that tries to run `secret scan path` when git is not available
- Fix all crashes so that the test pass
- Install ggshield in a Docker image that does not have git installed.
- Try to scan a path, it should not crash.
=> Do not require git

ggshield/core/text_utils.py, ggshield/verticals/secret/output/secret_sarif_output_handler.py, ggshield/verticals/secret/output/secret_text_output_handler.py, tests/unit/verticals/secret/output/snapshots/snap_test_text_output.py, tests/unit/verticals/secret/output/test_sarif_output.py, tests/unit/verticals/secret/output/test_text_output.py
In ggshield text output, the value for the "Known by GitGuardian dashboard" is "YES" or "NO", but the value for the new "Secret in Secrets Manager" is "true" or "false".
This commit makes "Secret in Secrets Manager" use "YES" or "NO" too.
Before:
```
>> Secret detected: Generic Password
Validity: No Checker
Occurrences: 1
Known by GitGuardian dashboard: NO
Incident URL: N/A
Secret SHA: bcab461d00a692b05add54f547d83660290e1a22504db841d7a9c325451bf20b
Secret in Secrets Manager: False
Detector documentation: https://docs.gitguardian.com/secrets-detection/secrets-detection-engine/detectors/generics/generic_password
```
After:
```
>> Secret detected: Generic Password
Validity: No Checker
Occurrences: 1
Known by GitGuardian dashboard: NO
Incident URL: N/A
Secret SHA: …
```
=> fix: make "Secret in Secrets Manager" more consistent

.github/workflows/build_release_assets.yml, .github/workflows/ci.yml, .github/workflows/perfbench.yml, CHANGELOG.md
[CI is failing](https://github.com/GitGuardian/ggshield/actions/runs/15779418933/job/44482026043) on `clearlinux` tests because libstdcpp is not installed in the docker image for `clearlinux`. This is most likely new and coming from the latest version of the [docker image](https://hub.docker.com/_/clearlinux)  but we can't know for sure as the image isn't versioned. 
- install libstdcpp lib for clearlinux
- cosmetic changes: move all git installs in the new requirements step
CI failed before, succeeds after.
=> fix: install libstdcpp for clearlinux

CHANGELOG.md, changelog.d/20250620_145029_severine.bonnechere_fix_pull_docker_apple_silicon.md, ggshield/verticals/secret/docker.py, tests/unit/verticals/secret/test_scan_docker.py
A user reported the following issue on Apple Silicon:
```bash
ggshield secret scan docker bimapangestu/pertamina-login:latest
Saving docker image...
need to download image first
latest: Pulling from bimapangestu/pertamina-login
no matching manifest for linux/arm64/v8 in the manifest list entries
Error: Image "bimapangestu/pertamina-login:latest" not found
```
After pulling the image separately (using `docker pull bimapangestu/pertamina-login:latest` or `docker pull --platform linux/amd64 bimapangestu/pertamina-login:latest`), it ended working.
When `docker pull` command fails, retry pulling specifically the `linux/amd64` image.
Use case on Apple Silicon:
- Make sure not to have locally pulled `bimapangestu/pertamina-login:latest` image (`docker rmi -f bimapangestu/pertamina-login:latest`) …
=> fix: docker pull fallback on linux amd64 for apple silicon

.github/workflows/ci.yml, .github/workflows/tag.yml, changelog.d/20250709_184012_severine.bonnechere_produce_docker_arm_images.md
Solves #952 
- update docker build and push flow in CI: we were using action docker/build-push-action v1 while latest version is v6. Multi-platform isn't supported in v1.
- Provide multi-platform images for linux/amd64 and linux/arm64.
Multi-plaform support is ensured by [this line](https://github.com/GitGuardian/ggshield/pull/1112/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR198)
Most of the work was about updating the jobs to latest version.
Main points of attention / notes:
- ghcr.io is the same as docker.pkg.github.com which is deprecated, see [here](https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry)
- There is 1 unique job pushing to both docker and github registries …
=> feat: push linux/arm64 docker images

changelog.d/20250819_142137_salome.voltz_scrt_5808_pyinstaller_deprecation_warning.md, scripts/build-os-packages/build-os-packages
This MR fixes https://github.com/GitGuardian/ggshield/issues/1119, following [Pyinstaller maintainers recommandations](https://github.com/orgs/pyinstaller/discussions/9148#discussioncomment-13289368) 
- Download packages [here](https://github.com/GitGuardian/ggshield/actions/runs/17043104348)
=> chore(build-packages): Remove PyInstaller deprecation warning
